using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using static Constants;

public class FlagsManager : MonoBehaviour
{
    public static FlagsManager Manager;

    public List<FlagColor> FlagColors = new List<FlagColor>();

    public static List<Sprite> AllSymbols = new List<Sprite>();

    public static string[] euCountriesIDs = { "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE", "EU", "IS", "LI", "NO", "CH", "AL", "ME", "MK", "RS", "TR", "AD", "BY", "BA", "MD", "MC", "RU", "SM", "UA", "GB", "VA" };
    public static string[] africaCountriesIDs = { "AI", "AL", "AN", "BA", "BE", "BT", "BF", "BR", "BU", "BH", "CR", "CI", "CV", "CA", "DH", "DC", "EG", "ER", "ET", "GB", "GA", "GH", "GC", "GU", "HO", "IC", "KY", "LE", "LI", "LB", "MD", "MW", "ML", "MN", "MU", "MA", "MB", "ME", "MR", "MZ", "NM", "NG", "NI", "PY", "CH", "RD", "RE", "RG", "RS", "SY", "RC", "RI", "RW", "SE", "SN", "SL", "SO", "SA", "SS", "SU", "SH", "SW", "TA", "TO", "TN", "UG", "UC", "YA", "ZA", "ZM", "ZI", "ZU" };
    public static string[] asiaCountriesIDs = { "AH", "AF", "AK", "AL", "AR", "AM", "AY", "AB", "AZ", "BY", "BI", "BA", "BE", "BH", "BO", "BN", "BR", "BU", "CM", "CH", "CU", "DK", "EL", "EV", "GE", "HA", "HE", "HI", "HT", "IN", "ID", "IR", "IQ", "IS", "IT", "JA", "JW", "JO", "KA", "KZ", "KT", "KR", "KU", "KY", "LA", "LE", "MA", "MS", "ME", "MY", "MO", "MG", "MM", "NA", "NG", "NE", "NS", "OM", "OS", "OT", "PK", "PE", "PH", "PO", "QA", "RK", "ML", "SA", "SB", "SC", "SE", "SI", "SR", "SU", "SY", "TW", "TJ", "TS", "TM", "TH", "TB", "TL", "TN", "TU", "TK", "TV", "UL", "UA", "UR", "UZ", "VT", "YK", "YE" };
    public static string[] oceaniaCountriesIDs = { "AU", "CI", "CO", "FJ", "GM", "HA", "KI", "MA", "MI", "ME", "MC", "NA", "NB", "NC", "GU", "NZ", "NI", "PN", "PO", "PA", "SA", "SI", "SO", "TO", "TU", "TV", "VA", "YO" };
    public static string[] northAmericaCountriesIDs = { "AC", "AU", "AL", "AM", "AN", "AT", "AR", "AB", "AZ", "BB", "BC", "BL", "BO", "CA", "CG", "CE", "CY", "CH", "CI", "CO", "CU", "BA", "CR", "CB", "DA", "DO", "DR", "ES", "EK" };
    public static string[] southAmericaCountriesIDs = { "AC", "AR", "BE", "BO", "RR", "BR", "CH", "CI", "CO", "CR", "EC", "ES", "FI", "FG", "GU", "GY", "HO", "IN", "JM", "MY", "NA", "NI", "PM", "PA", "PE", "SU", "TT", "UR" };

    #region Basic Events
    private void Awake()
    {
        Manager = this;

        DontDestroyOnLoad(gameObject);
    }

    private void Start()
    {
        foreach (var flag in Flags)
        {
            Sprite flagSprite = Resources.Load<Sprite>("Flags/World/" + flag.abbrev);

            Sprite symbolSprite = Resources.Load<Sprite>("Flags/World/" + flag.abbrev + "_symbol");
            Sprite noSymbolSprite = Resources.Load<Sprite>("Flags/World/" + flag.abbrev + "_noSymbol");

            flag.sprite = flagSprite;

            if (symbolSprite != null && noSymbolSprite != null)
            {
                flag.hasSymbol = true;
                flag.symbol = new FlagSymbol(symbolSprite, noSymbolSprite);
                AllSymbols.Add(symbolSprite);
            }

            flag.country.isEU = euCountriesIDs.Contains(flag.abbrev);
            flag.country.isAfrica = africaCountriesIDs.Contains(flag.abbrev);
            flag.country.isAsia = asiaCountriesIDs.Contains(flag.abbrev);
            flag.country.isOceania = oceaniaCountriesIDs.Contains(flag.abbrev);
            flag.country.isNorthAmerica = northAmericaCountriesIDs.Contains(flag.abbrev);
            flag.country.isSouthAmerica = southAmericaCountriesIDs.Contains(flag.abbrev);
        }

        foreach (var flagColor in FlagColors)
        {
            Flag associatedFlag = Flags.FirstOrDefault(e => e.abbrev == flagColor.ID);

            if (associatedFlag != null)
            {
                associatedFlag.hasColors = true;
                flagColor.graySprite = Resources.Load<Sprite>("Flags/World/" + associatedFlag.abbrev + "_gray");
                associatedFlag.colors = flagColor;
            }
        }

        Debug.Log("Initialised: " + Flags.Count + " flags - " + FlagColors.Count + " colors - " + AllSymbols.Count + " symbols");
    }
    #endregion

    public void ChangeFlagsPack()
    {
        if (UITexts.selectedLanguage == UITexts.en)
        {
            foreach (var flag in Flags)
            {
                flag.name = world_EN.FirstOrDefault(e => e.ID == flag.abbrev).name;
            }
            return;
        }

        if (UITexts.selectedLanguage == UITexts.ro)
        {
            foreach (var flag in Flags)
            {
                flag.name = world_RO.FirstOrDefault(e => e.ID == flag.abbrev).name;
            }
            return;
        }

        if (UITexts.selectedLanguage == UITexts.fr)
        {
            foreach (var flag in Flags)
            {
                flag.name = world_FR.FirstOrDefault(e => e.ID == flag.abbrev).name;
            }
            return;
        }

        if (UITexts.selectedLanguage == UITexts.es)
        {
            foreach (var flag in Flags)
            {
                flag.name = world_ES.FirstOrDefault(e => e.ID == flag.abbrev).name;
            }
            return;
        }
    }

    public static List<Flag> Flags = new List<Flag>()
    {
         new Flag { abbrev = "AD", difLevel = 2},
         new Flag { abbrev = "AE", difLevel = 1},
         new Flag { abbrev = "AF", difLevel = 1},
         new Flag { abbrev = "AG", difLevel = 3},
         new Flag { abbrev = "AI", difLevel = 3},
         new Flag { abbrev = "AL", difLevel = 1},
         new Flag { abbrev = "AM", difLevel = 2},
         new Flag { abbrev = "AN", difLevel = 3},
         new Flag { abbrev = "AO", difLevel = 3},
         new Flag { abbrev = "AQ", difLevel = 1},
         new Flag { abbrev = "AR", difLevel = 1},
         new Flag { abbrev = "AS", difLevel = 2},
         new Flag { abbrev = "AT", difLevel = 1},
         new Flag { abbrev = "AU", difLevel = 1},
         new Flag { abbrev = "AW", difLevel = 2},
         new Flag { abbrev = "AX", difLevel = 3},
         new Flag { abbrev = "AZ", difLevel = 1},
         new Flag { abbrev = "BA", difLevel = 1},
         new Flag { abbrev = "BB", difLevel = 2},
         new Flag { abbrev = "BD", difLevel = 1},
         new Flag { abbrev = "BE", difLevel = 1},
         new Flag { abbrev = "BF", difLevel = 3},
         new Flag { abbrev = "BG", difLevel = 1},
         new Flag { abbrev = "BH", difLevel = 2},
         new Flag { abbrev = "BI", difLevel = 3},
         new Flag { abbrev = "BJ", difLevel = 3},
         new Flag { abbrev = "BL", difLevel = 3},
         new Flag { abbrev = "BM", difLevel = 2},
         new Flag { abbrev = "BN", difLevel = 3},
         new Flag { abbrev = "BO", difLevel = 1},
         new Flag { abbrev = "BR", difLevel = 1},
         new Flag { abbrev = "BS", difLevel = 1},
         new Flag { abbrev = "BT", difLevel = 2},
         new Flag { abbrev = "BV", difLevel = 3},
         new Flag { abbrev = "BW", difLevel = 2},
         new Flag { abbrev = "BY", difLevel = 1},
         new Flag { abbrev = "BZ", difLevel = 3},
         new Flag { abbrev = "CA", difLevel = 1},
         new Flag { abbrev = "CC", difLevel = 3},
         new Flag { abbrev = "CD", difLevel = 3},
         new Flag { abbrev = "CF", difLevel = 3},
         new Flag { abbrev = "CG", difLevel = 3},
         new Flag { abbrev = "CH", difLevel = 1},
         new Flag { abbrev = "CI", difLevel = 3},
         new Flag { abbrev = "CK", difLevel = 3},
         new Flag { abbrev = "CL", difLevel = 2},
         new Flag { abbrev = "CM", difLevel = 2},
         new Flag { abbrev = "CN", difLevel = 1},
         new Flag { abbrev = "CO", difLevel = 1},
         new Flag { abbrev = "CR", difLevel = 1},
         new Flag { abbrev = "CU", difLevel = 1},
         new Flag { abbrev = "CV", difLevel = 2},
         new Flag { abbrev = "CX", difLevel = 2},
         new Flag { abbrev = "CY", difLevel = 2},
         new Flag { abbrev = "CZ", difLevel = 1},
         new Flag { abbrev = "DE", difLevel = 1},
         new Flag { abbrev = "DJ", difLevel = 3},
         new Flag { abbrev = "DK", difLevel = 1},
         new Flag { abbrev = "DM", difLevel = 2},
         new Flag { abbrev = "DO", difLevel = 1},
         new Flag { abbrev = "DZ", difLevel = 2},
         new Flag { abbrev = "EC", difLevel = 2},
         new Flag { abbrev = "EE", difLevel = 1},
         new Flag { abbrev = "EG", difLevel = 1},
         new Flag { abbrev = "EH", difLevel = 3},
         new Flag { abbrev = "ER", difLevel = 3},
         new Flag { abbrev = "ES", difLevel = 1},
         new Flag { abbrev = "ET", difLevel = 2},
         new Flag { abbrev = "FI", difLevel = 1},
         new Flag { abbrev = "FJ", difLevel = 2},
         new Flag { abbrev = "FK", difLevel = 3},
         new Flag { abbrev = "FM", difLevel = 3},
         new Flag { abbrev = "FO", difLevel = 2},
         new Flag { abbrev = "FR", difLevel = 1},
         new Flag { abbrev = "GA", difLevel = 2},
         new Flag { abbrev = "GB", difLevel = 1},
         new Flag { abbrev = "GD", difLevel = 3},
         new Flag { abbrev = "GE", difLevel = 1},
         new Flag { abbrev = "GF", difLevel = 2},
         new Flag { abbrev = "GG", difLevel = 3},
         new Flag { abbrev = "GH", difLevel = 3},
         new Flag { abbrev = "GI", difLevel = 2},
         new Flag { abbrev = "GL", difLevel = 2},
         new Flag { abbrev = "GM", difLevel = 3},
         new Flag { abbrev = "GN", difLevel = 3},
         //new Flag { abbrev = "GP", difLevel = 2},
         new Flag { abbrev = "GQ", difLevel = 2},
         new Flag { abbrev = "GR", difLevel = 1},
         new Flag { abbrev = "GS", difLevel = 2},
         new Flag { abbrev = "GT", difLevel = 1},
         new Flag { abbrev = "GU", difLevel = 3},
         new Flag { abbrev = "GW", difLevel = 3},
         new Flag { abbrev = "GY", difLevel = 3},
         new Flag { abbrev = "HK", difLevel = 1},
         new Flag { abbrev = "HM", difLevel = 3},
         new Flag { abbrev = "HN", difLevel = 3},
         new Flag { abbrev = "HR", difLevel = 1},
         new Flag { abbrev = "HT", difLevel = 2},
         new Flag { abbrev = "HU", difLevel = 1},
         new Flag { abbrev = "ID", difLevel = 1},
         new Flag { abbrev = "IE", difLevel = 1},
         new Flag { abbrev = "IL", difLevel = 1},
         new Flag { abbrev = "IM", difLevel = 2},
         new Flag { abbrev = "IN", difLevel = 1},
         new Flag { abbrev = "IO", difLevel = 3},
         new Flag { abbrev = "IQ", difLevel = 2},
         new Flag { abbrev = "IR", difLevel = 2},
         new Flag { abbrev = "IS", difLevel = 1},
         new Flag { abbrev = "IT", difLevel = 1},
         new Flag { abbrev = "JE", difLevel = 2},
         new Flag { abbrev = "JM", difLevel = 2},
         new Flag { abbrev = "JO", difLevel = 2},
         new Flag { abbrev = "JP", difLevel = 1},
         new Flag { abbrev = "KE", difLevel = 2},
         new Flag { abbrev = "KG", difLevel = 3},
         new Flag { abbrev = "KH", difLevel = 3},
         new Flag { abbrev = "KI", difLevel = 3},
         new Flag { abbrev = "KM", difLevel = 3},
         new Flag { abbrev = "KN", difLevel = 3},
         new Flag { abbrev = "KP", difLevel = 1},
         new Flag { abbrev = "KR", difLevel = 1},
         new Flag { abbrev = "KW", difLevel = 3},
         new Flag { abbrev = "KY", difLevel = 3},
         new Flag { abbrev = "KZ", difLevel = 2},
         new Flag { abbrev = "LA", difLevel = 3},
         new Flag { abbrev = "LB", difLevel = 3},
         new Flag { abbrev = "LC", difLevel = 3},
         new Flag { abbrev = "LI", difLevel = 2},
         new Flag { abbrev = "LK", difLevel = 2},
         new Flag { abbrev = "LR", difLevel = 3},
         new Flag { abbrev = "LS", difLevel = 2},
         new Flag { abbrev = "LT", difLevel = 1},
         new Flag { abbrev = "LU", difLevel = 1},
         new Flag { abbrev = "LV", difLevel = 3},
         new Flag { abbrev = "LY", difLevel = 2},
         new Flag { abbrev = "MA", difLevel = 3},
         new Flag { abbrev = "MC", difLevel = 2},
         new Flag { abbrev = "MD", difLevel = 1},
         new Flag { abbrev = "ME", difLevel = 2},
         new Flag { abbrev = "MF", difLevel = 3},
         new Flag { abbrev = "MG", difLevel = 1},
         new Flag { abbrev = "MH", difLevel = 3},
         new Flag { abbrev = "MK", difLevel = 2},
         new Flag { abbrev = "ML", difLevel = 3},
         new Flag { abbrev = "MM", difLevel = 2},
         new Flag { abbrev = "MN", difLevel = 2},
         new Flag { abbrev = "MO", difLevel = 3},
         new Flag { abbrev = "MP", difLevel = 3},
         new Flag { abbrev = "MQ", difLevel = 3},
         new Flag { abbrev = "MR", difLevel = 3},
         new Flag { abbrev = "MS", difLevel = 3},
         new Flag { abbrev = "MT", difLevel = 2},
         new Flag { abbrev = "MU", difLevel = 2},
         new Flag { abbrev = "MV", difLevel = 2},
         new Flag { abbrev = "MW", difLevel = 3},
         new Flag { abbrev = "MX", difLevel = 2},
         new Flag { abbrev = "MY", difLevel = 1},
         new Flag { abbrev = "MZ", difLevel = 3},
         new Flag { abbrev = "NA", difLevel = 3},
         new Flag { abbrev = "NC", difLevel = 3},
         new Flag { abbrev = "NE", difLevel = 3},
         new Flag { abbrev = "NF", difLevel = 3},
         new Flag { abbrev = "NG", difLevel = 2},
         new Flag { abbrev = "NI", difLevel = 3},
         new Flag { abbrev = "NL", difLevel = 1},
         new Flag { abbrev = "NO", difLevel = 3},
         new Flag { abbrev = "NP", difLevel = 1},
         new Flag { abbrev = "NR", difLevel = 3},
         new Flag { abbrev = "NU", difLevel = 2},
         new Flag { abbrev = "NZ", difLevel = 1},
         new Flag { abbrev = "OM", difLevel = 2},
         new Flag { abbrev = "PA", difLevel = 2},
         new Flag { abbrev = "PE", difLevel = 1},
         new Flag { abbrev = "PF", difLevel = 3},
         new Flag { abbrev = "PG", difLevel = 1},
         new Flag { abbrev = "PH", difLevel = 1},
         new Flag { abbrev = "PK", difLevel = 1},
         new Flag { abbrev = "PL", difLevel = 1},
         //new Flag { abbrev = "PM", difLevel = 3},
         new Flag { abbrev = "PN", difLevel = 3},
         new Flag { abbrev = "PR", difLevel = 1},
         new Flag { abbrev = "PS", difLevel = 3},
         new Flag { abbrev = "PT", difLevel = 1},
         new Flag { abbrev = "PW", difLevel = 2},
         new Flag { abbrev = "PY", difLevel = 2},
         new Flag { abbrev = "QA", difLevel = 1},
         new Flag { abbrev = "RE", difLevel = 3},
         new Flag { abbrev = "RO", difLevel = 1},
         new Flag { abbrev = "RS", difLevel = 1},
         new Flag { abbrev = "RU", difLevel = 1},
         new Flag { abbrev = "RW", difLevel = 2},
         new Flag { abbrev = "SA", difLevel = 1},
         new Flag { abbrev = "SB", difLevel = 3},
         new Flag { abbrev = "SC", difLevel = 3},
         new Flag { abbrev = "SD", difLevel = 2},
         new Flag { abbrev = "SE", difLevel = 1},
         new Flag { abbrev = "SG", difLevel = 1},
         new Flag { abbrev = "SH", difLevel = 3},
         new Flag { abbrev = "SI", difLevel = 1},
         new Flag { abbrev = "SJ", difLevel = 3},
         new Flag { abbrev = "SK", difLevel = 1},
         new Flag { abbrev = "SL", difLevel = 3},
         new Flag { abbrev = "SM", difLevel = 3},
         new Flag { abbrev = "SN", difLevel = 2},
         new Flag { abbrev = "SO", difLevel = 2},
         new Flag { abbrev = "SR", difLevel = 3},
         new Flag { abbrev = "SS", difLevel = 2},
         new Flag { abbrev = "ST", difLevel = 3},
         new Flag { abbrev = "SV", difLevel = 1},
         new Flag { abbrev = "SY", difLevel = 2},
         new Flag { abbrev = "SZ", difLevel = 3},
         new Flag { abbrev = "TC", difLevel = 3},
         new Flag { abbrev = "TD", difLevel = 2},
         new Flag { abbrev = "TF", difLevel = 3},
         new Flag { abbrev = "TG", difLevel = 2},
         new Flag { abbrev = "TH", difLevel = 1},
         new Flag { abbrev = "TJ", difLevel = 3},
         new Flag { abbrev = "TK", difLevel = 3},
         new Flag { abbrev = "TL", difLevel = 3},
         new Flag { abbrev = "TM", difLevel = 3},
         new Flag { abbrev = "TN", difLevel = 2},
         new Flag { abbrev = "TO", difLevel = 3},
         new Flag { abbrev = "TR", difLevel = 1},
         new Flag { abbrev = "TT", difLevel = 2},
         new Flag { abbrev = "TV", difLevel = 3},
         new Flag { abbrev = "TW", difLevel = 1},
         new Flag { abbrev = "TZ", difLevel = 3},
         new Flag { abbrev = "UA", difLevel = 1},
         new Flag { abbrev = "UG", difLevel = 1},
         new Flag { abbrev = "US", difLevel = 1},
         new Flag { abbrev = "UY", difLevel = 2},
         new Flag { abbrev = "UZ", difLevel = 2},
         new Flag { abbrev = "VA", difLevel = 2},
         new Flag { abbrev = "VC", difLevel = 3},
         new Flag { abbrev = "VE", difLevel = 2},
         new Flag { abbrev = "VG", difLevel = 2},
         new Flag { abbrev = "VI", difLevel = 2},
         new Flag { abbrev = "VN", difLevel = 2},
         new Flag { abbrev = "VU", difLevel = 3},
         new Flag { abbrev = "WF", difLevel = 3},
         new Flag { abbrev = "WS", difLevel = 3},
         new Flag { abbrev = "YE", difLevel = 2},
         new Flag { abbrev = "YT", difLevel = 2},
         new Flag { abbrev = "ZA", difLevel = 1},
         new Flag { abbrev = "ZM", difLevel = 2},
         new Flag { abbrev = "ZW", difLevel = 2}
    };

    #region Translation for flags
    public static List<FlagTranslate> world_EN = new List<FlagTranslate>()
    {
         new FlagTranslate { ID = "AD", name = "Andorra" },
         new FlagTranslate { ID = "AE", name = "United Arab Emirates" },
         new FlagTranslate { ID = "AF", name = "Afghanistan" },
         new FlagTranslate { ID = "AG", name = "Antigua and Barbuda" },
         new FlagTranslate { ID = "AI", name = "Anguilla" },
         new FlagTranslate { ID = "AL", name = "Albania" },
         new FlagTranslate { ID = "AM", name = "Armenia" },
         new FlagTranslate { ID = "AN", name = "Netherlands Antilles" },
         new FlagTranslate { ID = "AO", name = "Angola" },
         new FlagTranslate { ID = "AQ", name = "Antarctica" },
         new FlagTranslate { ID = "AR", name = "Argentina" },
         new FlagTranslate { ID = "AS", name = "American Samoa" },
         new FlagTranslate { ID = "AT", name = "Austria" },
         new FlagTranslate { ID = "AU", name = "Australia" },
         new FlagTranslate { ID = "AW", name = "Aruba" },
         new FlagTranslate { ID = "AX", name = "Aland Islands" },
         new FlagTranslate { ID = "AZ", name = "Azerbaijan" },
         new FlagTranslate { ID = "BA", name = "Bosnia and Herzegovina" },
         new FlagTranslate { ID = "BB", name = "Barbados" },
         new FlagTranslate { ID = "BD", name = "Bangladesh" },
         new FlagTranslate { ID = "BE", name = "Belgium" },
         new FlagTranslate { ID = "BF", name = "Burkina Faso" },
         new FlagTranslate { ID = "BG", name = "Bulgaria" },
         new FlagTranslate { ID = "BH", name = "Bahrain" },
         new FlagTranslate { ID = "BI", name = "Burundi" },
         new FlagTranslate { ID = "BJ", name = "Benin" },
         new FlagTranslate { ID = "BL", name = "Saint-Barthélemy" },
         new FlagTranslate { ID = "BM", name = "Bermuda" },
         new FlagTranslate { ID = "BN", name = "Brunei Darussalam" },
         new FlagTranslate { ID = "BO", name = "Bolivia" },
         new FlagTranslate { ID = "BR", name = "Brazil" },
         new FlagTranslate { ID = "BS", name = "Bahamas" },
         new FlagTranslate { ID = "BT", name = "Bhutan" },
         new FlagTranslate { ID = "BV", name = "Bouvet Island" },
         new FlagTranslate { ID = "BW", name = "Botswana" },
         new FlagTranslate { ID = "BY", name = "Belarus" },
         new FlagTranslate { ID = "BZ", name = "Belize" },
         new FlagTranslate { ID = "CA", name = "Canada" },
         new FlagTranslate { ID = "CC", name = "Cocos Islands" },
         new FlagTranslate { ID = "CD", name = "Congo-Kinshasa" },
         new FlagTranslate { ID = "CF", name = "Central African Republic" },
         new FlagTranslate { ID = "CG", name = "Congo-Brazzaville" },
         new FlagTranslate { ID = "CH", name = "Switzerland" },
         new FlagTranslate { ID = "CI", name = "Côte d'Ivoire" },
         new FlagTranslate { ID = "CK", name = "Cook Islands" },
         new FlagTranslate { ID = "CL", name = "Chile" },
         new FlagTranslate { ID = "CM", name = "Cameroon" },
         new FlagTranslate { ID = "CN", name = "China" },
         new FlagTranslate { ID = "CO", name = "Colombia" },
         new FlagTranslate { ID = "CR", name = "Costa Rica" },
         new FlagTranslate { ID = "CU", name = "Cuba" },
         new FlagTranslate { ID = "CV", name = "Cape Verde" },
         new FlagTranslate { ID = "CX", name = "Christmas Island" },
         new FlagTranslate { ID = "CY", name = "Cyprus" },
         new FlagTranslate { ID = "CZ", name = "Czech Republic" },
         new FlagTranslate { ID = "DE", name = "Germany" },
         new FlagTranslate { ID = "DJ", name = "Djibouti" },
         new FlagTranslate { ID = "DK", name = "Denmark" },
         new FlagTranslate { ID = "DM", name = "Dominica" },
         new FlagTranslate { ID = "DO", name = "Dominican Republic" },
         new FlagTranslate { ID = "DZ", name = "Algeria" },
         new FlagTranslate { ID = "EC", name = "Ecuador" },
         new FlagTranslate { ID = "EE", name = "Estonia" },
         new FlagTranslate { ID = "EG", name = "Egypt" },
         new FlagTranslate { ID = "EH", name = "Western Sahara" },
         new FlagTranslate { ID = "ER", name = "Eritrea" },
         new FlagTranslate { ID = "ES", name = "Spain" },
         new FlagTranslate { ID = "ET", name = "Ethiopia" },
         new FlagTranslate { ID = "FI", name = "Finland" },
         new FlagTranslate { ID = "FJ", name = "Fiji" },
         new FlagTranslate { ID = "FK", name = "Falkland Islands (Malvinas)" },
         new FlagTranslate { ID = "FM", name = "Federated States of Micronesia" },
         new FlagTranslate { ID = "FO", name = "Faroe Islands" },
         new FlagTranslate { ID = "FR", name = "France" },
         new FlagTranslate { ID = "GA", name = "Gabon" },
         new FlagTranslate { ID = "GB", name = "United Kingdom" },
         new FlagTranslate { ID = "GD", name = "Grenada" },
         new FlagTranslate { ID = "GE", name = "Georgia" },
         new FlagTranslate { ID = "GF", name = "French Guiana" },
         new FlagTranslate { ID = "GG", name = "Guernsey" },
         new FlagTranslate { ID = "GH", name = "Ghana" },
         new FlagTranslate { ID = "GI", name = "Gibraltar" },
         new FlagTranslate { ID = "GL", name = "Greenland" },
         new FlagTranslate { ID = "GM", name = "Gambia" },
         new FlagTranslate { ID = "GN", name = "Guinea" },
         new FlagTranslate { ID = "GP", name = "Guadeloupe" },
         new FlagTranslate { ID = "GQ", name = "Equatorial Guinea" },
         new FlagTranslate { ID = "GR", name = "Greece" },
         new FlagTranslate { ID = "GS", name = "South Georgia" },
         new FlagTranslate { ID = "GT", name = "Guatemala" },
         new FlagTranslate { ID = "GU", name = "Guam" },
         new FlagTranslate { ID = "GW", name = "Guinea-Bissau" },
         new FlagTranslate { ID = "GY", name = "Guyana" },
         new FlagTranslate { ID = "HK", name = "Hong Kong" },
         new FlagTranslate { ID = "HM", name = "Heard and McDonald Islands" },
         new FlagTranslate { ID = "HN", name = "Honduras" },
         new FlagTranslate { ID = "HR", name = "Croatia" },
         new FlagTranslate { ID = "HT", name = "Haiti" },
         new FlagTranslate { ID = "HU", name = "Hungary" },
         new FlagTranslate { ID = "ID", name = "Indonesia" },
         new FlagTranslate { ID = "IE", name = "Ireland" },
         new FlagTranslate { ID = "IL", name = "Israel" },
         new FlagTranslate { ID = "IM", name = "Isle of Man" },
         new FlagTranslate { ID = "IN", name = "India" },
         new FlagTranslate { ID = "IO", name = "British Indian Ocean Territory" },
         new FlagTranslate { ID = "IQ", name = "Iraq" },
         new FlagTranslate { ID = "IR", name = "Islamic Republic of Iran" },
         new FlagTranslate { ID = "IS", name = "Iceland" },
         new FlagTranslate { ID = "IT", name = "Italy" },
         new FlagTranslate { ID = "JE", name = "Jersey" },
         new FlagTranslate { ID = "JM", name = "Jamaica" },
         new FlagTranslate { ID = "JO", name = "Jordan" },
         new FlagTranslate { ID = "JP", name = "Japan" },
         new FlagTranslate { ID = "KE", name = "Kenya" },
         new FlagTranslate { ID = "KG", name = "Kyrgyzstan" },
         new FlagTranslate { ID = "KH", name = "Cambodia" },
         new FlagTranslate { ID = "KI", name = "Kiribati" },
         new FlagTranslate { ID = "KM", name = "Comoros" },
         new FlagTranslate { ID = "KN", name = "Saint Kitts and Nevis" },
         new FlagTranslate { ID = "KP", name = "North Korea" },
         new FlagTranslate { ID = "KR", name = "South Korea" },
         new FlagTranslate { ID = "KW", name = "Kuwait" },
         new FlagTranslate { ID = "KY", name = "Cayman Islands" },
         new FlagTranslate { ID = "KZ", name = "Kazakhstan" },
         new FlagTranslate { ID = "LA", name = "Lao PDR" },
         new FlagTranslate { ID = "LB", name = "Lebanon" },
         new FlagTranslate { ID = "LC", name = "Saint Lucia" },
         new FlagTranslate { ID = "LI", name = "Liechtenstein" },
         new FlagTranslate { ID = "LK", name = "Sri Lanka" },
         new FlagTranslate { ID = "LR", name = "Liberia" },
         new FlagTranslate { ID = "LS", name = "Lesotho" },
         new FlagTranslate { ID = "LT", name = "Lithuania" },
         new FlagTranslate { ID = "LU", name = "Luxembourg" },
         new FlagTranslate { ID = "LV", name = "Latvia" },
         new FlagTranslate { ID = "LY", name = "Libya" },
         new FlagTranslate { ID = "MA", name = "Morocco" },
         new FlagTranslate { ID = "MC", name = "Monaco" },
         new FlagTranslate { ID = "MD", name = "Moldova" },
         new FlagTranslate { ID = "ME", name = "Montenegro" },
         new FlagTranslate { ID = "MF", name = "Saint-Martin (French part)" },
         new FlagTranslate { ID = "MG", name = "Madagascar" },
         new FlagTranslate { ID = "MH", name = "Marshall Islands" },
         new FlagTranslate { ID = "MK", name = "Republic of North Macedonia" },
         new FlagTranslate { ID = "ML", name = "Mali" },
         new FlagTranslate { ID = "MM", name = "Myanmar" },
         new FlagTranslate { ID = "MN", name = "Mongolia" },
         new FlagTranslate { ID = "MO", name = "Macao" },
         new FlagTranslate { ID = "MP", name = "Northern Mariana Islands" },
         new FlagTranslate { ID = "MQ", name = "Martinique" },
         new FlagTranslate { ID = "MR", name = "Mauritania" },
         new FlagTranslate { ID = "MS", name = "Montserrat" },
         new FlagTranslate { ID = "MT", name = "Malta" },
         new FlagTranslate { ID = "MU", name = "Mauritius" },
         new FlagTranslate { ID = "MV", name = "Maldives" },
         new FlagTranslate { ID = "MW", name = "Malawi" },
         new FlagTranslate { ID = "MX", name = "Mexico" },
         new FlagTranslate { ID = "MY", name = "Malaysia" },
         new FlagTranslate { ID = "MZ", name = "Mozambique" },
         new FlagTranslate { ID = "NA", name = "Namibia" },
         new FlagTranslate { ID = "NC", name = "New Caledonia" },
         new FlagTranslate { ID = "NE", name = "Niger" },
         new FlagTranslate { ID = "NF", name = "Norfolk Island" },
         new FlagTranslate { ID = "NG", name = "Nigeria" },
         new FlagTranslate { ID = "NI", name = "Nicaragua" },
         new FlagTranslate { ID = "NL", name = "Netherlands" },
         new FlagTranslate { ID = "NO", name = "Norway" },
         new FlagTranslate { ID = "NP", name = "Nepal" },
         new FlagTranslate { ID = "NR", name = "Nauru" },
         new FlagTranslate { ID = "NU", name = "Niue" },
         new FlagTranslate { ID = "NZ", name = "New Zealand" },
         new FlagTranslate { ID = "OM", name = "Oman" },
         new FlagTranslate { ID = "PA", name = "Panama" },
         new FlagTranslate { ID = "PE", name = "Peru" },
         new FlagTranslate { ID = "PF", name = "French Polynesia" },
         new FlagTranslate { ID = "PG", name = "Papua New Guinea" },
         new FlagTranslate { ID = "PH", name = "Philippines" },
         new FlagTranslate { ID = "PK", name = "Pakistan" },
         new FlagTranslate { ID = "PL", name = "Poland" },
         new FlagTranslate { ID = "PM", name = "Saint Pierre and Miquelon" },
         new FlagTranslate { ID = "PN", name = "Pitcairn" },
         new FlagTranslate { ID = "PR", name = "Puerto Rico" },
         new FlagTranslate { ID = "PS", name = "Palestinian Territory" },
         new FlagTranslate { ID = "PT", name = "Portugal" },
         new FlagTranslate { ID = "PW", name = "Palau" },
         new FlagTranslate { ID = "PY", name = "Paraguay" },
         new FlagTranslate { ID = "QA", name = "Qatar" },
         new FlagTranslate { ID = "RE", name = "Réunion" },
         new FlagTranslate { ID = "RO", name = "Romania" },
         new FlagTranslate { ID = "RS", name = "Serbia" },
         new FlagTranslate { ID = "RU", name = "Russian Federation" },
         new FlagTranslate { ID = "RW", name = "Rwanda" },
         new FlagTranslate { ID = "SA", name = "Saudi Arabia" },
         new FlagTranslate { ID = "SB", name = "Solomon Islands" },
         new FlagTranslate { ID = "SC", name = "Seychelles" },
         new FlagTranslate { ID = "SD", name = "Sudan" },
         new FlagTranslate { ID = "SE", name = "Sweden" },
         new FlagTranslate { ID = "SG", name = "Singapore" },
         new FlagTranslate { ID = "SH", name = "Saint Helena" },
         new FlagTranslate { ID = "SI", name = "Slovenia" },
         new FlagTranslate { ID = "SJ", name = "Svalbard and Jan Mayen Islands" },
         new FlagTranslate { ID = "SK", name = "Slovakia" },
         new FlagTranslate { ID = "SL", name = "Sierra Leone" },
         new FlagTranslate { ID = "SM", name = "San Marino" },
         new FlagTranslate { ID = "SN", name = "Senegal" },
         new FlagTranslate { ID = "SO", name = "Somalia" },
         new FlagTranslate { ID = "SR", name = "Suriname" },
         new FlagTranslate { ID = "SS", name = "South Sudan" },
         new FlagTranslate { ID = "ST", name = "Sao Tome and Principe" },
         new FlagTranslate { ID = "SV", name = "El Salvador" },
         new FlagTranslate { ID = "SY", name = "Syrian Arab Republic (Syria)" },
         new FlagTranslate { ID = "SZ", name = "Swaziland" },
         new FlagTranslate { ID = "TC", name = "Turks and Caicos Islands" },
         new FlagTranslate { ID = "TD", name = "Chad" },
         new FlagTranslate { ID = "TF", name = "French Southern Territories" },
         new FlagTranslate { ID = "TG", name = "Togo" },
         new FlagTranslate { ID = "TH", name = "Thailand" },
         new FlagTranslate { ID = "TJ", name = "Tajikistan" },
         new FlagTranslate { ID = "TK", name = "Tokelau" },
         new FlagTranslate { ID = "TL", name = "Timor-Leste" },
         new FlagTranslate { ID = "TM", name = "Turkmenistan" },
         new FlagTranslate { ID = "TN", name = "Tunisia" },
         new FlagTranslate { ID = "TO", name = "Tonga" },
         new FlagTranslate { ID = "TR", name = "Turkey" },
         new FlagTranslate { ID = "TT", name = "Trinidad and Tobago" },
         new FlagTranslate { ID = "TV", name = "Tuvalu" },
         new FlagTranslate { ID = "TW", name = "Taiwan" },
         new FlagTranslate { ID = "TZ", name = "United Republic of Tanzania" },
         new FlagTranslate { ID = "UA", name = "Ukraine" },
         new FlagTranslate { ID = "UG", name = "Uganda" },
         new FlagTranslate { ID = "US", name = "United States of America" },
         new FlagTranslate { ID = "UY", name = "Uruguay" },
         new FlagTranslate { ID = "UZ", name = "Uzbekistan" },
         new FlagTranslate { ID = "VA", name = "Vatican City State" },
         new FlagTranslate { ID = "VC", name = "Saint Vincent and Grenadines" },
         new FlagTranslate { ID = "VE", name = "Venezuela (Bolivarian Republic)" },
         new FlagTranslate { ID = "VG", name = "British Virgin Islands" },
         new FlagTranslate { ID = "VI", name = "Virgin Islands, US" },
         new FlagTranslate { ID = "VN", name = "Viet Nam" },
         new FlagTranslate { ID = "VU", name = "Vanuatu" },
         new FlagTranslate { ID = "WF", name = "Wallis and Futuna Islands" },
         new FlagTranslate { ID = "WS", name = "Samoa" },
         new FlagTranslate { ID = "YE", name = "Yemen" },
         new FlagTranslate { ID = "YT", name = "Mayotte" },
         new FlagTranslate { ID = "ZA", name = "South Africa" },
         new FlagTranslate { ID = "ZM", name = "Zambia" },
         new FlagTranslate { ID = "ZW", name = "Zimbabwe" }
    };

    public static List<FlagTranslate> world_RO = new List<FlagTranslate>()
    {
         new FlagTranslate { ID = "AD", name = "Andorra" },
         new FlagTranslate { ID = "AE", name = "Emiratele Arabe Unite" },
         new FlagTranslate { ID = "AF", name = "Afganistan" },
         new FlagTranslate { ID = "AG", name = "Antigua si Barbuda" },
         new FlagTranslate { ID = "AI", name = "Anguilla" },
         new FlagTranslate { ID = "AL", name = "Albania" },
         new FlagTranslate { ID = "AM", name = "Armenia" },
         new FlagTranslate { ID = "AN", name = "Antilele Olandeze" },
         new FlagTranslate { ID = "AO", name = "Angola" },
         new FlagTranslate { ID = "AQ", name = "Antarctica" },
         new FlagTranslate { ID = "AR", name = "Argentina" },
         new FlagTranslate { ID = "AS", name = "Samoa Americană" },
         new FlagTranslate { ID = "AT", name = "Austria" },
         new FlagTranslate { ID = "AU", name = "Australia" },
         new FlagTranslate { ID = "AW", name = "Aruba" },
         new FlagTranslate { ID = "AX", name = "Insulele Aland" },
         new FlagTranslate { ID = "AZ", name = "Azerbaidjan" },
         new FlagTranslate { ID = "BA", name = "Bosnia si Hertegovina" },
         new FlagTranslate { ID = "BB", name = "Barbados" },
         new FlagTranslate { ID = "BD", name = "Bangladesh" },
         new FlagTranslate { ID = "BE", name = "Belgia" },
         new FlagTranslate { ID = "BF", name = "Burkina Faso" },
         new FlagTranslate { ID = "BG", name = "Bulgaria" },
         new FlagTranslate { ID = "BH", name = "Bahrain" },
         new FlagTranslate { ID = "BI", name = "Burundi" },
         new FlagTranslate { ID = "BJ", name = "Benin" },
         new FlagTranslate { ID = "BL", name = "Saint-Barthélemy" },
         new FlagTranslate { ID = "BM", name = "Bermude" },
         new FlagTranslate { ID = "BN", name = "Brunei Darussalam" },
         new FlagTranslate { ID = "BO", name = "Bolivia" },
         new FlagTranslate { ID = "BR", name = "Brazilia" },
         new FlagTranslate { ID = "BS", name = "Bahamas" },
         new FlagTranslate { ID = "BT", name = "Bhutan" },
         new FlagTranslate { ID = "BV", name = "Insula Bouvet" },
         new FlagTranslate { ID = "BW", name = "Botswana" },
         new FlagTranslate { ID = "BY", name = "Bielorusia" },
         new FlagTranslate { ID = "BZ", name = "Belize" },
         new FlagTranslate { ID = "CA", name = "Canada" },
         new FlagTranslate { ID = "CC", name = "Insulele Cocos" },
         new FlagTranslate { ID = "CD", name = "Congo-Kinshasa" },
         new FlagTranslate { ID = "CF", name = "Republica Centrafricană" },
         new FlagTranslate { ID = "CG", name = "Congo-Brazzaville" },
         new FlagTranslate { ID = "CH", name = "Elveţia" },
         new FlagTranslate { ID = "CI", name = "Côte d'Ivoire" },
         new FlagTranslate { ID = "CK", name = "Insulele Cook" },
         new FlagTranslate { ID = "CL", name = "Chile" },
         new FlagTranslate { ID = "CM", name = "Camerun" },
         new FlagTranslate { ID = "CN", name = "China" },
         new FlagTranslate { ID = "CO", name = "Columbia" },
         new FlagTranslate { ID = "CR", name = "Costa Rica" },
         new FlagTranslate { ID = "CU", name = "Cuba" },
         new FlagTranslate { ID = "CV", name = "capul Verde" },
         new FlagTranslate { ID = "CX", name = "Insula Craciunului" },
         new FlagTranslate { ID = "CY", name = "Cipru" },
         new FlagTranslate { ID = "CZ", name = "Republica Cehă" },
         new FlagTranslate { ID = "DE", name = "Germania" },
         new FlagTranslate { ID = "DJ", name = "Djibouti" },
         new FlagTranslate { ID = "DK", name = "Danemarca" },
         new FlagTranslate { ID = "DM", name = "Dominica" },
         new FlagTranslate { ID = "DO", name = "Republica Dominicană" },
         new FlagTranslate { ID = "DZ", name = "Algeria" },
         new FlagTranslate { ID = "EC", name = "Ecuador" },
         new FlagTranslate { ID = "EE", name = "Estonia" },
         new FlagTranslate { ID = "EG", name = "Egipt" },
         new FlagTranslate { ID = "EH", name = "sahara de Vest" },
         new FlagTranslate { ID = "ER", name = "Eritreea" },
         new FlagTranslate { ID = "ES", name = "Spania" },
         new FlagTranslate { ID = "ET", name = "Etiopia" },
         new FlagTranslate { ID = "FI", name = "Finlanda" },
         new FlagTranslate { ID = "FJ", name = "Fiji" },
         new FlagTranslate { ID = "FK", name = "Insulele Falkland (Malvinas)" },
         new FlagTranslate { ID = "FM", name = "Statele Federate ale Microneziei" },
         new FlagTranslate { ID = "FO", name = "Insulele Feroe" },
         new FlagTranslate { ID = "FR", name = "Franţa" },
         new FlagTranslate { ID = "GA", name = "Gabon" },
         new FlagTranslate { ID = "GB", name = "Regatul Unit" },
         new FlagTranslate { ID = "GD", name = "Grenada" },
         new FlagTranslate { ID = "GE", name = "Georgia" },
         new FlagTranslate { ID = "GF", name = "Guyana Franceză" },
         new FlagTranslate { ID = "GG", name = "Guernsey" },
         new FlagTranslate { ID = "GH", name = "Ghana" },
         new FlagTranslate { ID = "GI", name = "Gibraltar" },
         new FlagTranslate { ID = "GL", name = "Groenlanda" },
         new FlagTranslate { ID = "GM", name = "Gambia" },
         new FlagTranslate { ID = "GN", name = "Guineea" },
         new FlagTranslate { ID = "GP", name = "Guadelupa" },
         new FlagTranslate { ID = "GQ", name = "Guineea Ecuatorială" },
         new FlagTranslate { ID = "GR", name = "Grecia" },
         new FlagTranslate { ID = "GS", name = "Georgia de Sud" },
         new FlagTranslate { ID = "GT", name = "Guatemala" },
         new FlagTranslate { ID = "GU", name = "Guam" },
         new FlagTranslate { ID = "GW", name = "Guineea-Bissau" },
         new FlagTranslate { ID = "GY", name = "Guyana" },
         new FlagTranslate { ID = "HK", name = "Hong Kong" },
         new FlagTranslate { ID = "HM", name = "Insulele Heard și McDonald" },
         new FlagTranslate { ID = "HN", name = "Honduras" },
         new FlagTranslate { ID = "HR", name = "Croaţia" },
         new FlagTranslate { ID = "HT", name = "Haiti" },
         new FlagTranslate { ID = "HU", name = "Ungaria" },
         new FlagTranslate { ID = "ID", name = "Indonezia" },
         new FlagTranslate { ID = "IE", name = "Irlanda" },
         new FlagTranslate { ID = "IL", name = "Israel" },
         new FlagTranslate { ID = "IM", name = "insula Barbatului" },
         new FlagTranslate { ID = "IN", name = "India" },
         new FlagTranslate { ID = "IO", name = "Teritoriul Britanic al Oceanului Indian" },
         new FlagTranslate { ID = "IQ", name = "Irak" },
         new FlagTranslate { ID = "IR", name = "Republica Islamică Iran" },
         new FlagTranslate { ID = "IS", name = "Islanda" },
         new FlagTranslate { ID = "IT", name = "Italia" },
         new FlagTranslate { ID = "JE", name = "Jersey" },
         new FlagTranslate { ID = "JM", name = "Jamaica" },
         new FlagTranslate { ID = "JO", name = "Iordania" },
         new FlagTranslate { ID = "JP", name = "Japonia" },
         new FlagTranslate { ID = "KE", name = "Kenya" },
         new FlagTranslate { ID = "KG", name = "Kârgâzstan" },
         new FlagTranslate { ID = "KH", name = "Cambodgia" },
         new FlagTranslate { ID = "KI", name = "Kiribati" },
         new FlagTranslate { ID = "KM", name = "Comore" },
         new FlagTranslate { ID = "KN", name = "Saint Kitts și Nevis" },
         new FlagTranslate { ID = "KP", name = "Coreea de Nord" },
         new FlagTranslate { ID = "KR", name = "Coreea de Sud" },
         new FlagTranslate { ID = "KW", name = "Kuweit" },
         new FlagTranslate { ID = "KY", name = "Insulele Cayman" },
         new FlagTranslate { ID = "KZ", name = "Kazahstan" },
         new FlagTranslate { ID = "LA", name = "RDP Lao" },
         new FlagTranslate { ID = "LB", name = "Liban" },
         new FlagTranslate { ID = "LC", name = "Sfânta Lucia" },
         new FlagTranslate { ID = "LI", name = "Liechtenstein" },
         new FlagTranslate { ID = "LK", name = "Sri Lanka" },
         new FlagTranslate { ID = "LR", name = "Liberia" },
         new FlagTranslate { ID = "LS", name = "Lesotho" },
         new FlagTranslate { ID = "LT", name = "Lituania" },
         new FlagTranslate { ID = "LU", name = "Luxemburg" },
         new FlagTranslate { ID = "LV", name = "Letonia" },
         new FlagTranslate { ID = "LY", name = "Libia" },
         new FlagTranslate { ID = "MA", name = "Maroc" },
         new FlagTranslate { ID = "MC", name = "Monaco" },
         new FlagTranslate { ID = "MD", name = "Moldova" },
         new FlagTranslate { ID = "ME", name = "Muntenegru" },
         new FlagTranslate { ID = "MF", name = "Saint-Martin (partea franceză)" },
         new FlagTranslate { ID = "MG", name = "Madagascar" },
         new FlagTranslate { ID = "MH", name = "Insulele Marshall" },
         new FlagTranslate { ID = "MK", name = "Republica Macedonia de Nord" },
         new FlagTranslate { ID = "ML", name = "Mali" },
         new FlagTranslate { ID = "MM", name = "Myanmar" },
         new FlagTranslate { ID = "MN", name = "Mongolia" },
         new FlagTranslate { ID = "MO", name = "Macao" },
         new FlagTranslate { ID = "MP", name = "Insulele Mariane de Nord" },
         new FlagTranslate { ID = "MQ", name = "Martinica" },
         new FlagTranslate { ID = "MR", name = "Mauritania" },
         new FlagTranslate { ID = "MS", name = "Montserrat" },
         new FlagTranslate { ID = "MT", name = "Malta" },
         new FlagTranslate { ID = "MU", name = "Mauritius" },
         new FlagTranslate { ID = "MV", name = "Maldive" },
         new FlagTranslate { ID = "MW", name = "Malawi" },
         new FlagTranslate { ID = "MX", name = "Mexic" },
         new FlagTranslate { ID = "MY", name = "Malaezia" },
         new FlagTranslate { ID = "MZ", name = "Mozambic" },
         new FlagTranslate { ID = "NA", name = "Namibia" },
         new FlagTranslate { ID = "NC", name = "Noua Caledonie" },
         new FlagTranslate { ID = "NE", name = "Niger" },
         new FlagTranslate { ID = "NF", name = "Insula Norfolk" },
         new FlagTranslate { ID = "NG", name = "Nigeria" },
         new FlagTranslate { ID = "NI", name = "Nicaragua" },
         new FlagTranslate { ID = "NL", name = "Olanda" },
         new FlagTranslate { ID = "NO", name = "Norvegia" },
         new FlagTranslate { ID = "NP", name = "Nepal" },
         new FlagTranslate { ID = "NR", name = "Nauru" },
         new FlagTranslate { ID = "NU", name = "Niue" },
         new FlagTranslate { ID = "NZ", name = "Noua Zeelandă" },
         new FlagTranslate { ID = "OM", name = "Oman" },
         new FlagTranslate { ID = "PA", name = "Panama" },
         new FlagTranslate { ID = "PE", name = "Peru" },
         new FlagTranslate { ID = "PF", name = "Polinezia Franceză" },
         new FlagTranslate { ID = "PG", name = "Papua Noua Guinee" },
         new FlagTranslate { ID = "PH", name = "Filipine" },
         new FlagTranslate { ID = "PK", name = "Pakistan" },
         new FlagTranslate { ID = "PL", name = "Polonia" },
         new FlagTranslate { ID = "PM", name = "Saint Pierre și Miquelon" },
         new FlagTranslate { ID = "PN", name = "Pitcairn" },
         new FlagTranslate { ID = "PR", name = "Puerto Rico" },
         new FlagTranslate { ID = "PS", name = "Teritoriul Palestinian" },
         new FlagTranslate { ID = "PT", name = "Portugalia" },
         new FlagTranslate { ID = "PW", name = "Palau" },
         new FlagTranslate { ID = "PY", name = "Paraguay" },
         new FlagTranslate { ID = "QA", name = "Qatar" },
         new FlagTranslate { ID = "RE", name = "Reuniune" },
         new FlagTranslate { ID = "RO", name = "România" },
         new FlagTranslate { ID = "RS", name = "Serbia" },
         new FlagTranslate { ID = "RU", name = "Federația Rusă" },
         new FlagTranslate { ID = "RW", name = "Rwanda" },
         new FlagTranslate { ID = "SA", name = "Arabia Saudită" },
         new FlagTranslate { ID = "SB", name = "Insulele Solomon" },
         new FlagTranslate { ID = "SC", name = "Seychelles" },
         new FlagTranslate { ID = "SD", name = "Sudan" },
         new FlagTranslate { ID = "SE", name = "Suedia" },
         new FlagTranslate { ID = "SG", name = "Singapore" },
         new FlagTranslate { ID = "SH", name = "Sfânta Elena" },
         new FlagTranslate { ID = "SI", name = "Slovenia" },
         new FlagTranslate { ID = "SJ", name = "Insulele Svalbard și Jan Mayen" },
         new FlagTranslate { ID = "SK", name = "Slovacia" },
         new FlagTranslate { ID = "SL", name = "Sierra Leone" },
         new FlagTranslate { ID = "SM", name = "San Marino" },
         new FlagTranslate { ID = "SN", name = "Senegal" },
         new FlagTranslate { ID = "SO", name = "Somalia" },
         new FlagTranslate { ID = "SR", name = "Surinam" },
         new FlagTranslate { ID = "SS", name = "Sudul Sudanului" },
         new FlagTranslate { ID = "ST", name = "Sao Tome și Principe" },
         new FlagTranslate { ID = "SV", name = "El Salvador" },
         new FlagTranslate { ID = "SY", name = "Republica Arabă Siriană (Siria)" },
         new FlagTranslate { ID = "SZ", name = "Swaziland" },
         new FlagTranslate { ID = "TC", name = "Insulele Turks și Caicos" },
         new FlagTranslate { ID = "TD", name = "Ciad" },
         new FlagTranslate { ID = "TF", name = "teritoriile din sudul Frantei" },
         new FlagTranslate { ID = "TG", name = "A merge" },
         new FlagTranslate { ID = "TH", name = "Tailanda" },
         new FlagTranslate { ID = "TJ", name = "Tadjikistan" },
         new FlagTranslate { ID = "TK", name = "Tokelau" },
         new FlagTranslate { ID = "TL", name = "Timorul de Est" },
         new FlagTranslate { ID = "TM", name = "Turkmenistan" },
         new FlagTranslate { ID = "TN", name = "Tunisia" },
         new FlagTranslate { ID = "TO", name = "Tonga" },
         new FlagTranslate { ID = "TR", name = "Curcan" },
         new FlagTranslate { ID = "TT", name = "Trinidad și Tobago" },
         new FlagTranslate { ID = "TV", name = "Tuvalu" },
         new FlagTranslate { ID = "TW", name = "Taiwan" },
         new FlagTranslate { ID = "TZ", name = "Republica Unită Tanzania" },
         new FlagTranslate { ID = "UA", name = "Ucraina" },
         new FlagTranslate { ID = "UG", name = "Uganda" },
         new FlagTranslate { ID = "US", name = "Statele Unite ale Americii" },
         new FlagTranslate { ID = "UY", name = "Uruguay" },
         new FlagTranslate { ID = "UZ", name = "Uzbekistan" },
         new FlagTranslate { ID = "VA", name = "Statul Vatican" },
         new FlagTranslate { ID = "VC", name = "Saint Vincent și Grenadine" },
         new FlagTranslate { ID = "VE", name = "Venezuela (Republica Bolivariană)" },
         new FlagTranslate { ID = "VG", name = "Insulele Virgine Britanice" },
         new FlagTranslate { ID = "VI", name = "Insulele Virgine, SUA" },
         new FlagTranslate { ID = "VN", name = "Vietnam" },
         new FlagTranslate { ID = "VU", name = "Vanuatu" },
         new FlagTranslate { ID = "WF", name = "Insulele Wallis și Futuna" },
         new FlagTranslate { ID = "WS", name = "Samoa" },
         new FlagTranslate { ID = "YE", name = "Yemen" },
         new FlagTranslate { ID = "YT", name = "Mayotte" },
         new FlagTranslate { ID = "ZA", name = "Africa de Sud" },
         new FlagTranslate { ID = "ZM", name = "Zambia" },
         new FlagTranslate { ID = "ZW", name = "Zimbabwe" }
    };

    public static List<FlagTranslate> world_FR = new List<FlagTranslate>()
    {
        new FlagTranslate { ID = "AD", name = "Andorre" },
        new FlagTranslate { ID = "AE", name = "Emirats Arabes Unis" },
        new FlagTranslate { ID = "AF", name = "Afghanistan" },
        new FlagTranslate { ID = "AG", name = "Antigua-et-Barbuda" },
        new FlagTranslate { ID = "AI", name = "Anguilla" },
        new FlagTranslate { ID = "AL", name = "Albanie" },
        new FlagTranslate { ID = "AM", name = "Arménie" },
        new FlagTranslate { ID = "AN", name = "Antilles néerlandaises" },
        new FlagTranslate { ID = "AO", name = "Angola" },
        new FlagTranslate { ID = "AQ", name = "Antarctique" },
        new FlagTranslate { ID = "AR", name = "Argentine" },
        new FlagTranslate { ID = "AS", name = "Samoa américaines" },
        new FlagTranslate { ID = "AT", name = "L'Autriche" },
        new FlagTranslate { ID = "AU", name = "Australie" },
        new FlagTranslate { ID = "AW", name = "Aruba" },
        new FlagTranslate { ID = "AX", name = "Iles Aland" },
        new FlagTranslate { ID = "AZ", name = "Azerbaïdjan" },
        new FlagTranslate { ID = "BA", name = "Bosnie Herzégovine" },
        new FlagTranslate { ID = "BB", name = "Barbade" },
        new FlagTranslate { ID = "BD", name = "Bengladesh" },
        new FlagTranslate { ID = "BE", name = "Belgique" },
        new FlagTranslate { ID = "BF", name = "Burkina Faso" },
        new FlagTranslate { ID = "BG", name = "Bulgarie" },
        new FlagTranslate { ID = "BH", name = "Bahreïn" },
        new FlagTranslate { ID = "BI", name = "Burundi" },
        new FlagTranslate { ID = "BJ", name = "Bénin" },
        new FlagTranslate { ID = "BL", name = "Saint-Barthélemy" },
        new FlagTranslate { ID = "BM", name = "Bermudes" },
        new FlagTranslate { ID = "BN", name = "Brunei Darussalam" },
        new FlagTranslate { ID = "BO", name = "Bolivie" },
        new FlagTranslate { ID = "BR", name = "Brésil" },
        new FlagTranslate { ID = "BS", name = "Bahamas" },
        new FlagTranslate { ID = "BT", name = "Bhoutan" },
        new FlagTranslate { ID = "BV", name = "Île Bouvet" },
        new FlagTranslate { ID = "BW", name = "Bostwana" },
        new FlagTranslate { ID = "BY", name = "Biélorussie" },
        new FlagTranslate { ID = "BZ", name = "Bélize" },
        new FlagTranslate { ID = "CA", name = "Canada" },
        new FlagTranslate { ID = "CC", name = "Îles Cocos" },
        new FlagTranslate { ID = "CD", name = "Congo-Kinshasa" },
        new FlagTranslate { ID = "CF", name = "République centrafricaine" },
        new FlagTranslate { ID = "CG", name = "Congo Brazzaville" },
        new FlagTranslate { ID = "CH", name = "Suisse" },
        new FlagTranslate { ID = "CI", name = "Côte d'Ivoire" },
        new FlagTranslate { ID = "CK", name = "les Îles Cook" },
        new FlagTranslate { ID = "CL", name = "Chili" },
        new FlagTranslate { ID = "CM", name = "Cameroun" },
        new FlagTranslate { ID = "CN", name = "Chine" },
        new FlagTranslate { ID = "CO", name = "Colombie" },
        new FlagTranslate { ID = "CR", name = "Costa Rica" },
        new FlagTranslate { ID = "CU", name = "Cuba" },
        new FlagTranslate { ID = "CV", name = "Cap-Vert" },
        new FlagTranslate { ID = "CX", name = "L'île de noël" },
        new FlagTranslate { ID = "CY", name = "Chypre" },
        new FlagTranslate { ID = "CZ", name = "République tchèque" },
        new FlagTranslate { ID = "DE", name = "Allemagne" },
        new FlagTranslate { ID = "DJ", name = "Djibouti" },
        new FlagTranslate { ID = "DK", name = "Danemark" },
        new FlagTranslate { ID = "DM", name = "Dominique" },
        new FlagTranslate { ID = "DO", name = "République dominicaine" },
        new FlagTranslate { ID = "DZ", name = "Algérie" },
        new FlagTranslate { ID = "EC", name = "Equateur" },
        new FlagTranslate { ID = "EE", name = "Estonie" },
        new FlagTranslate { ID = "EG", name = "Egypte" },
        new FlagTranslate { ID = "EH", name = "Sahara occidental" },
        new FlagTranslate { ID = "ER", name = "Érythrée" },
        new FlagTranslate { ID = "ES", name = "Espagne" },
        new FlagTranslate { ID = "ET", name = "Ethiopie" },
        new FlagTranslate { ID = "FI", name = "Finlande" },
        new FlagTranslate { ID = "FJ", name = "Fidji" },
        new FlagTranslate { ID = "FK", name = "Îles Falkland (Malouines)" },
        new FlagTranslate { ID = "FM", name = "États fédérés de Micronésie" },
        new FlagTranslate { ID = "FO", name = "Îles Féroé" },
        new FlagTranslate { ID = "FR", name = "France" },
        new FlagTranslate { ID = "GA", name = "Gabon" },
        new FlagTranslate { ID = "GB", name = "Royaume-Uni" },
        new FlagTranslate { ID = "GD", name = "Grenade" },
        new FlagTranslate { ID = "GE", name = "Géorgie" },
        new FlagTranslate { ID = "GF", name = "Guyane Française" },
        new FlagTranslate { ID = "GG", name = "Guernesey" },
        new FlagTranslate { ID = "GH", name = "Ghana" },
        new FlagTranslate { ID = "GI", name = "Gibraltar" },
        new FlagTranslate { ID = "GL", name = "Groenland" },
        new FlagTranslate { ID = "GM", name = "Gambie" },
        new FlagTranslate { ID = "GN", name = "Guinée" },
        new FlagTranslate { ID = "GP", name = "Guadeloupe" },
        new FlagTranslate { ID = "GQ", name = "Guinée Équatoriale" },
        new FlagTranslate { ID = "GR", name = "Grèce" },
        new FlagTranslate { ID = "GS", name = "Géorgie du Sud" },
        new FlagTranslate { ID = "GT", name = "Guatemala" },
        new FlagTranslate { ID = "GU", name = "Guam" },
        new FlagTranslate { ID = "GW", name = "Guinée-Bissau" },
        new FlagTranslate { ID = "GY", name = "Guyane" },
        new FlagTranslate { ID = "HK", name = "Hong Kong" },
        new FlagTranslate { ID = "HM", name = "Îles Heard et McDonald" },
        new FlagTranslate { ID = "HN", name = "Honduras" },
        new FlagTranslate { ID = "HR", name = "Croatie" },
        new FlagTranslate { ID = "HT", name = "Haïti" },
        new FlagTranslate { ID = "HU", name = "Hongrie" },
        new FlagTranslate { ID = "ID", name = "Indonésie" },
        new FlagTranslate { ID = "IE", name = "Irlande" },
        new FlagTranslate { ID = "IL", name = "Israël" },
        new FlagTranslate { ID = "IM", name = "île de Man" },
        new FlagTranslate { ID = "IN", name = "Inde" },
        new FlagTranslate { ID = "IO", name = "Territoire britannique de l'océan Indien" },
        new FlagTranslate { ID = "IQ", name = "Irak" },
        new FlagTranslate { ID = "IR", name = "République islamique d'Iran" },
        new FlagTranslate { ID = "IS", name = "Islande" },
        new FlagTranslate { ID = "IT", name = "Italie" },
        new FlagTranslate { ID = "JE", name = "Jersey" },
        new FlagTranslate { ID = "JM", name = "Jamaïque" },
        new FlagTranslate { ID = "JO", name = "Jordan" },
        new FlagTranslate { ID = "JP", name = "Japon" },
        new FlagTranslate { ID = "KE", name = "Kenya" },
        new FlagTranslate { ID = "KG", name = "Kirghizistan" },
        new FlagTranslate { ID = "KH", name = "Cambodge" },
        new FlagTranslate { ID = "KI", name = "Kiribati" },
        new FlagTranslate { ID = "KM", name = "Comores" },
        new FlagTranslate { ID = "KN", name = "Saint-Christophe-et-Niévès" },
        new FlagTranslate { ID = "KP", name = "Corée du Nord" },
        new FlagTranslate { ID = "KR", name = "Corée du Sud" },
        new FlagTranslate { ID = "KW", name = "Koweit" },
        new FlagTranslate { ID = "KY", name = "Îles Caïmans" },
        new FlagTranslate { ID = "KZ", name = "Kazakhstan" },
        new FlagTranslate { ID = "LA", name = "République démocratique populaire lao" },
        new FlagTranslate { ID = "LB", name = "Liban" },
        new FlagTranslate { ID = "LC", name = "Sainte-Lucie" },
        new FlagTranslate { ID = "LI", name = "Liechtenstein" },
        new FlagTranslate { ID = "LK", name = "Sri Lanka" },
        new FlagTranslate { ID = "LR", name = "Libéria" },
        new FlagTranslate { ID = "LS", name = "Lesotho" },
        new FlagTranslate { ID = "LT", name = "Lituanie" },
        new FlagTranslate { ID = "LU", name = "Luxembourg" },
        new FlagTranslate { ID = "LV", name = "Lettonie" },
        new FlagTranslate { ID = "LY", name = "Libye" },
        new FlagTranslate { ID = "MA", name = "Maroc" },
        new FlagTranslate { ID = "MC", name = "Monaco" },
        new FlagTranslate { ID = "MD", name = "Moldavie" },
        new FlagTranslate { ID = "ME", name = "Monténégro" },
        new FlagTranslate { ID = "MF", name = "Saint-Martin (partie française)" },
        new FlagTranslate { ID = "MG", name = "Madagascar" },
        new FlagTranslate { ID = "MH", name = "Iles Marshall" },
        new FlagTranslate { ID = "MK", name = "République de Macédoine du Nord" },
        new FlagTranslate { ID = "ML", name = "Mali" },
        new FlagTranslate { ID = "MM", name = "Birmanie" },
        new FlagTranslate { ID = "MN", name = "Mongolie" },
        new FlagTranslate { ID = "MO", name = "Macao" },
        new FlagTranslate { ID = "MP", name = "Îles Mariannes du Nord" },
        new FlagTranslate { ID = "MQ", name = "Martinique" },
        new FlagTranslate { ID = "MR", name = "Mauritanie" },
        new FlagTranslate { ID = "MS", name = "Montserrat" },
        new FlagTranslate { ID = "MT", name = "Malte" },
        new FlagTranslate { ID = "MU", name = "Maurice" },
        new FlagTranslate { ID = "MV", name = "Maldives" },
        new FlagTranslate { ID = "MW", name = "Malawi" },
        new FlagTranslate { ID = "MX", name = "Mexique" },
        new FlagTranslate { ID = "MY", name = "Malaisie" },
        new FlagTranslate { ID = "MZ", name = "Mozambique" },
        new FlagTranslate { ID = "NA", name = "Namibie" },
        new FlagTranslate { ID = "NC", name = "Nouvelle Calédonie" },
        new FlagTranslate { ID = "NE", name = "Niger" },
        new FlagTranslate { ID = "NF", name = "l'ile de Norfolk" },
        new FlagTranslate { ID = "NG", name = "Nigeria" },
        new FlagTranslate { ID = "NI", name = "Nicaragua" },
        new FlagTranslate { ID = "NL", name = "Pays-Bas" },
        new FlagTranslate { ID = "NO", name = "Norvège" },
        new FlagTranslate { ID = "NP", name = "Népal" },
        new FlagTranslate { ID = "NR", name = "Nauru" },
        new FlagTranslate { ID = "NU", name = "Niué" },
        new FlagTranslate { ID = "NZ", name = "Nouvelle-Zélande" },
        new FlagTranslate { ID = "OM", name = "Oman" },
        new FlagTranslate { ID = "PA", name = "Panama" },
        new FlagTranslate { ID = "PE", name = "Pérou" },
        new FlagTranslate { ID = "PF", name = "Polynésie française" },
        new FlagTranslate { ID = "PG", name = "Papouasie Nouvelle Guinée" },
        new FlagTranslate { ID = "PH", name = "Philippines" },
        new FlagTranslate { ID = "PK", name = "Pakistan" },
        new FlagTranslate { ID = "PL", name = "Pologne" },
        new FlagTranslate { ID = "PM", name = "Saint-Pierre-et-Miquelon" },
        new FlagTranslate { ID = "PN", name = "Pitcairn" },
        new FlagTranslate { ID = "PR", name = "Porto Rico" },
        new FlagTranslate { ID = "PS", name = "Territoire Palestinien" },
        new FlagTranslate { ID = "PT", name = "le Portugal" },
        new FlagTranslate { ID = "PW", name = "Palaos" },
        new FlagTranslate { ID = "PY", name = "Paraguay" },
        new FlagTranslate { ID = "QA", name = "Qatar" },
        new FlagTranslate { ID = "RE", name = "Réunion" },
        new FlagTranslate { ID = "RO", name = "Roumanie" },
        new FlagTranslate { ID = "RS", name = "Serbie" },
        new FlagTranslate { ID = "RU", name = "Fédération Russe" },
        new FlagTranslate { ID = "RW", name = "Rwanda" },
        new FlagTranslate { ID = "SA", name = "Arabie Saoudite" },
        new FlagTranslate { ID = "SB", name = "Les îles Salomon" },
        new FlagTranslate { ID = "SC", name = "les Seychelles" },
        new FlagTranslate { ID = "SD", name = "Soudan" },
        new FlagTranslate { ID = "SE", name = "Suède" },
        new FlagTranslate { ID = "SG", name = "Singapour" },
        new FlagTranslate { ID = "SH", name = "Sainte-Hélène" },
        new FlagTranslate { ID = "SI", name = "Slovénie" },
        new FlagTranslate { ID = "SJ", name = "Îles Svalbard et Jan Mayen" },
        new FlagTranslate { ID = "SK", name = "Slovaquie" },
        new FlagTranslate { ID = "SL", name = "Sierra Leone" },
        new FlagTranslate { ID = "SM", name = "Saint Marin" },
        new FlagTranslate { ID = "SN", name = "Sénégal" },
        new FlagTranslate { ID = "SO", name = "Somalie" },
        new FlagTranslate { ID = "SR", name = "Suriname" },
        new FlagTranslate { ID = "SS", name = "Soudan du sud" },
        new FlagTranslate { ID = "ST", name = "Sao Tomé et Principe" },
        new FlagTranslate { ID = "SV", name = "Le Salvador" },
        new FlagTranslate { ID = "SY", name = "République arabe syrienne (Syrie)" },
        new FlagTranslate { ID = "SZ", name = "Swaziland" },
        new FlagTranslate { ID = "TC", name = "îles Turques-et-Caïques" },
        new FlagTranslate { ID = "TD", name = "Tchad" },
        new FlagTranslate { ID = "TF", name = "Terres australes françaises" },
        new FlagTranslate { ID = "TG", name = "Aller" },
        new FlagTranslate { ID = "TH", name = "Thaïlande" },
        new FlagTranslate { ID = "TJ", name = "Tadjikistan" },
        new FlagTranslate { ID = "TK", name = "Tokélaou" },
        new FlagTranslate { ID = "TL", name = "Timor oriental" },
        new FlagTranslate { ID = "TM", name = "Turkménistan" },
        new FlagTranslate { ID = "TN", name = "Tunisie" },
        new FlagTranslate { ID = "TO", name = "Tonga" },
        new FlagTranslate { ID = "TR", name = "Turquie" },
        new FlagTranslate { ID = "TT", name = "Trinité-et-Tobago" },
        new FlagTranslate { ID = "TV", name = "Tuvalu" },
        new FlagTranslate { ID = "TW", name = "Taïwan" },
        new FlagTranslate { ID = "TZ", name = "République-Unie de Tanzanie" },
        new FlagTranslate { ID = "UA", name = "Ukraine" },
        new FlagTranslate { ID = "UG", name = "Ouganda" },
        new FlagTranslate { ID = "US", name = "les états-unis d'Amérique" },
        new FlagTranslate { ID = "UY", name = "Uruguay" },
        new FlagTranslate { ID = "UZ", name = "Ouzbékistan" },
        new FlagTranslate { ID = "VA", name = "État de la Cité du Vatican" },
        new FlagTranslate { ID = "VC", name = "Saint-Vincent-et-les Grenadines" },
        new FlagTranslate { ID = "VE", name = "Venezuela (République bolivarienne)" },
        new FlagTranslate { ID = "VG", name = "Îles Vierges britanniques" },
        new FlagTranslate { ID = "VI", name = "Îles Vierges, États-Unis" },
        new FlagTranslate { ID = "VN", name = "Vietnam" },
        new FlagTranslate { ID = "VU", name = "Vanuatu" },
        new FlagTranslate { ID = "WF", name = "Iles Wallis et Futuna" },
        new FlagTranslate { ID = "WS", name = "Samoa" },
        new FlagTranslate { ID = "YE", name = "Yémen" },
        new FlagTranslate { ID = "YT", name = "Mayotte" },
        new FlagTranslate { ID = "ZA", name = "Afrique du Sud" },
        new FlagTranslate { ID = "ZM", name = "Zambie" },
        new FlagTranslate { ID = "ZW", name = "Zimbabwe" }
    };

    public static List<FlagTranslate> world_ES = new List<FlagTranslate>()
    {
        new FlagTranslate { ID = "AD", name = "Andorra" },
        new FlagTranslate { ID = "AE", name = "Emiratos Árabes Unidos" },
        new FlagTranslate { ID = "AF", name = "Afganistán" },
        new FlagTranslate { ID = "AG", name = "Antigua y Barbuda" },
        new FlagTranslate { ID = "AI", name = "anguila" },
        new FlagTranslate { ID = "AL", name = "Albania" },
        new FlagTranslate { ID = "AM", name = "Armenia" },
        new FlagTranslate { ID = "AN", name = "Antillas Holandesas" },
        new FlagTranslate { ID = "AO", name = "angola" },
        new FlagTranslate { ID = "AQ", name = "Antártida" },
        new FlagTranslate { ID = "AR", name = "Argentina" },
        new FlagTranslate { ID = "AS", name = "Samoa Americana" },
        new FlagTranslate { ID = "AT", name = "Austria" },
        new FlagTranslate { ID = "AU", name = "Australia" },
        new FlagTranslate { ID = "AW", name = "Aruba" },
        new FlagTranslate { ID = "AX", name = "Islas Aland" },
        new FlagTranslate { ID = "AZ", name = "Azerbaiyán" },
        new FlagTranslate { ID = "BA", name = "Bosnia y Herzegovina" },
        new FlagTranslate { ID = "BB", name = "barbados" },
        new FlagTranslate { ID = "BD", name = "bangladesh" },
        new FlagTranslate { ID = "BE", name = "Bélgica" },
        new FlagTranslate { ID = "BF", name = "Burkina Faso" },
        new FlagTranslate { ID = "BG", name = "Bulgaria" },
        new FlagTranslate { ID = "BH", name = "Baréin" },
        new FlagTranslate { ID = "BI", name = "Burundi" },
        new FlagTranslate { ID = "BJ", name = "Benín" },
        new FlagTranslate { ID = "BL", name = "San Bartolomé" },
        new FlagTranslate { ID = "BM", name = "islas Bermudas" },
        new FlagTranslate { ID = "BN", name = "Brunei Darussalam" },
        new FlagTranslate { ID = "BO", name = "Bolivia" },
        new FlagTranslate { ID = "BR", name = "Brasil" },
        new FlagTranslate { ID = "BS", name = "bahamas" },
        new FlagTranslate { ID = "BT", name = "Bután" },
        new FlagTranslate { ID = "BV", name = "Isla Bouvet" },
        new FlagTranslate { ID = "BW", name = "Botsuana" },
        new FlagTranslate { ID = "BY", name = "Bielorrusia" },
        new FlagTranslate { ID = "BZ", name = "Belice" },
        new FlagTranslate { ID = "CA", name = "Canadá" },
        new FlagTranslate { ID = "CC", name = "Islas Cocos" },
        new FlagTranslate { ID = "CD", name = "Congo-Kinshasa" },
        new FlagTranslate { ID = "CF", name = "República Centroafricana" },
        new FlagTranslate { ID = "CG", name = "Congo-Brazzaville" },
        new FlagTranslate { ID = "CH", name = "Suiza" },
        new FlagTranslate { ID = "CI", name = "costa de marfil" },
        new FlagTranslate { ID = "CK", name = "Islas Cook" },
        new FlagTranslate { ID = "CL", name = "Chile" },
        new FlagTranslate { ID = "CM", name = "Camerún" },
        new FlagTranslate { ID = "CN", name = "Porcelana" },
        new FlagTranslate { ID = "CO", name = "Colombia" },
        new FlagTranslate { ID = "CR", name = "Costa Rica" },
        new FlagTranslate { ID = "CU", name = "Cuba" },
        new FlagTranslate { ID = "CV", name = "Cabo Verde" },
        new FlagTranslate { ID = "CX", name = "Isla de Navidad" },
        new FlagTranslate { ID = "CY", name = "Chipre" },
        new FlagTranslate { ID = "CZ", name = "República Checa" },
        new FlagTranslate { ID = "DE", name = "Alemania" },
        new FlagTranslate { ID = "DJ", name = "Yibuti" },
        new FlagTranslate { ID = "DK", name = "Dinamarca" },
        new FlagTranslate { ID = "DM", name = "Dominica" },
        new FlagTranslate { ID = "DO", name = "República Dominicana" },
        new FlagTranslate { ID = "DZ", name = "Argelia" },
        new FlagTranslate { ID = "EC", name = "Ecuador" },
        new FlagTranslate { ID = "EE", name = "Estonia" },
        new FlagTranslate { ID = "EG", name = "Egipto" },
        new FlagTranslate { ID = "EH", name = "Sahara Occidental" },
        new FlagTranslate { ID = "ER", name = "Eritrea" },
        new FlagTranslate { ID = "ES", name = "España" },
        new FlagTranslate { ID = "ET", name = "Etiopía" },
        new FlagTranslate { ID = "FI", name = "Finlandia" },
        new FlagTranslate { ID = "FJ", name = "Fiyi" },
        new FlagTranslate { ID = "FK", name = "Islas Malvinas (Malvinas)" },
        new FlagTranslate { ID = "FM", name = "Estados Federados de Micronesia" },
        new FlagTranslate { ID = "FO", name = "Islas Faroe" },
        new FlagTranslate { ID = "FR", name = "Francia" },
        new FlagTranslate { ID = "GA", name = "Gabón" },
        new FlagTranslate { ID = "GB", name = "Reino Unido" },
        new FlagTranslate { ID = "GD", name = "Granada" },
        new FlagTranslate { ID = "GE", name = "Georgia" },
        new FlagTranslate { ID = "GF", name = "Guayana Francesa" },
        new FlagTranslate { ID = "GG", name = "Guernesey" },
        new FlagTranslate { ID = "GH", name = "Ghana" },
        new FlagTranslate { ID = "GI", name = "Gibraltar" },
        new FlagTranslate { ID = "GL", name = "Groenlandia" },
        new FlagTranslate { ID = "GM", name = "Gambia" },
        new FlagTranslate { ID = "GN", name = "Guinea" },
        new FlagTranslate { ID = "GP", name = "Guadalupe" },
        new FlagTranslate { ID = "GQ", name = "Guinea Ecuatorial" },
        new FlagTranslate { ID = "GR", name = "Grecia" },
        new FlagTranslate { ID = "GS", name = "georgia del sur" },
        new FlagTranslate { ID = "GT", name = "Guatemala" },
        new FlagTranslate { ID = "GU", name = "Guam" },
        new FlagTranslate { ID = "GW", name = "Guinea-Bisáu" },
        new FlagTranslate { ID = "GY", name = "Guayana" },
        new FlagTranslate { ID = "HK", name = "Hong Kong" },
        new FlagTranslate { ID = "HM", name = "Islas Heard y McDonald" },
        new FlagTranslate { ID = "HN", name = "Honduras" },
        new FlagTranslate { ID = "HR", name = "Croacia" },
        new FlagTranslate { ID = "HT", name = "Haití" },
        new FlagTranslate { ID = "HU", name = "Hungría" },
        new FlagTranslate { ID = "ID", name = "Indonesia" },
        new FlagTranslate { ID = "IE", name = "Irlanda" },
        new FlagTranslate { ID = "IL", name = "Israel" },
        new FlagTranslate { ID = "IM", name = "Isla del hombre" },
        new FlagTranslate { ID = "IN", name = "India" },
        new FlagTranslate { ID = "IO", name = "Territorio Británico del Océano Índico" },
        new FlagTranslate { ID = "IQ", name = "Irak" },
        new FlagTranslate { ID = "IR", name = "República Islámica de Irán" },
        new FlagTranslate { ID = "IS", name = "Islandia" },
        new FlagTranslate { ID = "IT", name = "Italia" },
        new FlagTranslate { ID = "JE", name = "Jersey" },
        new FlagTranslate { ID = "JM", name = "Jamaica" },
        new FlagTranslate { ID = "JO", name = "Jordán" },
        new FlagTranslate { ID = "JP", name = "Japón" },
        new FlagTranslate { ID = "KE", name = "Kenia" },
        new FlagTranslate { ID = "KG", name = "Kirguistán" },
        new FlagTranslate { ID = "KH", name = "Camboya" },
        new FlagTranslate { ID = "KI", name = "Kiribati" },
        new FlagTranslate { ID = "KM", name = "Comoras" },
        new FlagTranslate { ID = "KN", name = "San Cristóbal y Nieves" },
        new FlagTranslate { ID = "KP", name = "Corea del Norte" },
        new FlagTranslate { ID = "KR", name = "Corea del Sur" },
        new FlagTranslate { ID = "KW", name = "Kuwait" },
        new FlagTranslate { ID = "KY", name = "Islas Caimán" },
        new FlagTranslate { ID = "KZ", name = "Kazajstán" },
        new FlagTranslate { ID = "LA", name = "República Democrática Popular Lao" },
        new FlagTranslate { ID = "LB", name = "Líbano" },
        new FlagTranslate { ID = "LC", name = "Santa Lucía" },
        new FlagTranslate { ID = "LI", name = "Liechtenstein" },
        new FlagTranslate { ID = "LK", name = "Sri Lanka" },
        new FlagTranslate { ID = "LR", name = "Liberia" },
        new FlagTranslate { ID = "LS", name = "Lesoto" },
        new FlagTranslate { ID = "LT", name = "Lituania" },
        new FlagTranslate { ID = "LU", name = "luxemburgo" },
        new FlagTranslate { ID = "LV", name = "letonia" },
        new FlagTranslate { ID = "LY", name = "Libia" },
        new FlagTranslate { ID = "MA", name = "Marruecos" },
        new FlagTranslate { ID = "MC", name = "Mónaco" },
        new FlagTranslate { ID = "MD", name = "Moldavia" },
        new FlagTranslate { ID = "ME", name = "montenegro" },
        new FlagTranslate { ID = "MF", name = "San Martín (parte francesa)" },
        new FlagTranslate { ID = "MG", name = "Madagascar" },
        new FlagTranslate { ID = "MH", name = "Islas Marshall" },
        new FlagTranslate { ID = "MK", name = "República de Macedonia del Norte" },
        new FlagTranslate { ID = "ML", name = "Malí" },
        new FlagTranslate { ID = "MM", name = "Birmania" },
        new FlagTranslate { ID = "MN", name = "Mongolia" },
        new FlagTranslate { ID = "MO", name = "Macao" },
        new FlagTranslate { ID = "MP", name = "Islas Marianas del Norte" },
        new FlagTranslate { ID = "MQ", name = "Martinica" },
        new FlagTranslate { ID = "MR", name = "Mauritania" },
        new FlagTranslate { ID = "MS", name = "Montserrat" },
        new FlagTranslate { ID = "MT", name = "Malta" },
        new FlagTranslate { ID = "MU", name = "Mauricio" },
        new FlagTranslate { ID = "MV", name = "Maldivas" },
        new FlagTranslate { ID = "MW", name = "Malaui" },
        new FlagTranslate { ID = "MX", name = "México" },
        new FlagTranslate { ID = "MY", name = "Malasia" },
        new FlagTranslate { ID = "MZ", name = "Mozambique" },
        new FlagTranslate { ID = "NA", name = "Namibia" },
        new FlagTranslate { ID = "NC", name = "Nueva Caledonia" },
        new FlagTranslate { ID = "NE", name = "Níger" },
        new FlagTranslate { ID = "NF", name = "Isla Norfolk" },
        new FlagTranslate { ID = "NG", name = "Nigeria" },
        new FlagTranslate { ID = "NI", name = "Nicaragua" },
        new FlagTranslate { ID = "NL", name = "Países Bajos" },
        new FlagTranslate { ID = "NO", name = "Noruega" },
        new FlagTranslate { ID = "NP", name = "Nepal" },
        new FlagTranslate { ID = "NR", name = "Nauru" },
        new FlagTranslate { ID = "NU", name = "Niue" },
        new FlagTranslate { ID = "NZ", name = "Nueva Zelanda" },
        new FlagTranslate { ID = "OM", name = "Omán" },
        new FlagTranslate { ID = "PA", name = "Panamá" },
        new FlagTranslate { ID = "PE", name = "Perú" },
        new FlagTranslate { ID = "PF", name = "Polinesia francés" },
        new FlagTranslate { ID = "PG", name = "Papúa Nueva Guinea" },
        new FlagTranslate { ID = "PH", name = "Filipinas" },
        new FlagTranslate { ID = "PK", name = "Pakistán" },
        new FlagTranslate { ID = "PL", name = "Polonia" },
        new FlagTranslate { ID = "PM", name = "San Pedro y Miquelón" },
        new FlagTranslate { ID = "PN", name = "pitcairn" },
        new FlagTranslate { ID = "PR", name = "Puerto Rico" },
        new FlagTranslate { ID = "PS", name = "Territorio Palestino" },
        new FlagTranslate { ID = "PT", name = "Portugal" },
        new FlagTranslate { ID = "PW", name = "palaos" },
        new FlagTranslate { ID = "PY", name = "Paraguay" },
        new FlagTranslate { ID = "QA", name = "Katar" },
        new FlagTranslate { ID = "RE", name = "Reunión" },
        new FlagTranslate { ID = "RO", name = "Rumania" },
        new FlagTranslate { ID = "RS", name = "Serbia" },
        new FlagTranslate { ID = "RU", name = "Federación Rusa" },
        new FlagTranslate { ID = "RW", name = "Ruanda" },
        new FlagTranslate { ID = "SA", name = "Arabia Saudita" },
        new FlagTranslate { ID = "SB", name = "Islas Salomón" },
        new FlagTranslate { ID = "SC", name = "Seychelles" },
        new FlagTranslate { ID = "SD", name = "Sudán" },
        new FlagTranslate { ID = "SE", name = "Suecia" },
        new FlagTranslate { ID = "SG", name = "Singapur" },
        new FlagTranslate { ID = "SH", name = "Santa Elena" },
        new FlagTranslate { ID = "SI", name = "Eslovenia" },
        new FlagTranslate { ID = "SJ", name = "Islas Svalbard y Jan Mayen" },
        new FlagTranslate { ID = "SK", name = "Eslovaquia" },
        new FlagTranslate { ID = "SL", name = "Sierra Leona" },
        new FlagTranslate { ID = "SM", name = "San Marino" },
        new FlagTranslate { ID = "SN", name = "Senegal" },
        new FlagTranslate { ID = "SO", name = "Somalia" },
        new FlagTranslate { ID = "SR", name = "Surinam" },
        new FlagTranslate { ID = "SS", name = "Sudán del Sur" },
        new FlagTranslate { ID = "ST", name = "Santo Tomé y Príncipe" },
        new FlagTranslate { ID = "SV", name = "El Salvador" },
        new FlagTranslate { ID = "SY", name = "República Árabe Siria (Siria)" },
        new FlagTranslate { ID = "SZ", name = "Suazilandia" },
        new FlagTranslate { ID = "TC", name = "Islas Turcas y Caicos" },
        new FlagTranslate { ID = "TD", name = "Chad" },
        new FlagTranslate { ID = "TF", name = "Territorios Franceses del Sur" },
        new FlagTranslate { ID = "TG", name = "Ir" },
        new FlagTranslate { ID = "TH", name = "Tailandia" },
        new FlagTranslate { ID = "TJ", name = "Tayikistán" },
        new FlagTranslate { ID = "TK", name = "Tokelau" },
        new FlagTranslate { ID = "TL", name = "Timor Oriental" },
        new FlagTranslate { ID = "TM", name = "turkmenistán" },
        new FlagTranslate { ID = "TN", name = "Túnez" },
        new FlagTranslate { ID = "TO", name = "tonga" },
        new FlagTranslate { ID = "TR", name = "Pavo" },
        new FlagTranslate { ID = "TT", name = "Trinidad y Tobago" },
        new FlagTranslate { ID = "TV", name = "Tuvalu" },
        new FlagTranslate { ID = "TW", name = "Taiwán" },
        new FlagTranslate { ID = "TZ", name = "República Unida de Tanzanía" },
        new FlagTranslate { ID = "UA", name = "Ucrania" },
        new FlagTranslate { ID = "UG", name = "Uganda" },
        new FlagTranslate { ID = "US", name = "Estados Unidos de América" },
        new FlagTranslate { ID = "UY", name = "Uruguay" },
        new FlagTranslate { ID = "UZ", name = "Uzbekistán" },
        new FlagTranslate { ID = "VA", name = "Estado de la Ciudad del Vaticano" },
        new FlagTranslate { ID = "VC", name = "San Vicente y las Granadinas" },
        new FlagTranslate { ID = "VE", name = "Venezuela (República Bolivariana)" },
        new FlagTranslate { ID = "VG", name = "Islas Vírgenes Británicas" },
        new FlagTranslate { ID = "VI", name = "Islas Vírgenes, EE. UU." },
        new FlagTranslate { ID = "VN", name = "Vietnam" },
        new FlagTranslate { ID = "VU", name = "Vanuatu" },
        new FlagTranslate { ID = "WF", name = "Islas Wallis y Futuna" },
        new FlagTranslate { ID = "WS", name = "samoa" },
        new FlagTranslate { ID = "YE", name = "Yemen" },
        new FlagTranslate { ID = "YT", name = "Mayotte" },
        new FlagTranslate { ID = "ZA", name = "Sudáfrica" },
        new FlagTranslate { ID = "ZM", name = "Zambia" },
        new FlagTranslate { ID = "ZW", name = "Zimbabue" }
};
    #endregion
}

