using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using static Constants;

public class FlagsManager : MonoBehaviour
{
    public static FlagsManager Manager;

    public List<FlagColor> FlagColors = new List<FlagColor>();

    public static List<Sprite> AllSymbols = new List<Sprite>();

    public static string[] euCountriesIDs = { "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE", "EU", "IS", "LI", "NO", "CH", "AL", "ME", "MK", "RS", "TR", "AD", "BY", "BA", "MD", "MC", "RU", "SM", "UA", "GB", "VA" };
    public static string[] africaCountriesIDs = { "AI", "AL", "AN", "BA", "BE", "BT", "BF", "BR", "BU", "BH", "CR", "CI", "CV", "CA", "DH", "DC", "EG", "ER", "ET", "GB", "GA", "GH", "GC", "GU", "HO", "IC", "KY", "LE", "LI", "LB", "MD", "MW", "ML", "MN", "MU", "MA", "MB", "ME", "MR", "MZ", "NM", "NG", "NI", "PY", "CH", "RD", "RE", "RG", "RS", "SY", "RC", "RI", "RW", "SE", "SN", "SL", "SO", "SA", "SS", "SU", "SH", "SW", "TA", "TO", "TN", "UG", "UC", "YA", "ZA", "ZM", "ZI", "ZU" };
    public static string[] asiaCountriesIDs = { "AH", "AF", "AK", "AL", "AR", "AM", "AY", "AB", "AZ", "BY", "BI", "BA", "BE", "BH", "BO", "BN", "BR", "BU", "CM", "CH", "CU", "DK", "EL", "EV", "GE", "HA", "HE", "HI", "HT", "IN", "ID", "IR", "IQ", "IS", "IT", "JA", "JW", "JO", "KA", "KZ", "KT", "KR", "KU", "KY", "LA", "LE", "MA", "MS", "ME", "MY", "MO", "MG", "MM", "NA", "NG", "NE", "NS", "OM", "OS", "OT", "PK", "PE", "PH", "PO", "QA", "RK", "ML", "SA", "SB", "SC", "SE", "SI", "SR", "SU", "SY", "TW", "TJ", "TS", "TM", "TH", "TB", "TL", "TN", "TU", "TK", "TV", "UL", "UA", "UR", "UZ", "VT", "YK", "YE" };
    public static string[] oceaniaCountriesIDs = { "AU", "CI", "CO", "FJ", "GM", "HA", "KI", "MA", "MI", "ME", "MC", "NA", "NB", "NC", "GU", "NZ", "NI", "PN", "PO", "PA", "SA", "SI", "SO", "TO", "TU", "TV", "VA", "YO" };
    public static string[] northAmericaCountriesIDs = { "AC", "AU", "AL", "AM", "AN", "AT", "AR", "AB", "AZ", "BB", "BC", "BL", "BO", "CA", "CG", "CE", "CY", "CH", "CI", "CO", "CU", "BA", "CR", "CB", "DA", "DO", "DR", "ES", "EK" };
    public static string[] southAmericaCountriesIDs = { "AC", "AR", "BE", "BO", "RR", "BR", "CH", "CI", "CO", "CR", "EC", "ES", "FI", "FG", "GU", "GY", "HO", "IN", "JM", "MY", "NA", "NI", "PM", "PA", "PE", "SU", "TT", "UR" };

    #region Basic Events
    private void Awake()
    {
        Manager = this;

        DontDestroyOnLoad(gameObject);
    }

    private void Start()
    {
        foreach (var flag in Flags)
        {
            Sprite flagSprite = Resources.Load<Sprite>("Flags/World/" + flag.abbrev);

            Sprite symbolSprite = Resources.Load<Sprite>("Flags/World/" + flag.abbrev + "_symbol");
            Sprite noSymbolSprite = Resources.Load<Sprite>("Flags/World/" + flag.abbrev + "_noSymbol");

            flag.sprite = flagSprite;

            if (symbolSprite != null && noSymbolSprite != null)
            {
                flag.hasSymbol = true;
                flag.symbol = new FlagSymbol(symbolSprite, noSymbolSprite);
                AllSymbols.Add(flag.sprite);
            }

            flag.country.isEU = euCountriesIDs.Contains(flag.abbrev);
            flag.country.isAfrica = africaCountriesIDs.Contains(flag.abbrev);
            flag.country.isAsia = asiaCountriesIDs.Contains(flag.abbrev);
            flag.country.isOceania = oceaniaCountriesIDs.Contains(flag.abbrev);
            flag.country.isNorthAmerica = northAmericaCountriesIDs.Contains(flag.abbrev);
            flag.country.isSouthAmerica = southAmericaCountriesIDs.Contains(flag.abbrev);
        }

        foreach (var flagColor in FlagColors)
        {
            Flag associatedFlag = Flags.FirstOrDefault(e => e.abbrev == flagColor.ID);

            if (associatedFlag != null)
            {
                associatedFlag.hasColors = true;
                associatedFlag.colors = flagColor;
            }
        }
    }
    #endregion

    public void ChangeFlagsPack()
    {
        if (UITexts.selectedLanguage == UITexts.en)
        {
            foreach (var flag in Flags)
            {
                flag.name = world_EN.FirstOrDefault(e => e.ID == flag.abbrev).name;
            }
        }

        if (UITexts.selectedLanguage == UITexts.ro)
        {
            foreach (var flag in Flags)
            {
                string name = world_RO.First(e => e.ID == flag.abbrev).name;
                if (!string.IsNullOrEmpty(name))
                    flag.name = name;
            }
        }

        if (UITexts.selectedLanguage == UITexts.fr)
        {
            foreach (var flag in Flags)
            {
                flag.name = world_FR.FirstOrDefault(e => e.ID == flag.abbrev).name;
            }
        }

        if (UITexts.selectedLanguage == UITexts.es)
        {
            foreach (var flag in Flags)
            {
                flag.name = world_ES.FirstOrDefault(e => e.ID == flag.abbrev).name;
            }
        }
    }

    public static List<Flag> Flags = new List<Flag>()
    {
         new Flag { abbrev = "AD", name = "Andorra", difLevel = 2 },
         new Flag { abbrev = "AE", name = "United Arab Emirates" },
         new Flag { abbrev = "AF", name = "Afghanistan" },
         new Flag { abbrev = "AG", name = "Antigua and Barbuda" },
         new Flag { abbrev = "AI", name = "Anguilla" },
         new Flag { abbrev = "AL", name = "Albania" },
         new Flag { abbrev = "AM", name = "Armenia" },
         new Flag { abbrev = "AN", name = "Netherlands Antilles" },
         new Flag { abbrev = "AO", name = "Angola" },
         new Flag { abbrev = "AQ", name = "Antarctica" },
         new Flag { abbrev = "AR", name = "Argentina" },
         new Flag { abbrev = "AS", name = "American Samoa" },
         new Flag { abbrev = "AT", name = "Austria" },
         new Flag { abbrev = "AU", name = "Australia" },
         new Flag { abbrev = "AW", name = "Aruba" },
         new Flag { abbrev = "AX", name = "Aland Islands" },
         new Flag { abbrev = "AZ", name = "Azerbaijan" },
         new Flag { abbrev = "BA", name = "Bosnia and Herzegovina" },
         new Flag { abbrev = "BB", name = "Barbados" },
         new Flag { abbrev = "BD", name = "Bangladesh" },
         new Flag { abbrev = "BE", name = "Belgium" },
         new Flag { abbrev = "BF", name = "Burkina Faso" },
         new Flag { abbrev = "BG", name = "Bulgaria" },
         new Flag { abbrev = "BH", name = "Bahrain" },
         new Flag { abbrev = "BI", name = "Burundi" },
         new Flag { abbrev = "BJ", name = "Benin" },
         new Flag { abbrev = "BL", name = "Saint-Barthélemy" },
         new Flag { abbrev = "BM", name = "Bermuda" },
         new Flag { abbrev = "BN", name = "Brunei Darussalam" },
         new Flag { abbrev = "BO", name = "Bolivia" },
         new Flag { abbrev = "BR", name = "Brazil" },
         new Flag { abbrev = "BS", name = "Bahamas" },
         new Flag { abbrev = "BT", name = "Bhutan" },
         new Flag { abbrev = "BV", name = "Bouvet Island" },
         new Flag { abbrev = "BW", name = "Botswana" },
         new Flag { abbrev = "BY", name = "Belarus" },
         new Flag { abbrev = "BZ", name = "Belize" },
         new Flag { abbrev = "CA", name = "Canada" },
         new Flag { abbrev = "CC", name = "Cocos (Keeling) Islands" },
         new Flag { abbrev = "CD", name = "Congo, (Kinshasa)" },
         new Flag { abbrev = "CF", name = "Central African Republic" },
         new Flag { abbrev = "CG", name = "Congo (Brazzaville)" },
         new Flag { abbrev = "CH", name = "Switzerland" },
         new Flag { abbrev = "CI", name = "Côte d'Ivoire" },
         new Flag { abbrev = "CK", name = "Cook Islands" },
         new Flag { abbrev = "CL", name = "Chile" },
         new Flag { abbrev = "CM", name = "Cameroon" },
         new Flag { abbrev = "CN", name = "China" },
         new Flag { abbrev = "CO", name = "Colombia" },
         new Flag { abbrev = "CR", name = "Costa Rica" },
         new Flag { abbrev = "CU", name = "Cuba" },
         new Flag { abbrev = "CV", name = "Cape Verde" },
         new Flag { abbrev = "CX", name = "Christmas Island" },
         new Flag { abbrev = "CY", name = "Cyprus" },
         new Flag { abbrev = "CZ", name = "Czech Republic" },
         new Flag { abbrev = "DE", name = "Germany" },
         new Flag { abbrev = "DJ", name = "Djibouti" },
         new Flag { abbrev = "DK", name = "Denmark" },
         new Flag { abbrev = "DM", name = "Dominica" },
         new Flag { abbrev = "DO", name = "Dominican Republic" },
         new Flag { abbrev = "DZ", name = "Algeria" },
         new Flag { abbrev = "EC", name = "Ecuador" },
         new Flag { abbrev = "EE", name = "Estonia" },
         new Flag { abbrev = "EG", name = "Egypt" },
         new Flag { abbrev = "EH", name = "Western Sahara" },
         new Flag { abbrev = "ER", name = "Eritrea" },
         new Flag { abbrev = "ES", name = "Spain" },
         new Flag { abbrev = "ET", name = "Ethiopia" },
         new Flag { abbrev = "FI", name = "Finland" },
         new Flag { abbrev = "FJ", name = "Fiji" },
         new Flag { abbrev = "FK", name = "Falkland Islands (Malvinas)" },
         new Flag { abbrev = "FM", name = "Micronesia, Federated States of" },
         new Flag { abbrev = "FO", name = "Faroe Islands" },
         new Flag { abbrev = "FR", name = "France" },
         new Flag { abbrev = "GA", name = "Gabon" },
         new Flag { abbrev = "GB", name = "United Kingdom" },
         new Flag { abbrev = "GD", name = "Grenada" },
         new Flag { abbrev = "GE", name = "Georgia" },
         new Flag { abbrev = "GF", name = "French Guiana" },
         new Flag { abbrev = "GG", name = "Guernsey" },
         new Flag { abbrev = "GH", name = "Ghana" },
         new Flag { abbrev = "GI", name = "Gibraltar" },
         new Flag { abbrev = "GL", name = "Greenland" },
         new Flag { abbrev = "GM", name = "Gambia" },
         new Flag { abbrev = "GN", name = "Guinea" },
         new Flag { abbrev = "GP", name = "Guadeloupe" },
         new Flag { abbrev = "GQ", name = "Equatorial Guinea" },
         new Flag { abbrev = "GR", name = "Greece" },
         new Flag { abbrev = "GS", name = "South Georgia and the South Sandwich Islands" },
         new Flag { abbrev = "GT", name = "Guatemala" },
         new Flag { abbrev = "GU", name = "Guam" },
         new Flag { abbrev = "GW", name = "Guinea-Bissau" },
         new Flag { abbrev = "GY", name = "Guyana" },
         new Flag { abbrev = "HK", name = "Hong Kong, SAR China" },
         new Flag { abbrev = "HM", name = "Heard and Mcdonald Islands" },
         new Flag { abbrev = "HN", name = "Honduras" },
         new Flag { abbrev = "HR", name = "Croatia" },
         new Flag { abbrev = "HT", name = "Haiti" },
         new Flag { abbrev = "HU", name = "Hungary" },
         new Flag { abbrev = "ID", name = "Indonesia" },
         new Flag { abbrev = "IE", name = "Ireland" },
         new Flag { abbrev = "IL", name = "Israel" },
         new Flag { abbrev = "IM", name = "Isle of Man" },
         new Flag { abbrev = "IN", name = "India" },
         new Flag { abbrev = "IO", name = "British Indian Ocean Territory" },
         new Flag { abbrev = "IQ", name = "Iraq" },
         new Flag { abbrev = "IR", name = "Iran, Islamic Republic of" },
         new Flag { abbrev = "IS", name = "Iceland" },
         new Flag { abbrev = "IT", name = "Italy" },
         new Flag { abbrev = "JE", name = "Jersey" },
         new Flag { abbrev = "JM", name = "Jamaica" },
         new Flag { abbrev = "JO", name = "Jordan" },
         new Flag { abbrev = "JP", name = "Japan" },
         new Flag { abbrev = "KE", name = "Kenya" },
         new Flag { abbrev = "KG", name = "Kyrgyzstan" },
         new Flag { abbrev = "KH", name = "Cambodia" },
         new Flag { abbrev = "KI", name = "Kiribati" },
         new Flag { abbrev = "KM", name = "Comoros" },
         new Flag { abbrev = "KN", name = "Saint Kitts and Nevis" },
         new Flag { abbrev = "KP", name = "Korea (North)" },
         new Flag { abbrev = "KR", name = "Korea (South)" },
         new Flag { abbrev = "KW", name = "Kuwait" },
         new Flag { abbrev = "KY", name = "Cayman Islands" },
         new Flag { abbrev = "KZ", name = "Kazakhstan" },
         new Flag { abbrev = "LA", name = "Lao PDR" },
         new Flag { abbrev = "LB", name = "Lebanon" },
         new Flag { abbrev = "LC", name = "Saint Lucia" },
         new Flag { abbrev = "LI", name = "Liechtenstein" },
         new Flag { abbrev = "LK", name = "Sri Lanka" },
         new Flag { abbrev = "LR", name = "Liberia" },
         new Flag { abbrev = "LS", name = "Lesotho" },
         new Flag { abbrev = "LT", name = "Lithuania" },
         new Flag { abbrev = "LU", name = "Luxembourg" },
         new Flag { abbrev = "LV", name = "Latvia" },
         new Flag { abbrev = "LY", name = "Libya" },
         new Flag { abbrev = "MA", name = "Morocco" },
         new Flag { abbrev = "MC", name = "Monaco" },
         new Flag { abbrev = "MD", name = "Moldova" },
         new Flag { abbrev = "ME", name = "Montenegro" },
         new Flag { abbrev = "MF", name = "Saint-Martin (French part)" },
         new Flag { abbrev = "MG", name = "Madagascar" },
         new Flag { abbrev = "MH", name = "Marshall Islands" },
         new Flag { abbrev = "MK", name = "Republic of North Macedonia" },
         new Flag { abbrev = "ML", name = "Mali" },
         new Flag { abbrev = "MM", name = "Myanmar" },
         new Flag { abbrev = "MN", name = "Mongolia" },
         new Flag { abbrev = "MO", name = "Macao, SAR China" },
         new Flag { abbrev = "MP", name = "Northern Mariana Islands" },
         new Flag { abbrev = "MQ", name = "Martinique" },
         new Flag { abbrev = "MR", name = "Mauritania" },
         new Flag { abbrev = "MS", name = "Montserrat" },
         new Flag { abbrev = "MT", name = "Malta" },
         new Flag { abbrev = "MU", name = "Mauritius" },
         new Flag { abbrev = "MV", name = "Maldives" },
         new Flag { abbrev = "MW", name = "Malawi" },
         new Flag { abbrev = "MX", name = "Mexico" },
         new Flag { abbrev = "MY", name = "Malaysia" },
         new Flag { abbrev = "MZ", name = "Mozambique" },
         new Flag { abbrev = "NA", name = "Namibia" },
         new Flag { abbrev = "NC", name = "New Caledonia" },
         new Flag { abbrev = "NE", name = "Niger" },
         new Flag { abbrev = "NF", name = "Norfolk Island" },
         new Flag { abbrev = "NG", name = "Nigeria" },
         new Flag { abbrev = "NI", name = "Nicaragua" },
         new Flag { abbrev = "NL", name = "Netherlands" },
         new Flag { abbrev = "NO", name = "Norway" },
         new Flag { abbrev = "NP", name = "Nepal" },
         new Flag { abbrev = "NR", name = "Nauru" },
         new Flag { abbrev = "NU", name = "Niue" },
         new Flag { abbrev = "NZ", name = "New Zealand" },
         new Flag { abbrev = "OM", name = "Oman" },
         new Flag { abbrev = "PA", name = "Panama" },
         new Flag { abbrev = "PE", name = "Peru" },
         new Flag { abbrev = "PF", name = "French Polynesia" },
         new Flag { abbrev = "PG", name = "Papua New Guinea" },
         new Flag { abbrev = "PH", name = "Philippines" },
         new Flag { abbrev = "PK", name = "Pakistan" },
         new Flag { abbrev = "PL", name = "Poland" },
         new Flag { abbrev = "PM", name = "Saint Pierre and Miquelon" },
         new Flag { abbrev = "PN", name = "Pitcairn" },
         new Flag { abbrev = "PR", name = "Puerto Rico" },
         new Flag { abbrev = "PS", name = "Palestinian Territory" },
         new Flag { abbrev = "PT", name = "Portugal" },
         new Flag { abbrev = "PW", name = "Palau" },
         new Flag { abbrev = "PY", name = "Paraguay" },
         new Flag { abbrev = "QA", name = "Qatar" },
         new Flag { abbrev = "RE", name = "Réunion" },
         new Flag { abbrev = "RO", name = "Romania" },
         new Flag { abbrev = "RS", name = "Serbia" },
         new Flag { abbrev = "RU", name = "Russian Federation" },
         new Flag { abbrev = "RW", name = "Rwanda" },
         new Flag { abbrev = "SA", name = "Saudi Arabia" },
         new Flag { abbrev = "SB", name = "Solomon Islands" },
         new Flag { abbrev = "SC", name = "Seychelles" },
         new Flag { abbrev = "SD", name = "Sudan" },
         new Flag { abbrev = "SE", name = "Sweden" },
         new Flag { abbrev = "SG", name = "Singapore" },
         new Flag { abbrev = "SH", name = "Saint Helena" },
         new Flag { abbrev = "SI", name = "Slovenia" },
         new Flag { abbrev = "SJ", name = "Svalbard and Jan Mayen Islands" },
         new Flag { abbrev = "SK", name = "Slovakia" },
         new Flag { abbrev = "SL", name = "Sierra Leone" },
         new Flag { abbrev = "SM", name = "San Marino" },
         new Flag { abbrev = "SN", name = "Senegal" },
         new Flag { abbrev = "SO", name = "Somalia" },
         new Flag { abbrev = "SR", name = "Suriname" },
         new Flag { abbrev = "SS", name = "South Sudan" },
         new Flag { abbrev = "ST", name = "Sao Tome and Principe" },
         new Flag { abbrev = "SV", name = "El Salvador" },
         new Flag { abbrev = "SY", name = "Syrian Arab Republic (Syria)" },
         new Flag { abbrev = "SZ", name = "Swaziland" },
         new Flag { abbrev = "TC", name = "Turks and Caicos Islands" },
         new Flag { abbrev = "TD", name = "Chad" },
         new Flag { abbrev = "TF", name = "French Southern Territories" },
         new Flag { abbrev = "TG", name = "Togo" },
         new Flag { abbrev = "TH", name = "Thailand" },
         new Flag { abbrev = "TJ", name = "Tajikistan" },
         new Flag { abbrev = "TK", name = "Tokelau" },
         new Flag { abbrev = "TL", name = "Timor-Leste" },
         new Flag { abbrev = "TM", name = "Turkmenistan" },
         new Flag { abbrev = "TN", name = "Tunisia" },
         new Flag { abbrev = "TO", name = "Tonga" },
         new Flag { abbrev = "TR", name = "Turkey" },
         new Flag { abbrev = "TT", name = "Trinidad and Tobago" },
         new Flag { abbrev = "TV", name = "Tuvalu" },
         new Flag { abbrev = "TW", name = "Taiwan, Republic of China" },
         new Flag { abbrev = "TZ", name = "Tanzania, United Republic of" },
         new Flag { abbrev = "UA", name = "Ukraine" },
         new Flag { abbrev = "UG", name = "Uganda" },
         new Flag { abbrev = "UM", name = "US Minor Outlying Islands" },
         new Flag { abbrev = "US", name = "United States of America" },
         new Flag { abbrev = "UY", name = "Uruguay" },
         new Flag { abbrev = "UZ", name = "Uzbekistan" },
         new Flag { abbrev = "VA", name = "Holy See (Vatican City State)" },
         new Flag { abbrev = "VC", name = "Saint Vincent and Grenadines" },
         new Flag { abbrev = "VE", name = "Venezuela (Bolivarian Republic)" },
         new Flag { abbrev = "VG", name = "British Virgin Islands" },
         new Flag { abbrev = "VI", name = "Virgin Islands, US" },
         new Flag { abbrev = "VN", name = "Viet Nam" },
         new Flag { abbrev = "VU", name = "Vanuatu" },
         new Flag { abbrev = "WF", name = "Wallis and Futuna Islands" },
         new Flag { abbrev = "WS", name = "Samoa" },
         new Flag { abbrev = "YE", name = "Yemen" },
         new Flag { abbrev = "YT", name = "Mayotte" },
         new Flag { abbrev = "ZA", name = "South Africa" },
         new Flag { abbrev = "ZM", name = "Zambia" },
         new Flag { abbrev = "ZW", name = "Zimbabwe" }
    };

    public static List<FlagTranslate> world_EN = new List<FlagTranslate>()
    {
         new FlagTranslate { ID = "AD", name = "Andorra" },
         new FlagTranslate { ID = "AE", name = "United Arab Emirates" },
         new FlagTranslate { ID = "AF", name = "Afghanistan" },
         new FlagTranslate { ID = "AG", name = "Antigua and Barbuda" },
         new FlagTranslate { ID = "AI", name = "Anguilla" },
         new FlagTranslate { ID = "AL", name = "Albania" },
         new FlagTranslate { ID = "AM", name = "Armenia" },
         new FlagTranslate { ID = "AN", name = "Netherlands Antilles" },
         new FlagTranslate { ID = "AO", name = "Angola" },
         new FlagTranslate { ID = "AQ", name = "Antarctica" },
         new FlagTranslate { ID = "AR", name = "Argentina" },
         new FlagTranslate { ID = "AS", name = "American Samoa" },
         new FlagTranslate { ID = "AT", name = "Austria" },
         new FlagTranslate { ID = "AU", name = "Australia" },
         new FlagTranslate { ID = "AW", name = "Aruba" },
         new FlagTranslate { ID = "AX", name = "Aland Islands" },
         new FlagTranslate { ID = "AZ", name = "Azerbaijan" },
         new FlagTranslate { ID = "BA", name = "Bosnia and Herzegovina" },
         new FlagTranslate { ID = "BB", name = "Barbados" },
         new FlagTranslate { ID = "BD", name = "Bangladesh" },
         new FlagTranslate { ID = "BE", name = "Belgium" },
         new FlagTranslate { ID = "BF", name = "Burkina Faso" },
         new FlagTranslate { ID = "BG", name = "Bulgaria" },
         new FlagTranslate { ID = "BH", name = "Bahrain" },
         new FlagTranslate { ID = "BI", name = "Burundi" },
         new FlagTranslate { ID = "BJ", name = "Benin" },
         new FlagTranslate { ID = "BL", name = "Saint-Barthélemy" },
         new FlagTranslate { ID = "BM", name = "Bermuda" },
         new FlagTranslate { ID = "BN", name = "Brunei Darussalam" },
         new FlagTranslate { ID = "BO", name = "Bolivia" },
         new FlagTranslate { ID = "BR", name = "Brazil" },
         new FlagTranslate { ID = "BS", name = "Bahamas" },
         new FlagTranslate { ID = "BT", name = "Bhutan" },
         new FlagTranslate { ID = "BV", name = "Bouvet Island" },
         new FlagTranslate { ID = "BW", name = "Botswana" },
         new FlagTranslate { ID = "BY", name = "Belarus" },
         new FlagTranslate { ID = "BZ", name = "Belize" },
         new FlagTranslate { ID = "CA", name = "Canada" },
         new FlagTranslate { ID = "CC", name = "Cocos (Keeling) Islands" },
         new FlagTranslate { ID = "CD", name = "Congo, (Kinshasa)" },
         new FlagTranslate { ID = "CF", name = "Central African Republic" },
         new FlagTranslate { ID = "CG", name = "Congo (Brazzaville)" },
         new FlagTranslate { ID = "CH", name = "Switzerland" },
         new FlagTranslate { ID = "CI", name = "Côte d'Ivoire" },
         new FlagTranslate { ID = "CK", name = "Cook Islands" },
         new FlagTranslate { ID = "CL", name = "Chile" },
         new FlagTranslate { ID = "CM", name = "Cameroon" },
         new FlagTranslate { ID = "CN", name = "China" },
         new FlagTranslate { ID = "CO", name = "Colombia" },
         new FlagTranslate { ID = "CR", name = "Costa Rica" },
         new FlagTranslate { ID = "CU", name = "Cuba" },
         new FlagTranslate { ID = "CV", name = "Cape Verde" },
         new FlagTranslate { ID = "CX", name = "Christmas Island" },
         new FlagTranslate { ID = "CY", name = "Cyprus" },
         new FlagTranslate { ID = "CZ", name = "Czech Republic" },
         new FlagTranslate { ID = "DE", name = "Germany" },
         new FlagTranslate { ID = "DJ", name = "Djibouti" },
         new FlagTranslate { ID = "DK", name = "Denmark" },
         new FlagTranslate { ID = "DM", name = "Dominica" },
         new FlagTranslate { ID = "DO", name = "Dominican Republic" },
         new FlagTranslate { ID = "DZ", name = "Algeria" },
         new FlagTranslate { ID = "EC", name = "Ecuador" },
         new FlagTranslate { ID = "EE", name = "Estonia" },
         new FlagTranslate { ID = "EG", name = "Egypt" },
         new FlagTranslate { ID = "EH", name = "Western Sahara" },
         new FlagTranslate { ID = "ER", name = "Eritrea" },
         new FlagTranslate { ID = "ES", name = "Spain" },
         new FlagTranslate { ID = "ET", name = "Ethiopia" },
         new FlagTranslate { ID = "FI", name = "Finland" },
         new FlagTranslate { ID = "FJ", name = "Fiji" },
         new FlagTranslate { ID = "FK", name = "Falkland Islands (Malvinas)" },
         new FlagTranslate { ID = "FM", name = "Micronesia, Federated States of" },
         new FlagTranslate { ID = "FO", name = "Faroe Islands" },
         new FlagTranslate { ID = "FR", name = "France" },
         new FlagTranslate { ID = "GA", name = "Gabon" },
         new FlagTranslate { ID = "GB", name = "United Kingdom" },
         new FlagTranslate { ID = "GD", name = "Grenada" },
         new FlagTranslate { ID = "GE", name = "Georgia" },
         new FlagTranslate { ID = "GF", name = "French Guiana" },
         new FlagTranslate { ID = "GG", name = "Guernsey" },
         new FlagTranslate { ID = "GH", name = "Ghana" },
         new FlagTranslate { ID = "GI", name = "Gibraltar" },
         new FlagTranslate { ID = "GL", name = "Greenland" },
         new FlagTranslate { ID = "GM", name = "Gambia" },
         new FlagTranslate { ID = "GN", name = "Guinea" },
         new FlagTranslate { ID = "GP", name = "Guadeloupe" },
         new FlagTranslate { ID = "GQ", name = "Equatorial Guinea" },
         new FlagTranslate { ID = "GR", name = "Greece" },
         new FlagTranslate { ID = "GS", name = "South Georgia and the South Sandwich Islands" },
         new FlagTranslate { ID = "GT", name = "Guatemala" },
         new FlagTranslate { ID = "GU", name = "Guam" },
         new FlagTranslate { ID = "GW", name = "Guinea-Bissau" },
         new FlagTranslate { ID = "GY", name = "Guyana" },
         new FlagTranslate { ID = "HK", name = "Hong Kong, SAR China" },
         new FlagTranslate { ID = "HM", name = "Heard and Mcdonald Islands" },
         new FlagTranslate { ID = "HN", name = "Honduras" },
         new FlagTranslate { ID = "HR", name = "Croatia" },
         new FlagTranslate { ID = "HT", name = "Haiti" },
         new FlagTranslate { ID = "HU", name = "Hungary" },
         new FlagTranslate { ID = "ID", name = "Indonesia" },
         new FlagTranslate { ID = "IE", name = "Ireland" },
         new FlagTranslate { ID = "IL", name = "Israel" },
         new FlagTranslate { ID = "IM", name = "Isle of Man" },
         new FlagTranslate { ID = "IN", name = "India" },
         new FlagTranslate { ID = "IO", name = "British Indian Ocean Territory" },
         new FlagTranslate { ID = "IQ", name = "Iraq" },
         new FlagTranslate { ID = "IR", name = "Iran, Islamic Republic of" },
         new FlagTranslate { ID = "IS", name = "Iceland" },
         new FlagTranslate { ID = "IT", name = "Italy" },
         new FlagTranslate { ID = "JE", name = "Jersey" },
         new FlagTranslate { ID = "JM", name = "Jamaica" },
         new FlagTranslate { ID = "JO", name = "Jordan" },
         new FlagTranslate { ID = "JP", name = "Japan" },
         new FlagTranslate { ID = "KE", name = "Kenya" },
         new FlagTranslate { ID = "KG", name = "Kyrgyzstan" },
         new FlagTranslate { ID = "KH", name = "Cambodia" },
         new FlagTranslate { ID = "KI", name = "Kiribati" },
         new FlagTranslate { ID = "KM", name = "Comoros" },
         new FlagTranslate { ID = "KN", name = "Saint Kitts and Nevis" },
         new FlagTranslate { ID = "KP", name = "Korea (North)" },
         new FlagTranslate { ID = "KR", name = "Korea (South)" },
         new FlagTranslate { ID = "KW", name = "Kuwait" },
         new FlagTranslate { ID = "KY", name = "Cayman Islands" },
         new FlagTranslate { ID = "KZ", name = "Kazakhstan" },
         new FlagTranslate { ID = "LA", name = "Lao PDR" },
         new FlagTranslate { ID = "LB", name = "Lebanon" },
         new FlagTranslate { ID = "LC", name = "Saint Lucia" },
         new FlagTranslate { ID = "LI", name = "Liechtenstein" },
         new FlagTranslate { ID = "LK", name = "Sri Lanka" },
         new FlagTranslate { ID = "LR", name = "Liberia" },
         new FlagTranslate { ID = "LS", name = "Lesotho" },
         new FlagTranslate { ID = "LT", name = "Lithuania" },
         new FlagTranslate { ID = "LU", name = "Luxembourg" },
         new FlagTranslate { ID = "LV", name = "Latvia" },
         new FlagTranslate { ID = "LY", name = "Libya" },
         new FlagTranslate { ID = "MA", name = "Morocco" },
         new FlagTranslate { ID = "MC", name = "Monaco" },
         new FlagTranslate { ID = "MD", name = "Moldova" },
         new FlagTranslate { ID = "ME", name = "Montenegro" },
         new FlagTranslate { ID = "MF", name = "Saint-Martin (French part)" },
         new FlagTranslate { ID = "MG", name = "Madagascar" },
         new FlagTranslate { ID = "MH", name = "Marshall Islands" },
         new FlagTranslate { ID = "MK", name = "Macedonia, Republic of" },
         new FlagTranslate { ID = "ML", name = "Mali" },
         new FlagTranslate { ID = "MM", name = "Myanmar" },
         new FlagTranslate { ID = "MN", name = "Mongolia" },
         new FlagTranslate { ID = "MO", name = "Macao, SAR China" },
         new FlagTranslate { ID = "MP", name = "Northern Mariana Islands" },
         new FlagTranslate { ID = "MQ", name = "Martinique" },
         new FlagTranslate { ID = "MR", name = "Mauritania" },
         new FlagTranslate { ID = "MS", name = "Montserrat" },
         new FlagTranslate { ID = "MT", name = "Malta" },
         new FlagTranslate { ID = "MU", name = "Mauritius" },
         new FlagTranslate { ID = "MV", name = "Maldives" },
         new FlagTranslate { ID = "MW", name = "Malawi" },
         new FlagTranslate { ID = "MX", name = "Mexico" },
         new FlagTranslate { ID = "MY", name = "Malaysia" },
         new FlagTranslate { ID = "MZ", name = "Mozambique" },
         new FlagTranslate { ID = "NA", name = "Namibia" },
         new FlagTranslate { ID = "NC", name = "New Caledonia" },
         new FlagTranslate { ID = "NE", name = "Niger" },
         new FlagTranslate { ID = "NF", name = "Norfolk Island" },
         new FlagTranslate { ID = "NG", name = "Nigeria" },
         new FlagTranslate { ID = "NI", name = "Nicaragua" },
         new FlagTranslate { ID = "NL", name = "Netherlands" },
         new FlagTranslate { ID = "NO", name = "Norway" },
         new FlagTranslate { ID = "NP", name = "Nepal" },
         new FlagTranslate { ID = "NR", name = "Nauru" },
         new FlagTranslate { ID = "NU", name = "Niue" },
         new FlagTranslate { ID = "NZ", name = "New Zealand" },
         new FlagTranslate { ID = "OM", name = "Oman" },
         new FlagTranslate { ID = "PA", name = "Panama" },
         new FlagTranslate { ID = "PE", name = "Peru" },
         new FlagTranslate { ID = "PF", name = "French Polynesia" },
         new FlagTranslate { ID = "PG", name = "Papua New Guinea" },
         new FlagTranslate { ID = "PH", name = "Philippines" },
         new FlagTranslate { ID = "PK", name = "Pakistan" },
         new FlagTranslate { ID = "PL", name = "Poland" },
         new FlagTranslate { ID = "PM", name = "Saint Pierre and Miquelon" },
         new FlagTranslate { ID = "PN", name = "Pitcairn" },
         new FlagTranslate { ID = "PR", name = "Puerto Rico" },
         new FlagTranslate { ID = "PS", name = "Palestinian Territory" },
         new FlagTranslate { ID = "PT", name = "Portugal" },
         new FlagTranslate { ID = "PW", name = "Palau" },
         new FlagTranslate { ID = "PY", name = "Paraguay" },
         new FlagTranslate { ID = "QA", name = "Qatar" },
         new FlagTranslate { ID = "RE", name = "Réunion" },
         new FlagTranslate { ID = "RO", name = "Romania" },
         new FlagTranslate { ID = "RS", name = "Serbia" },
         new FlagTranslate { ID = "RU", name = "Russian Federation" },
         new FlagTranslate { ID = "RW", name = "Rwanda" },
         new FlagTranslate { ID = "SA", name = "Saudi Arabia" },
         new FlagTranslate { ID = "SB", name = "Solomon Islands" },
         new FlagTranslate { ID = "SC", name = "Seychelles" },
         new FlagTranslate { ID = "SD", name = "Sudan" },
         new FlagTranslate { ID = "SE", name = "Sweden" },
         new FlagTranslate { ID = "SG", name = "Singapore" },
         new FlagTranslate { ID = "SH", name = "Saint Helena" },
         new FlagTranslate { ID = "SI", name = "Slovenia" },
         new FlagTranslate { ID = "SJ", name = "Svalbard and Jan Mayen Islands" },
         new FlagTranslate { ID = "SK", name = "Slovakia" },
         new FlagTranslate { ID = "SL", name = "Sierra Leone" },
         new FlagTranslate { ID = "SM", name = "San Marino" },
         new FlagTranslate { ID = "SN", name = "Senegal" },
         new FlagTranslate { ID = "SO", name = "Somalia" },
         new FlagTranslate { ID = "SR", name = "Suriname" },
         new FlagTranslate { ID = "SS", name = "South Sudan" },
         new FlagTranslate { ID = "ST", name = "Sao Tome and Principe" },
         new FlagTranslate { ID = "SV", name = "El Salvador" },
         new FlagTranslate { ID = "SY", name = "Syrian Arab Republic (Syria)" },
         new FlagTranslate { ID = "SZ", name = "Swaziland" },
         new FlagTranslate { ID = "TC", name = "Turks and Caicos Islands" },
         new FlagTranslate { ID = "TD", name = "Chad" },
         new FlagTranslate { ID = "TF", name = "French Southern Territories" },
         new FlagTranslate { ID = "TG", name = "Togo" },
         new FlagTranslate { ID = "TH", name = "Thailand" },
         new FlagTranslate { ID = "TJ", name = "Tajikistan" },
         new FlagTranslate { ID = "TK", name = "Tokelau" },
         new FlagTranslate { ID = "TL", name = "Timor-Leste" },
         new FlagTranslate { ID = "TM", name = "Turkmenistan" },
         new FlagTranslate { ID = "TN", name = "Tunisia" },
         new FlagTranslate { ID = "TO", name = "Tonga" },
         new FlagTranslate { ID = "TR", name = "Turkey" },
         new FlagTranslate { ID = "TT", name = "Trinidad and Tobago" },
         new FlagTranslate { ID = "TV", name = "Tuvalu" },
         new FlagTranslate { ID = "TW", name = "Taiwan, Republic of China" },
         new FlagTranslate { ID = "TZ", name = "Tanzania, United Republic of" },
         new FlagTranslate { ID = "UA", name = "Ukraine" },
         new FlagTranslate { ID = "UG", name = "Uganda" },
         new FlagTranslate { ID = "UM", name = "US Minor Outlying Islands" },
         new FlagTranslate { ID = "US", name = "United States of America" },
         new FlagTranslate { ID = "UY", name = "Uruguay" },
         new FlagTranslate { ID = "UZ", name = "Uzbekistan" },
         new FlagTranslate { ID = "VA", name = "Holy See (Vatican City State)" },
         new FlagTranslate { ID = "VC", name = "Saint Vincent and Grenadines" },
         new FlagTranslate { ID = "VE", name = "Venezuela (Bolivarian Republic)" },
         new FlagTranslate { ID = "VG", name = "British Virgin Islands" },
         new FlagTranslate { ID = "VI", name = "Virgin Islands, US" },
         new FlagTranslate { ID = "VN", name = "Viet Nam" },
         new FlagTranslate { ID = "VU", name = "Vanuatu" },
         new FlagTranslate { ID = "WF", name = "Wallis and Futuna Islands" },
         new FlagTranslate { ID = "WS", name = "Samoa" },
         new FlagTranslate { ID = "YE", name = "Yemen" },
         new FlagTranslate { ID = "YT", name = "Mayotte" },
         new FlagTranslate { ID = "ZA", name = "South Africa" },
         new FlagTranslate { ID = "ZM", name = "Zambia" },
         new FlagTranslate { ID = "ZW", name = "Zimbabwe" }
    };

    public static List<FlagTranslate> world_RO = new List<FlagTranslate>()
    {
         new FlagTranslate { ID = "AD", name = "Andorra" },
         new FlagTranslate { ID = "AE", name = "Emiratele Arabe Unite" },
         new FlagTranslate { ID = "AF", name = "Afganistan" },
         new FlagTranslate { ID = "AG", name = "Antigua si Barbuda" },
         new FlagTranslate { ID = "AI", name = "Anguilla" },
         new FlagTranslate { ID = "AL", name = "Albania" },
         new FlagTranslate { ID = "AM", name = "Armenia" },
         new FlagTranslate { ID = "AN", name = "Antilele Olandeze" },
         new FlagTranslate { ID = "AO", name = "Angola" },
         new FlagTranslate { ID = "AQ", name = "Antarctica" },
         new FlagTranslate { ID = "AR", name = "Argentina" },
         new FlagTranslate { ID = "AS", name = "Samoa Americană" },
         new FlagTranslate { ID = "AT", name = "Austria" },
         new FlagTranslate { ID = "AU", name = "Australia" },
         new FlagTranslate { ID = "AW", name = "Aruba" },
         new FlagTranslate { ID = "AX", name = "Insulele Aland" },
         new FlagTranslate { ID = "AZ", name = "Azerbaidjan" },
         new FlagTranslate { ID = "BA", name = "Bosnia si Hertegovina" },
         new FlagTranslate { ID = "BB", name = "Barbados" },
         new FlagTranslate { ID = "BD", name = "Bangladesh" },
         new FlagTranslate { ID = "BE", name = "Belgia" },
         new FlagTranslate { ID = "BF", name = "Burkina Faso" },
         new FlagTranslate { ID = "BG", name = "Bulgaria" },
         new FlagTranslate { ID = "BH", name = "Bahrain" },
         new FlagTranslate { ID = "BI", name = "Burundi" },
         new FlagTranslate { ID = "BJ", name = "Benin" },
         new FlagTranslate { ID = "BL", name = "Saint-Barthélemy" },
         new FlagTranslate { ID = "BM", name = "Bermude" },
         new FlagTranslate { ID = "BN", name = "Brunei Darussalam" },
         new FlagTranslate { ID = "BO", name = "Bolivia" },
         new FlagTranslate { ID = "BR", name = "Brazilia" },
         new FlagTranslate { ID = "BS", name = "Bahamas" },
         new FlagTranslate { ID = "BT", name = "Bhutan" },
         new FlagTranslate { ID = "BV", name = "Insula Bouvet" },
         new FlagTranslate { ID = "BW", name = "Botswana" },
         new FlagTranslate { ID = "BY", name = "Bielorusia" },
         new FlagTranslate { ID = "BZ", name = "Belize" },
         new FlagTranslate { ID = "CA", name = "Canada" },
         new FlagTranslate { ID = "CC", name = "Insulele Cocos (Keeling)." },
         new FlagTranslate { ID = "CD", name = "Congo, (Kinshasa)" },
         new FlagTranslate { ID = "CF", name = "Republica Centrafricană" },
         new FlagTranslate { ID = "CG", name = "Congo (Brazzaville)" },
         new FlagTranslate { ID = "CH", name = "Elveţia" },
         new FlagTranslate { ID = "CI", name = "Côte d'Ivoire" },
         new FlagTranslate { ID = "CK", name = "Insulele Cook" },
         new FlagTranslate { ID = "CL", name = "Chile" },
         new FlagTranslate { ID = "CM", name = "Camerun" },
         new FlagTranslate { ID = "CN", name = "China" },
         new FlagTranslate { ID = "CO", name = "Columbia" },
         new FlagTranslate { ID = "CR", name = "Costa Rica" },
         new FlagTranslate { ID = "CU", name = "Cuba" },
         new FlagTranslate { ID = "CV", name = "capul Verde" },
         new FlagTranslate { ID = "CX", name = "Insula Craciunului" },
         new FlagTranslate { ID = "CY", name = "Cipru" },
         new FlagTranslate { ID = "CZ", name = "Republica Cehă" },
         new FlagTranslate { ID = "DE", name = "Germania" },
         new FlagTranslate { ID = "DJ", name = "Djibouti" },
         new FlagTranslate { ID = "DK", name = "Danemarca" },
         new FlagTranslate { ID = "DM", name = "Dominica" },
         new FlagTranslate { ID = "DO", name = "Republica Dominicană" },
         new FlagTranslate { ID = "DZ", name = "Algeria" },
         new FlagTranslate { ID = "EC", name = "Ecuador" },
         new FlagTranslate { ID = "EE", name = "Estonia" },
         new FlagTranslate { ID = "EG", name = "Egipt" },
         new FlagTranslate { ID = "EH", name = "sahara de Vest" },
         new FlagTranslate { ID = "ER", name = "Eritreea" },
         new FlagTranslate { ID = "ES", name = "Spania" },
         new FlagTranslate { ID = "ET", name = "Etiopia" },
         new FlagTranslate { ID = "FI", name = "Finlanda" },
         new FlagTranslate { ID = "FJ", name = "Fiji" },
         new FlagTranslate { ID = "FK", name = "Insulele Falkland (Malvinas)" },
         new FlagTranslate { ID = "FM", name = "Micronezia, Statele Federate ale" },
         new FlagTranslate { ID = "FO", name = "Insulele Feroe" },
         new FlagTranslate { ID = "FR", name = "Franţa" },
         new FlagTranslate { ID = "GA", name = "Gabon" },
         new FlagTranslate { ID = "GB", name = "Regatul Unit" },
         new FlagTranslate { ID = "GD", name = "Grenada" },
         new FlagTranslate { ID = "GE", name = "Georgia" },
         new FlagTranslate { ID = "GF", name = "Guyana Franceză" },
         new FlagTranslate { ID = "GG", name = "Guernsey" },
         new FlagTranslate { ID = "GH", name = "Ghana" },
         new FlagTranslate { ID = "GI", name = "Gibraltar" },
         new FlagTranslate { ID = "GL", name = "Groenlanda" },
         new FlagTranslate { ID = "GM", name = "Gambia" },
         new FlagTranslate { ID = "GN", name = "Guineea" },
         new FlagTranslate { ID = "GP", name = "Guadelupa" },
         new FlagTranslate { ID = "GQ", name = "Guineea Ecuatorială" },
         new FlagTranslate { ID = "GR", name = "Grecia" },
         new FlagTranslate { ID = "GS", name = "Georgia de Sud și Insulele Sandwich de Sud" },
         new FlagTranslate { ID = "GT", name = "Guatemala" },
         new FlagTranslate { ID = "GU", name = "Guam" },
         new FlagTranslate { ID = "GW", name = "Guineea-Bissau" },
         new FlagTranslate { ID = "GY", name = "Guyana" },
         new FlagTranslate { ID = "HK", name = "Hong Kong, SAR China" },
         new FlagTranslate { ID = "HM", name = "Insulele Heard și Mcdonald" },
         new FlagTranslate { ID = "HN", name = "Honduras" },
         new FlagTranslate { ID = "HR", name = "Croaţia" },
         new FlagTranslate { ID = "HT", name = "Haiti" },
         new FlagTranslate { ID = "HU", name = "Ungaria" },
         new FlagTranslate { ID = "ID", name = "Indonezia" },
         new FlagTranslate { ID = "IE", name = "Irlanda" },
         new FlagTranslate { ID = "IL", name = "Israel" },
         new FlagTranslate { ID = "IM", name = "insula Barbatului" },
         new FlagTranslate { ID = "IN", name = "India" },
         new FlagTranslate { ID = "IO", name = "Teritoriul Britanic al Oceanului Indian" },
         new FlagTranslate { ID = "IQ", name = "Irak" },
         new FlagTranslate { ID = "IR", name = "Iran (Republica Islamica a" },
         new FlagTranslate { ID = "IS", name = "Islanda" },
         new FlagTranslate { ID = "IT", name = "Italia" },
         new FlagTranslate { ID = "JE", name = "Jersey" },
         new FlagTranslate { ID = "JM", name = "Jamaica" },
         new FlagTranslate { ID = "JO", name = "Iordania" },
         new FlagTranslate { ID = "JP", name = "Japonia" },
         new FlagTranslate { ID = "KE", name = "Kenya" },
         new FlagTranslate { ID = "KG", name = "Kârgâzstan" },
         new FlagTranslate { ID = "KH", name = "Cambodgia" },
         new FlagTranslate { ID = "KI", name = "Kiribati" },
         new FlagTranslate { ID = "KM", name = "Comore" },
         new FlagTranslate { ID = "KN", name = "Saint Kitts și Nevis" },
         new FlagTranslate { ID = "KP", name = "Coreea de Nord" },
         new FlagTranslate { ID = "KR", name = "Coreea de Sud)" },
         new FlagTranslate { ID = "KW", name = "Kuweit" },
         new FlagTranslate { ID = "KY", name = "Insulele Cayman" },
         new FlagTranslate { ID = "KZ", name = "Kazahstan" },
         new FlagTranslate { ID = "LA", name = "RDP Lao" },
         new FlagTranslate { ID = "LB", name = "Liban" },
         new FlagTranslate { ID = "LC", name = "Sfânta Lucia" },
         new FlagTranslate { ID = "LI", name = "Liechtenstein" },
         new FlagTranslate { ID = "LK", name = "Sri Lanka" },
         new FlagTranslate { ID = "LR", name = "Liberia" },
         new FlagTranslate { ID = "LS", name = "Lesotho" },
         new FlagTranslate { ID = "LT", name = "Lituania" },
         new FlagTranslate { ID = "LU", name = "Luxemburg" },
         new FlagTranslate { ID = "LV", name = "Letonia" },
         new FlagTranslate { ID = "LY", name = "Libia" },
         new FlagTranslate { ID = "MA", name = "Maroc" },
         new FlagTranslate { ID = "MC", name = "Monaco" },
         new FlagTranslate { ID = "MD", name = "Moldova" },
         new FlagTranslate { ID = "ME", name = "Muntenegru" },
         new FlagTranslate { ID = "MF", name = "Saint-Martin (partea franceză)" },
         new FlagTranslate { ID = "MG", name = "Madagascar" },
         new FlagTranslate { ID = "MH", name = "Insulele Marshall" },
         new FlagTranslate { ID = "MK", name = "Republica Macedonia de Nord" },
         new FlagTranslate { ID = "ML", name = "Mali" },
         new FlagTranslate { ID = "MM", name = "Myanmar" },
         new FlagTranslate { ID = "MN", name = "Mongolia" },
         new FlagTranslate { ID = "MO", name = "Macao, SAR China" },
         new FlagTranslate { ID = "MP", name = "Insulele Mariane de Nord" },
         new FlagTranslate { ID = "MQ", name = "Martinica" },
         new FlagTranslate { ID = "MR", name = "Mauritania" },
         new FlagTranslate { ID = "MS", name = "Montserrat" },
         new FlagTranslate { ID = "MT", name = "Malta" },
         new FlagTranslate { ID = "MU", name = "Mauritius" },
         new FlagTranslate { ID = "MV", name = "Maldive" },
         new FlagTranslate { ID = "MW", name = "Malawi" },
         new FlagTranslate { ID = "MX", name = "Mexic" },
         new FlagTranslate { ID = "MY", name = "Malaezia" },
         new FlagTranslate { ID = "MZ", name = "Mozambic" },
         new FlagTranslate { ID = "NA", name = "Namibia" },
         new FlagTranslate { ID = "NC", name = "Noua Caledonie" },
         new FlagTranslate { ID = "NE", name = "Niger" },
         new FlagTranslate { ID = "NF", name = "Insula Norfolk" },
         new FlagTranslate { ID = "NG", name = "Nigeria" },
         new FlagTranslate { ID = "NI", name = "Nicaragua" },
         new FlagTranslate { ID = "NL", name = "Olanda" },
         new FlagTranslate { ID = "NO", name = "Norvegia" },
         new FlagTranslate { ID = "NP", name = "Nepal" },
         new FlagTranslate { ID = "NR", name = "Nauru" },
         new FlagTranslate { ID = "NU", name = "Niue" },
         new FlagTranslate { ID = "NZ", name = "Noua Zeelandă" },
         new FlagTranslate { ID = "OM", name = "Oman" },
         new FlagTranslate { ID = "PA", name = "Panama" },
         new FlagTranslate { ID = "PE", name = "Peru" },
         new FlagTranslate { ID = "PF", name = "Polinezia Franceză" },
         new FlagTranslate { ID = "PG", name = "Papua Noua Guinee" },
         new FlagTranslate { ID = "PH", name = "Filipine" },
         new FlagTranslate { ID = "PK", name = "Pakistan" },
         new FlagTranslate { ID = "PL", name = "Polonia" },
         new FlagTranslate { ID = "PM", name = "Saint Pierre și Miquelon" },
         new FlagTranslate { ID = "PN", name = "Pitcairn" },
         new FlagTranslate { ID = "PR", name = "Puerto Rico" },
         new FlagTranslate { ID = "PS", name = "Teritoriul Palestinian" },
         new FlagTranslate { ID = "PT", name = "Portugalia" },
         new FlagTranslate { ID = "PW", name = "Palau" },
         new FlagTranslate { ID = "PY", name = "Paraguay" },
         new FlagTranslate { ID = "QA", name = "Qatar" },
         new FlagTranslate { ID = "RE", name = "Reuniune" },
         new FlagTranslate { ID = "RO", name = "România" },
         new FlagTranslate { ID = "RS", name = "Serbia" },
         new FlagTranslate { ID = "RU", name = "Federația Rusă" },
         new FlagTranslate { ID = "RW", name = "Rwanda" },
         new FlagTranslate { ID = "SA", name = "Arabia Saudită" },
         new FlagTranslate { ID = "SB", name = "Insulele Solomon" },
         new FlagTranslate { ID = "SC", name = "Seychelles" },
         new FlagTranslate { ID = "SD", name = "Sudan" },
         new FlagTranslate { ID = "SE", name = "Suedia" },
         new FlagTranslate { ID = "SG", name = "Singapore" },
         new FlagTranslate { ID = "SH", name = "Sfânta Elena" },
         new FlagTranslate { ID = "SI", name = "Slovenia" },
         new FlagTranslate { ID = "SJ", name = "Insulele Svalbard și Jan Mayen" },
         new FlagTranslate { ID = "SK", name = "Slovacia" },
         new FlagTranslate { ID = "SL", name = "Sierra Leone" },
         new FlagTranslate { ID = "SM", name = "San Marino" },
         new FlagTranslate { ID = "SN", name = "Senegal" },
         new FlagTranslate { ID = "SO", name = "Somalia" },
         new FlagTranslate { ID = "SR", name = "Surinam" },
         new FlagTranslate { ID = "SS", name = "Sudul Sudanului" },
         new FlagTranslate { ID = "ST", name = "Sao Tome și Principe" },
         new FlagTranslate { ID = "SV", name = "El Salvador" },
         new FlagTranslate { ID = "SY", name = "Republica Arabă Siriană (Siria)" },
         new FlagTranslate { ID = "SZ", name = "Swaziland" },
         new FlagTranslate { ID = "TC", name = "Insulele Turks și Caicos" },
         new FlagTranslate { ID = "TD", name = "Ciad" },
         new FlagTranslate { ID = "TF", name = "teritoriile din sudul Frantei" },
         new FlagTranslate { ID = "TG", name = "A merge" },
         new FlagTranslate { ID = "TH", name = "Tailanda" },
         new FlagTranslate { ID = "TJ", name = "Tadjikistan" },
         new FlagTranslate { ID = "TK", name = "Tokelau" },
         new FlagTranslate { ID = "TL", name = "Timorul de Est" },
         new FlagTranslate { ID = "TM", name = "Turkmenistan" },
         new FlagTranslate { ID = "TN", name = "Tunisia" },
         new FlagTranslate { ID = "TO", name = "Tonga" },
         new FlagTranslate { ID = "TR", name = "Curcan" },
         new FlagTranslate { ID = "TT", name = "Trinidad și Tobago" },
         new FlagTranslate { ID = "TV", name = "Tuvalu" },
         new FlagTranslate { ID = "TW", name = "Taiwan" },
         new FlagTranslate { ID = "TZ", name = "Tanzania" },
         new FlagTranslate { ID = "UA", name = "Ucraina" },
         new FlagTranslate { ID = "UG", name = "Uganda" },
         new FlagTranslate { ID = "UM", name = "Insulele minore periferice ale SUA" },
         new FlagTranslate { ID = "US", name = "Statele Unite ale Americii" },
         new FlagTranslate { ID = "UY", name = "Uruguay" },
         new FlagTranslate { ID = "UZ", name = "Uzbekistan" },
         new FlagTranslate { ID = "VA", name = "Statul Vatican" },
         new FlagTranslate { ID = "VC", name = "Saint Vincent și Grenadine" },
         new FlagTranslate { ID = "VE", name = "Venezuela (Republica Bolivariană)" },
         new FlagTranslate { ID = "VG", name = "Insulele Virgine Britanice" },
         new FlagTranslate { ID = "VI", name = "Insulele Virgine, SUA" },
         new FlagTranslate { ID = "VN", name = "Vietnam" },
         new FlagTranslate { ID = "VU", name = "Vanuatu" },
         new FlagTranslate { ID = "WF", name = "Insulele Wallis și Futuna" },
         new FlagTranslate { ID = "WS", name = "Samoa" },
         new FlagTranslate { ID = "YE", name = "Yemen" },
         new FlagTranslate { ID = "YE", name = "Yemen" },
         new FlagTranslate { ID = "YT", name = "Mayotte" },
         new FlagTranslate { ID = "ZA", name = "Africa de Sud" },
         new FlagTranslate { ID = "ZM", name = "Zambia" },
         new FlagTranslate { ID = "ZW", name = "Zimbabwe" }
    };

    public static List<FlagTranslate> world_FR = new List<FlagTranslate>()
    {
         new FlagTranslate { ID = "afghane", name = "AF" },
         new FlagTranslate { ID = "AX", name = "Îles Aland" },
         new FlagTranslate { ID = "AL", name = "Albanie" },
         new FlagTranslate { ID = "DZ", name = "Algérie" },
         new FlagTranslate { ID = "AS", name = "Samoa américaines" },
         new FlagTranslate { ID = "AD", name = "Andorre" },
         new FlagTranslate { ID = "AO", name = "Angola" },
         new FlagTranslate { ID = "d'Anguilla", name = "L'IA" },
         new FlagTranslate { ID = "Antarctique", name = "QA" },
         new FlagTranslate { ID = "SA", name = "Antigua-et-Barbuda" },
         new FlagTranslate { ID = "AR", name = "Argentine" },
         new FlagTranslate { ID = "AM", name = "Arménie" },
         new FlagTranslate { ID = "AW", name = "Aruba" },
         new FlagTranslate { ID = "AU", name = "Australie" },
         new FlagTranslate { ID = "AT", name = "Autriche" },
         new FlagTranslate { ID = "AZ", name = "Azerbaïdjan" },
         new FlagTranslate { ID = "BS", name = "Bahamas" },
         new FlagTranslate { ID = "BH", name = "Bahreïn" },
         new FlagTranslate { ID = "BD", name = "Bangladesh" },
         new FlagTranslate { ID = "BB", name = "Barbade" },
         new FlagTranslate { ID = "PAR", name = "Biélorussie" },
         new FlagTranslate { ID = "BE", name = "Belgique" },
         new FlagTranslate { ID = "BZ", name = "Belize" },
         new FlagTranslate { ID = "BJ", name = "Bénin" },
         new FlagTranslate { ID = "BM", name = "Bermudes" },
         new FlagTranslate { ID = "BT", name = "Bhoutan" },
         new FlagTranslate { ID = "BO", name = "Bolivie" },
         new FlagTranslate { ID = "Bosnie-Herzégovine", name = "BA" },
         new FlagTranslate { ID = "BW", name = "Botswana" },
         new FlagTranslate { ID = "BV", name = "Île Bouvet" },
         new FlagTranslate { ID = "BR", name = "Brésil" },
         new FlagTranslate { ID = "VG", name = "Îles Vierges britanniques" },
         new FlagTranslate { ID = "OI", name = "Territoire britannique de l'océan Indien" },
         new FlagTranslate { ID = "BN", name = "Brunéi Darussalam" },
         new FlagTranslate { ID = "BG", name = "Bulgarie" },
         new FlagTranslate { ID = "BF", name = "Burkina Faso" },
         new FlagTranslate { ID = "BI", name = "Burundi" },
         new FlagTranslate { ID = "KH", name = "Cambodge" },
         new FlagTranslate { ID = "CM", name = "Cameroun" },
         new FlagTranslate { ID = "CA", name = "Canada" },
         new FlagTranslate { ID = "Vert", name = "CV Cap" },
         new FlagTranslate { ID = "KY", name = "Îles Caïmans" },
         new FlagTranslate { ID = "CF", name = "République centrafricaine" },
         new FlagTranslate { ID = "TD", name = "Tchad" },
         new FlagTranslate { ID = "CL", name = "Chili" },
         new FlagTranslate { ID = "CN", name = "Chine" },
         new FlagTranslate { ID = "HK", name = "Hong Kong, RAS Chine" },
         new FlagTranslate { ID = "MO", name = "Macao, RAS Chine" },
         new FlagTranslate { ID = "CX", name = "Île de Noël" },
         new FlagTranslate { ID = "CC", name = "Îles Cocos (Keeling)" },
         new FlagTranslate { ID = "CO", name = "Colombie" },
         new FlagTranslate { ID = "KM", name = "Comores" },
         new FlagTranslate { ID = "CG", name = "Congo (Brazzaville)" },
         new FlagTranslate { ID = "CD", name = "Congo, (Kinshasa)" },
         new FlagTranslate { ID = "CK", name = "Îles Cook" },
         new FlagTranslate { ID = "RC", name = "Costa Rica" },
         new FlagTranslate { ID = "CI", name = "Côte d'Ivoire" },
         new FlagTranslate { ID = "RH", name = "Croatie" },
         new FlagTranslate { ID = "CU", name = "Cuba" },
         new FlagTranslate { ID = "CY", name = "Chypre" },
         new FlagTranslate { ID = "CZ", name = "République tchèque" },
         new FlagTranslate { ID = "DK", name = "Danemark" },
         new FlagTranslate { ID = "djiboutien", name = "DJ" },
         new FlagTranslate { ID = "DM", name = "Dominique" },
         new FlagTranslate { ID = "DO", name = "République dominicaine" },
         new FlagTranslate { ID = "CE", name = "Equateur" },
         new FlagTranslate { ID = "EG", name = "Égypte" },
         new FlagTranslate { ID = "SV", name = "Salvador" },
         new FlagTranslate { ID = "GQ", name = "Guinée équatoriale" },
         new FlagTranslate { ID = "Érythrée", name = "urgence" },
         new FlagTranslate { ID = "EE", name = "Estonie" },
         new FlagTranslate { ID = "ET", name = "Éthiopie" },
         new FlagTranslate { ID = "FK", name = "Îles Falkland (Malvinas)" },
         new FlagTranslate { ID = "FO", name = "Iles Féroé" },
         new FlagTranslate { ID = "FJ", name = "Fidji" },
         new FlagTranslate { ID = "FI", name = "Finlande" },
         new FlagTranslate { ID = "FR", name = "France" },
         new FlagTranslate { ID = "GF", name = "Guyane française" },
         new FlagTranslate { ID = "PF", name = "Polynésie française" },
         new FlagTranslate { ID = "Françaises", name = "TF Terres Australes" },
         new FlagTranslate { ID = "Gabon", name = "GA" },
         new FlagTranslate { ID = "DG", name = "Gambie" },
         new FlagTranslate { ID = "GE", name = "Géorgie" },
         new FlagTranslate { ID = "DE", name = "Allemagne" },
         new FlagTranslate { ID = "GH", name = "Ghana" },
         new FlagTranslate { ID = "IG", name = "Gibraltar" },
         new FlagTranslate { ID = "GR", name = "Grèce" },
         new FlagTranslate { ID = "GL", name = "Groenland" },
         new FlagTranslate { ID = "GD", name = "Grenade" },
         new FlagTranslate { ID = "Guadeloupe", name = "GP de" },
         new FlagTranslate { ID = "GU", name = "Guam" },
         new FlagTranslate { ID = "GT", name = "Guatemala" },
         new FlagTranslate { ID = "GG", name = "Guernesey" },
         new FlagTranslate { ID = "GN", name = "Guinée" },
         new FlagTranslate { ID = "GW", name = "Guinée-Bissau" },
         new FlagTranslate { ID = "GY", name = "Guyane" },
         new FlagTranslate { ID = "HT", name = "Haïti" },
         new FlagTranslate { ID = "HM", name = "Îles Heard et McDonald" },
         new FlagTranslate { ID = "VA", name = "Saint-Siège (État de la Cité du Vatican)" },
         new FlagTranslate { ID = "HN", name = "Honduras" },
         new FlagTranslate { ID = "HU", name = "Hongrie" },
         new FlagTranslate { ID = "est", name = "L'Islande" },
         new FlagTranslate { ID = "EN", name = "Inde" },
         new FlagTranslate { ID = "Indonésie", name = "ID" },
         new FlagTranslate { ID = "RI", name = "Iran, République islamique de" },
         new FlagTranslate { ID = "QI", name = "Irak" },
         new FlagTranslate { ID = "IE", name = "Irlande" },
         new FlagTranslate { ID = "IM", name = "Île de Man" },
         new FlagTranslate { ID = "IL", name = "Israël" },
         new FlagTranslate { ID = "IT", name = "Italie" },
         new FlagTranslate { ID = "JM", name = "Jamaïque" },
         new FlagTranslate { ID = "JP", name = "Japon" },
         new FlagTranslate { ID = "JE", name = "Maillot" },
         new FlagTranslate { ID = "JO", name = "Jordanie" },
         new FlagTranslate { ID = "KZ", name = "Kazakhstan" },
         new FlagTranslate { ID = "KE", name = "Kenya" },
         new FlagTranslate { ID = "KI", name = "Kiribati" },
         new FlagTranslate { ID = "KP", name = "Corée (Nord)" },
         new FlagTranslate { ID = "KR", name = "Corée (du Sud)" },
         new FlagTranslate { ID = "KW", name = "Koweït" },
         new FlagTranslate { ID = "KG", name = "Kirghizistan" },
         new FlagTranslate { ID = "LA", name = "RDP lao" },
         new FlagTranslate { ID = "LV", name = "Lettonie" },
         new FlagTranslate { ID = "LB", name = "Liban" },
         new FlagTranslate { ID = "LS", name = "Lesotho" },
         new FlagTranslate { ID = "LR", name = "Libéria" },
         new FlagTranslate { ID = "LY", name = "Libye" },
         new FlagTranslate { ID = "LI", name = "Liechtenstein" },
         new FlagTranslate { ID = "LT", name = "Lituanie" },
         new FlagTranslate { ID = "LU", name = "Luxembourg" },
         new FlagTranslate { ID = "MK", name = "Macédoine, République de" },
         new FlagTranslate { ID = "MG", name = "Madagascar" },
         new FlagTranslate { ID = "MW", name = "Malawi" },
         new FlagTranslate { ID = "MA", name = "Malaisie" },
         new FlagTranslate { ID = "MV", name = "Maldives" },
         new FlagTranslate { ID = "ML", name = "Mali" },
         new FlagTranslate { ID = "MT", name = "Malte" },
         new FlagTranslate { ID = "MH", name = "Îles Marshall" },
         new FlagTranslate { ID = "MQ", name = "Martinique" },
         new FlagTranslate { ID = "MR", name = "Mauritanie" },
         new FlagTranslate { ID = "Maurice", name = "UM" },
         new FlagTranslate { ID = "YT", name = "Mayotte" },
         new FlagTranslate { ID = "MX", name = "Mexique" },
         new FlagTranslate { ID = "FM", name = "Micronésie, États fédérés de" },
         new FlagTranslate { ID = "Moldavie", name = "MD" },
         new FlagTranslate { ID = "MC", name = "Monaco" },
         new FlagTranslate { ID = "MN", name = "Mongolie" },
         new FlagTranslate { ID = "ME", name = "Monténégro" },
         new FlagTranslate { ID = "MS", name = "Montserrat" },
         new FlagTranslate { ID = "MA", name = "Maroc" },
         new FlagTranslate { ID = "MZ", name = "Mozambique" },
         new FlagTranslate { ID = "MM", name = "Birmanie" },
         new FlagTranslate { ID = "NA", name = "Namibie" },
         new FlagTranslate { ID = "Nord", name = "Nauru" },
         new FlagTranslate { ID = "NP", name = "Népal" },
         new FlagTranslate { ID = "NL", name = "Pays-Bas" },
         new FlagTranslate { ID = "AN", name = "Antilles néerlandaises" },
         new FlagTranslate { ID = "NC", name = "Nouvelle Calédonie" },
         new FlagTranslate { ID = "NZ", name = "Nouvelle-Zélande" },
         new FlagTranslate { ID = "NI", name = "Nicaragua" },
         new FlagTranslate { ID = "NE", name = "Niger" },
         new FlagTranslate { ID = "NG", name = "Nigéria" },
         new FlagTranslate { ID = "NU", name = "Nioué" },
         new FlagTranslate { ID = "NF", name = "Île Norfolk" },
         new FlagTranslate { ID = "Nord", name = "Député des îles Mariannes du" },
         new FlagTranslate { ID = "NON", name = "Norvège" },
         new FlagTranslate { ID = "OM", name = "Oman" },
         new FlagTranslate { ID = "PK", name = "Pakistan" },
         new FlagTranslate { ID = "PW", name = "Palaos" },
         new FlagTranslate { ID = "PS", name = "Territoire palestinien" },
         new FlagTranslate { ID = "panaméenne", name = "PA" },
         new FlagTranslate { ID = "PG", name = "Papouasie-Nouvelle-Guinée" },
         new FlagTranslate { ID = "PY", name = "Paraguay" },
         new FlagTranslate { ID = "PE", name = "Pérou" },
         new FlagTranslate { ID = "PH", name = "Philippines" },
         new FlagTranslate { ID = "PN", name = "Pitcairn" },
         new FlagTranslate { ID = "PL", name = "Pologne" },
         new FlagTranslate { ID = "TP", name = "Portugal" },
         new FlagTranslate { ID = "Rico", name = "Relations publiques de Porto" },
         new FlagTranslate { ID = "Qatar", name = "AQ du" },
         new FlagTranslate { ID = "RE", name = "Réunion" },
         new FlagTranslate { ID = "RO", name = "Roumanie" },
         new FlagTranslate { ID = "RU", name = "Fédération de Russie" },
         new FlagTranslate { ID = "AD", name = "Rwanda" },
         new FlagTranslate { ID = "BL", name = "Saint-Barthélemy" },
         new FlagTranslate { ID = "SH", name = "Sainte-Hélène" },
         new FlagTranslate { ID = "KN", name = "Saint-Kitts-et-Nevis" },
         new FlagTranslate { ID = "LC", name = "Sainte-Lucie" },
         new FlagTranslate { ID = "MF", name = "Saint-Martin (partie française)" },
         new FlagTranslate { ID = "PM", name = "Saint Pierre et Miquelon" },
         new FlagTranslate { ID = "VC", name = "Saint-Vincent-et-les Grenadines" },
         new FlagTranslate { ID = "WS", name = "Samoa" },
         new FlagTranslate { ID = "SM", name = "Saint-Marin" },
         new FlagTranslate { ID = "Principe", name = "Rue Sao Tomé et" },
         new FlagTranslate { ID = "SA", name = "Arabie Saoudite" },
         new FlagTranslate { ID = "SN", name = "Sénégal" },
         new FlagTranslate { ID = "RS", name = "Serbie" },
         new FlagTranslate { ID = "Seychelles", name = "" },
         new FlagTranslate { ID = "SL", name = "Sierra Leone" },
         new FlagTranslate { ID = "SG", name = "Singapour" },
         new FlagTranslate { ID = "SK", name = "Slovaquie" },
         new FlagTranslate { ID = "SI", name = "Slovénie" },
         new FlagTranslate { ID = "SB", name = "Îles Salomon" },
         new FlagTranslate { ID = "SO", name = "Somalie" },
         new FlagTranslate { ID = "ZA", name = "Afrique du Sud" },
         new FlagTranslate { ID = "Sud", name = "GS de Géorgie du Sud et des îles Sandwich du" },
         new FlagTranslate { ID = "Sud", name = "SS du Soudan du" },
         new FlagTranslate { ID = "ES", name = "Espagne" },
         new FlagTranslate { ID = "LK", name = "Sri Lanka" },
         new FlagTranslate { ID = "SD", name = "Soudan" },
         new FlagTranslate { ID = "RS", name = "Suriname" },
         new FlagTranslate { ID = "SJ", name = "Îles Svalbard et Jan Mayen" },
         new FlagTranslate { ID = "SZ", name = "Swaziland" },
         new FlagTranslate { ID = "SE", name = "Suède" },
         new FlagTranslate { ID = "CH", name = "Suisse" },
         new FlagTranslate { ID = "SY", name = "République arabe syrienne (Syrie)" },
         new FlagTranslate { ID = "TW", name = "Taïwan, République de Chine" },
         new FlagTranslate { ID = "TJ", name = "Tadjikistan" },
         new FlagTranslate { ID = "TZ", name = "Tanzanie, République-Unie de" },
         new FlagTranslate { ID = "TH", name = "Thaïlande" },
         new FlagTranslate { ID = "TL", name = "Timor oriental" },
         new FlagTranslate { ID = "TG", name = "Togo" },
         new FlagTranslate { ID = "Tokélaou", name = "TK des" },
         new FlagTranslate { ID = "VERS", name = "Tonga" },
         new FlagTranslate { ID = "TT", name = "Trinité-et-Tobago" },
         new FlagTranslate { ID = "TN", name = "Tunisie" },
         new FlagTranslate { ID = "TR", name = "Turquie" },
         new FlagTranslate { ID = "TM", name = "Turkménistan" },
         new FlagTranslate { ID = "Caïques", name = "TC des îles Turques et" },
         new FlagTranslate { ID = "Tuvalu", name = "Télévision de" },
         new FlagTranslate { ID = "UG", name = "Ouganda" },
         new FlagTranslate { ID = "UA", name = "Ukraine" },
         new FlagTranslate { ID = "AE", name = "Émirats arabes unis" },
         new FlagTranslate { ID = "GB", name = "Royaume-Uni" },
         new FlagTranslate { ID = "d'Amérique", name = "États-Unis" },
         new FlagTranslate { ID = "UM", name = "Îles mineures éloignées des États-Unis" },
         new FlagTranslate { ID = "UY", name = "Uruguay" },
         new FlagTranslate { ID = "UZ", name = "Ouzbékistan" },
         new FlagTranslate { ID = "VU", name = "Vanuatu" },
         new FlagTranslate { ID = "VE", name = "Venezuela (République bolivarienne)" },
         new FlagTranslate { ID = "VN", name = "Vietnam" },
         new FlagTranslate { ID = "VI", name = "Îles Vierges, États-Unis" },
         new FlagTranslate { ID = "WF", name = "Îles Wallis et Futuna" },
         new FlagTranslate { ID = "EH", name = "Sahara occidental" },
         new FlagTranslate { ID = "OUI", name = "Yémen" },
         new FlagTranslate { ID = "ZM", name = "Zambie" },
         new FlagTranslate { ID = "ZW", name = "Zimbabwe" },
         new FlagTranslate { ID = "OUI", name = "Yémen" },
         new FlagTranslate { ID = "ZM", name = "Zambie" },
         new FlagTranslate { ID = "ZW", name = "Zimbabwe" }
    };

    public static List<FlagTranslate> world_ES = new List<FlagTranslate>()
    {
         new FlagTranslate { ID = "AF", name = "Afganistán" },
         new FlagTranslate { ID = "Aland", name = "Hacha de las islas" },
         new FlagTranslate { ID = "AL", name = "Albania" },
         new FlagTranslate { ID = "DZ", name = "Argelia" },
         new FlagTranslate { ID = "AS", name = "Samoa Americana" },
         new FlagTranslate { ID = "AD", name = "Andorra" },
         new FlagTranslate { ID = "AO", name = "Angola" },
         new FlagTranslate { ID = "Anguila", name = "IA de" },
         new FlagTranslate { ID = "AQ", name = "Antártida" },
         new FlagTranslate { ID = "AG", name = "Antigua y Barbuda" },
         new FlagTranslate { ID = "AR", name = "Argentina" },
         new FlagTranslate { ID = "AM", name = "Armenia" },
         new FlagTranslate { ID = "AW", name = "Aruba" },
         new FlagTranslate { ID = "AU", name = "Australia" },
         new FlagTranslate { ID = "AT", name = "Austria" },
         new FlagTranslate { ID = "AZ", name = "Azerbaiyán" },
         new FlagTranslate { ID = "BS", name = "Bahamas" },
         new FlagTranslate { ID = "BH", name = "Baréin" },
         new FlagTranslate { ID = "BD", name = "Bangladesh" },
         new FlagTranslate { ID = "BB", name = "Barbados" },
         new FlagTranslate { ID = "BY", name = "Bielorrusia" },
         new FlagTranslate { ID = "BE", name = "Bélgica" },
         new FlagTranslate { ID = "BZ", name = "Belice" },
         new FlagTranslate { ID = "BJ", name = "Benin" },
         new FlagTranslate { ID = "BM", name = "Bermudas" },
         new FlagTranslate { ID = "BT", name = "Bután" },
         new FlagTranslate { ID = "BO", name = "Bolivia" },
         new FlagTranslate { ID = "BA", name = "Bosnia y Herzegovina" },
         new FlagTranslate { ID = "BW", name = "Botswana" },
         new FlagTranslate { ID = "BV", name = "Bouvet Island" },
         new FlagTranslate { ID = "BR", name = "Brasil" },
         new FlagTranslate { ID = "VG", name = "Islas Vírgenes Británicas" },
         new FlagTranslate { ID = "IO", name = "Territorio Británico del Océano Índico" },
         new FlagTranslate { ID = "BN", name = "Brunei Darussalam" },
         new FlagTranslate { ID = "BG", name = "Bulgaria" },
         new FlagTranslate { ID = "BF", name = "Burkina Faso" },
         new FlagTranslate { ID = "BI", name = "Burundi" },
         new FlagTranslate { ID = "KH", name = "Camboya" },
         new FlagTranslate { ID = "CM", name = "Camerún" },
         new FlagTranslate { ID = "CA", name = "Canadá" },
         new FlagTranslate { ID = "CV", name = "Cabo Verde" },
         new FlagTranslate { ID = "KY", name = "Islas Caimán" },
         new FlagTranslate { ID = "CF", name = "República Centroafricana" },
         new FlagTranslate { ID = "TD", name = "Chad" },
         new FlagTranslate { ID = "CL", name = "Chile" },
         new FlagTranslate { ID = "CN", name = "China" },
         new FlagTranslate { ID = "HK", name = "Hong Kong, RAE de China" },
         new FlagTranslate { ID = "MO", name = "Macao, RAE de China" },
         new FlagTranslate { ID = "CX", name = "Isla de Navidad" },
         new FlagTranslate { ID = "CC", name = "Islas Cocos (Keeling)" },
         new FlagTranslate { ID = "CO", name = "Colombia" },
         new FlagTranslate { ID = "KM", name = "Comoras" },
         new FlagTranslate { ID = "CG", name = "Congo (Brazzaville)" },
         new FlagTranslate { ID = "CD", name = "Congo, (Kinshasa)" },
         new FlagTranslate { ID = "CK", name = "Islas Cook" },
         new FlagTranslate { ID = "CR", name = "Costa Rica" },
         new FlagTranslate { ID = "CI", name = "Costa de Marfil" },
         new FlagTranslate { ID = "HR", name = "Croacia" },
         new FlagTranslate { ID = "CU", name = "Cuba" },
         new FlagTranslate { ID = "CY", name = "Chipre" },
         new FlagTranslate { ID = "CZ", name = "República Checa" },
         new FlagTranslate { ID = "DK", name = "Dinamarca" },
         new FlagTranslate { ID = "DJ", name = "Djibouti" },
         new FlagTranslate { ID = "DM", name = "Dominica" },
         new FlagTranslate { ID = "DO", name = "República Dominicana" },
         new FlagTranslate { ID = "EC", name = "Ecuador" },
         new FlagTranslate { ID = "EG", name = "Egipto" },
         new FlagTranslate { ID = "SV", name = "El Salvador" },
         new FlagTranslate { ID = "GQ", name = "Guinea Ecuatorial" },
         new FlagTranslate { ID = "Eritrea", name = "ER" },
         new FlagTranslate { ID = "EE", name = "Estonia" },
         new FlagTranslate { ID = "ET", name = "Etiopía" },
         new FlagTranslate { ID = "FK", name = "Islas Malvinas (Falkland)" },
         new FlagTranslate { ID = "FO", name = "Islas Feroe" },
         new FlagTranslate { ID = "FJ", name = "Fiyi" },
         new FlagTranslate { ID = "FI", name = "Finlandia" },
         new FlagTranslate { ID = "FR", name = "Francia" },
         new FlagTranslate { ID = "GF", name = "Guayana Francesa" },
         new FlagTranslate { ID = "PF", name = "Polinesia Francesa" },
         new FlagTranslate { ID = "TF", name = "Territorios Australes Franceses" },
         new FlagTranslate { ID = "GA", name = "Gabón" },
         new FlagTranslate { ID = "GM", name = "Gambia" },
         new FlagTranslate { ID = "GE", name = "Georgia" },
         new FlagTranslate { ID = "DE", name = "Alemania" },
         new FlagTranslate { ID = "GH", name = "Ghana" },
         new FlagTranslate { ID = "GI", name = "Gibraltar" },
         new FlagTranslate { ID = "GR", name = "Grecia" },
         new FlagTranslate { ID = "GL", name = "Groenlandia" },
         new FlagTranslate { ID = "GD", name = "Granada" },
         new FlagTranslate { ID = "Guadalupe", name = "GP de" },
         new FlagTranslate { ID = "GU", name = "Guam" },
         new FlagTranslate { ID = "GT", name = "Guatemala" },
         new FlagTranslate { ID = "GG", name = "Guernsey" },
         new FlagTranslate { ID = "GN", name = "Guinea" },
         new FlagTranslate { ID = "GW", name = "Guinea-Bissau" },
         new FlagTranslate { ID = "GY", name = "Guyana" },
         new FlagTranslate { ID = "HT", name = "Haití" },
         new FlagTranslate { ID = "HM", name = "Islas Heard y Mcdonald" },
         new FlagTranslate { ID = "VA", name = "Santa Sede (Estado de la Ciudad del Vaticano)" },
         new FlagTranslate { ID = "HN", name = "Honduras" },
         new FlagTranslate { ID = "HU", name = "Hungría" },
         new FlagTranslate { ID = "es", name = "Islandia" },
         new FlagTranslate { ID = "EN", name = "India" },
         new FlagTranslate { ID = "Indonesia", name = "Identificación de" },
         new FlagTranslate { ID = "IR", name = "Irán, República Islámica del" },
         new FlagTranslate { ID = "Irak", name = "IQ de" },
         new FlagTranslate { ID = "IE", name = "Irlanda" },
         new FlagTranslate { ID = "IM", name = "Isla de Man" },
         new FlagTranslate { ID = "IL", name = "Israel" },
         new FlagTranslate { ID = "IT", name = "Italia" },
         new FlagTranslate { ID = "JM", name = "Jamaica" },
         new FlagTranslate { ID = "JP", name = "Japón" },
         new FlagTranslate { ID = "JE", name = "Jersey" },
         new FlagTranslate { ID = "JO", name = "Jordan" },
         new FlagTranslate { ID = "KZ", name = "Kazajstán" },
         new FlagTranslate { ID = "KE", name = "Kenia" },
         new FlagTranslate { ID = "KI", name = "Kiribati" },
         new FlagTranslate { ID = "KP", name = "Corea (Norte)" },
         new FlagTranslate { ID = "KR", name = "Corea (Sur)" },
         new FlagTranslate { ID = "KW", name = "Kuwait" },
         new FlagTranslate { ID = "KG", name = "Kirguistán" },
         new FlagTranslate { ID = "LA", name = "Laos PDR" },
         new FlagTranslate { ID = "LV", name = "Letonia" },
         new FlagTranslate { ID = "LB", name = "Líbano" },
         new FlagTranslate { ID = "LS", name = "Lesoto" },
         new FlagTranslate { ID = "LR", name = "Liberia" },
         new FlagTranslate { ID = "LY", name = "Libia" },
         new FlagTranslate { ID = "LI", name = "Liechtenstein" },
         new FlagTranslate { ID = "LT", name = "Lituania" },
         new FlagTranslate { ID = "Luxemburgo", name = "LU de" },
         new FlagTranslate { ID = "MK", name = "Macedonia, República de" },
         new FlagTranslate { ID = "MG", name = "Madagascar" },
         new FlagTranslate { ID = "MW", name = "Malawi" },
         new FlagTranslate { ID = "MI", name = "Malasia" },
         new FlagTranslate { ID = "MV", name = "Maldivas" },
         new FlagTranslate { ID = "ML", name = "Malí" },
         new FlagTranslate { ID = "MT", name = "Malta" },
         new FlagTranslate { ID = "MH", name = "Islas Marshall" },
         new FlagTranslate { ID = "MQ", name = "Martinica" },
         new FlagTranslate { ID = "MR", name = "Mauritania" },
         new FlagTranslate { ID = "MU", name = "Mauricio" },
         new FlagTranslate { ID = "YT", name = "Mayotte" },
         new FlagTranslate { ID = "MX", name = "México" },
         new FlagTranslate { ID = "FM", name = "Micronesia, Estados Federados de" },
         new FlagTranslate { ID = "MD", name = "Moldavia" },
         new FlagTranslate { ID = "MC", name = "Mónaco" },
         new FlagTranslate { ID = "MN", name = "Mongolia" },
         new FlagTranslate { ID = "ME", name = "Montenegro" },
         new FlagTranslate { ID = "MS", name = "Montserrat" },
         new FlagTranslate { ID = "MA", name = "Marruecos" },
         new FlagTranslate { ID = "MZ", name = "Mozambique" },
         new FlagTranslate { ID = "MM", name = "Myanmar" },
         new FlagTranslate { ID = "NA", name = "Namibia" },
         new FlagTranslate { ID = "NR", name = "Nauru" },
         new FlagTranslate { ID = "NP", name = "Nepal" },
         new FlagTranslate { ID = "NL", name = "Holanda" },
         new FlagTranslate { ID = "AN", name = "Antillas Holandesas" },
         new FlagTranslate { ID = "NC", name = "Nueva Caledonia" },
         new FlagTranslate { ID = "NZ", name = "Nueva Zelanda" },
         new FlagTranslate { ID = "NI", name = "Nicaragua" },
         new FlagTranslate { ID = "NE", name = "Níger" },
         new FlagTranslate { ID = "NG", name = "Nigeria" },
         new FlagTranslate { ID = "NU", name = "Niue" },
         new FlagTranslate { ID = "NF", name = "Isla Norfolk" },
         new FlagTranslate { ID = "Norte", name = "Diputado de las Islas Marianas del" },
         new FlagTranslate { ID = "NO", name = "Noruega" },
         new FlagTranslate { ID = "OM", name = "Omán" },
         new FlagTranslate { ID = "PK", name = "Pakistán" },
         new FlagTranslate { ID = "PW", name = "Palau" },
         new FlagTranslate { ID = "PS", name = "Territorio Palestino" },
         new FlagTranslate { ID = "PA", name = "Panamá" },
         new FlagTranslate { ID = "PG", name = "Papua Nueva Guinea" },
         new FlagTranslate { ID = "PY", name = "Paraguay" },
         new FlagTranslate { ID = "PE", name = "Perú" },
         new FlagTranslate { ID = "PH", name = "Filipinas" },
         new FlagTranslate { ID = "Pitcairn", name = "PN" },
         new FlagTranslate { ID = "PL", name = "Polonia" },
         new FlagTranslate { ID = "PT", name = "Portugal" },
         new FlagTranslate { ID = "PR", name = "Puerto Rico" },
         new FlagTranslate { ID = "QA", name = "Qatar" },
         new FlagTranslate { ID = "RE", name = "Reunión" },
         new FlagTranslate { ID = "RO", name = "Rumanía" },
         new FlagTranslate { ID = "RU", name = "Federación de Rusia" },
         new FlagTranslate { ID = "RW", name = "Ruanda" },
         new FlagTranslate { ID = "BL", name = "San Bartolomé" },
         new FlagTranslate { ID = "SH", name = "Santa Elena" },
         new FlagTranslate { ID = "KN", name = "Saint Kitts y Nevis" },
         new FlagTranslate { ID = "LC", name = "Santa Lucía" },
         new FlagTranslate { ID = "MF", name = "Saint-Martin (parte francesa)" },
         new FlagTranslate { ID = "PM", name = "San Pedro y Miquelón" },
         new FlagTranslate { ID = "VC", name = "San Vicente y las Granadinas" },
         new FlagTranslate { ID = "WS", name = "Samoa" },
         new FlagTranslate { ID = "SM", name = "San Marino" },
         new FlagTranslate { ID = "ST", name = "Santo Tomé y Príncipe" },
         new FlagTranslate { ID = "SA", name = "Arabia Saudita" },
         new FlagTranslate { ID = "SN", name = "Senegal" },
         new FlagTranslate { ID = "RS", name = "Serbia" },
         new FlagTranslate { ID = "SC", name = "Seychelles" },
         new FlagTranslate { ID = "SL", name = "Sierra Leona" },
         new FlagTranslate { ID = "SG", name = "Singapur" },
         new FlagTranslate { ID = "SK", name = "Eslovaquia" },
         new FlagTranslate { ID = "SI", name = "Eslovenia" },
         new FlagTranslate { ID = "SB", name = "Islas Salomón" },
         new FlagTranslate { ID = "SO", name = "Somalia" },
         new FlagTranslate { ID = "ZA", name = "Sudáfrica" },
         new FlagTranslate { ID = "GS", name = "Georgia del Sur y las Islas Sandwich del Sur" },
         new FlagTranslate { ID = "SS", name = "Sudán del Sur" },
         new FlagTranslate { ID = "ES", name = "España" },
         new FlagTranslate { ID = "LK", name = "Sri Lanka" },
         new FlagTranslate { ID = "SD", name = "Sudán" },
         new FlagTranslate { ID = "SR", name = "Surinam" },
         new FlagTranslate { ID = "SJ", name = "Islas Svalbard y Jan Mayen" },
         new FlagTranslate { ID = "SZ", name = "Swazilandia" },
         new FlagTranslate { ID = "SE", name = "Suecia" },
         new FlagTranslate { ID = "CH", name = "Suiza" },
         new FlagTranslate { ID = "SY", name = "República Árabe Siria (Siria)" },
         new FlagTranslate { ID = "TW", name = "Taiwán, República de China" },
         new FlagTranslate { ID = "TJ", name = "Tayikistán" },
         new FlagTranslate { ID = "TZ", name = "Tanzania, República Unida de" },
         new FlagTranslate { ID = "TH", name = "Tailandia" },
         new FlagTranslate { ID = "TL", name = "Timor-Leste" },
         new FlagTranslate { ID = "TG", name = "Togo" },
         new FlagTranslate { ID = "TK", name = "Tokelau" },
         new FlagTranslate { ID = "TO", name = "Tonga" },
         new FlagTranslate { ID = "TT", name = "Trinidad y Tobago" },
         new FlagTranslate { ID = "TN", name = "Túnez" },
         new FlagTranslate { ID = "TR", name = "Turquía" },
         new FlagTranslate { ID = "TM", name = "Turkmenistán" },
         new FlagTranslate { ID = "TC", name = "Islas Turcas y Caicos" },
         new FlagTranslate { ID = "TV", name = "Tuvalu" },
         new FlagTranslate { ID = "UG", name = "Uganda" },
         new FlagTranslate { ID = "UA", name = "Ucrania" },
         new FlagTranslate { ID = "AE", name = "Emiratos Árabes Unidos" },
         new FlagTranslate { ID = "GB", name = "Reino Unido" },
         new FlagTranslate { ID = "UU.", name = "Estados Unidos de América EE." },
         new FlagTranslate { ID = "UM", name = "Islas menores alejadas de EE. UU." },
         new FlagTranslate { ID = "UY", name = "Uruguay" },
         new FlagTranslate { ID = "UZ", name = "Uzbekistán" },
         new FlagTranslate { ID = "VU", name = "Vanuatu" },
         new FlagTranslate { ID = "VE", name = "Venezuela (República Bolivariana)" },
         new FlagTranslate { ID = "VN", name = "Vietnam" },
         new FlagTranslate { ID = "VI", name = "Islas Vírgenes, EE. UU." },
         new FlagTranslate { ID = "WF", name = "Islas Wallis y Futuna" },
         new FlagTranslate { ID = "EH", name = "Sáhara Occidental" },
         new FlagTranslate { ID = "YE", name = "Yemen" },
         new FlagTranslate { ID = "ZM", name = "Zambia" },
         new FlagTranslate { ID = "ZW", name = "Zimbabwe" },
         new FlagTranslate { ID = "YE", name = "Yemen" },
         new FlagTranslate { ID = "ZM", name = "Zambia" },
         new FlagTranslate { ID = "ZW", name = "Zimbabwe" }
};
}

