using System.Collections.Generic;
using UnityEngine;
using static Constants;

public class FlagsManager : MonoBehaviour
{
    public static FlagsManager Manager;

    #region Basic Events
    void Awake()
    {
        Manager = this;
        DontDestroyOnLoad(gameObject);
    }

    private void Start()
    {
        Flags.RemoveAll(s => s.sprite == null);

        for (int i = 0; i < Flags.Count; i++)
        {
            Flags[i].ID = i;
        }
    }
    #endregion

    public void ChangeFlagsPack()
    {
        //if (UITexts.selectedLanguage == UITexts.en)
        //    selectedFlagList = world_EN; 
        //if (UITexts.selectedLanguage == UITexts.ro)
        //    selectedFlagList = world_RO;

        //if (UITexts.selectedLanguage == UITexts.fr)
        //    selectedFlagList = world_FR;

        //if (UITexts.selectedLanguage == UITexts.es)
        //    selectedFlagList = world_ES;
    }

    public List<Flag> Flags = new List<Flag>()
    {
         new Flag { abbrev = "AF", name = "Afghanistan" },
         new Flag { abbrev = "AX", name = "Aland Islands" },
         new Flag { abbrev = "AL", name = "Albania" },
         new Flag { abbrev = "DZ", name = "Algeria" },
         new Flag { abbrev = "AS", name = "American Samoa" },
         new Flag { abbrev = "AD", name = "Andorra" },
         new Flag { abbrev = "AO", name = "Angola" },
         new Flag { abbrev = "AI", name = "Anguilla" },
         new Flag { abbrev = "AQ", name = "Antarctica" },
         new Flag { abbrev = "AG", name = "Antigua and Barbuda" },
         new Flag { abbrev = "AR", name = "Argentina" },
         new Flag { abbrev = "AM", name = "Armenia" },
         new Flag { abbrev = "AW", name = "Aruba" },
         new Flag { abbrev = "AU", name = "Australia" },
         new Flag { abbrev = "AT", name = "Austria" },
         new Flag { abbrev = "AZ", name = "Azerbaijan" },
         new Flag { abbrev = "BS", name = "Bahamas" },
         new Flag { abbrev = "BH", name = "Bahrain" },
         new Flag { abbrev = "BD", name = "Bangladesh" },
         new Flag { abbrev = "BB", name = "Barbados" },
         new Flag { abbrev = "BY", name = "Belarus" },
         new Flag { abbrev = "BE", name = "Belgium" },
         new Flag { abbrev = "BZ", name = "Belize" },
         new Flag { abbrev = "BJ", name = "Benin" },
         new Flag { abbrev = "BM", name = "Bermuda" },
         new Flag { abbrev = "BT", name = "Bhutan" },
         new Flag { abbrev = "BO", name = "Bolivia" },
         new Flag { abbrev = "BA", name = "Bosnia and Herzegovina" },
         new Flag { abbrev = "BW", name = "Botswana" },
         new Flag { abbrev = "BV", name = "Bouvet Island" },
         new Flag { abbrev = "BR", name = "Brazil" },
         new Flag { abbrev = "VG", name = "British Virgin Islands" },
         new Flag { abbrev = "IO", name = "British Indian Ocean Territory" },
         new Flag { abbrev = "BN", name = "Brunei Darussalam" },
         new Flag { abbrev = "BG", name = "Bulgaria" },
         new Flag { abbrev = "BF", name = "Burkina Faso" },
         new Flag { abbrev = "BI", name = "Burundi" },
         new Flag { abbrev = "KH", name = "Cambodia" },
         new Flag { abbrev = "CM", name = "Cameroon" },
         new Flag { abbrev = "CA", name = "Canada" },
         new Flag { abbrev = "CV", name = "Cape Verde" },
         new Flag { abbrev = "KY", name = "Cayman Islands" },
         new Flag { abbrev = "CF", name = "Central African Republic" },
         new Flag { abbrev = "TD", name = "Chad" },
         new Flag { abbrev = "CL", name = "Chile" },
         new Flag { abbrev = "CN", name = "China" },
         new Flag { abbrev = "HK", name = "Hong Kong, SAR China" },
         new Flag { abbrev = "MO", name = "Macao, SAR China" },
         new Flag { abbrev = "CX", name = "Christmas Island" },
         new Flag { abbrev = "CC", name = "Cocos (Keeling) Islands" },
         new Flag { abbrev = "CO", name = "Colombia" },
         new Flag { abbrev = "KM", name = "Comoros" },
         new Flag { abbrev = "CG", name = "Congo (Brazzaville)" },
         new Flag { abbrev = "CD", name = "Congo, (Kinshasa)" },
         new Flag { abbrev = "CK", name = "Cook Islands" },
         new Flag { abbrev = "CR", name = "Costa Rica" },
         new Flag { abbrev = "CI", name = "Côte d'Ivoire" },
         new Flag { abbrev = "HR", name = "Croatia" },
         new Flag { abbrev = "CU", name = "Cuba" },
         new Flag { abbrev = "CY", name = "Cyprus" },
         new Flag { abbrev = "CZ", name = "Czech Republic" },
         new Flag { abbrev = "DK", name = "Denmark" },
         new Flag { abbrev = "DJ", name = "Djibouti" },
         new Flag { abbrev = "DM", name = "Dominica" },
         new Flag { abbrev = "DO", name = "Dominican Republic" },
         new Flag { abbrev = "EC", name = "Ecuador" },
         new Flag { abbrev = "EG", name = "Egypt" },
         new Flag { abbrev = "SV", name = "El Salvador" },
         new Flag { abbrev = "GQ", name = "Equatorial Guinea" },
         new Flag { abbrev = "ER", name = "Eritrea" },
         new Flag { abbrev = "EE", name = "Estonia" },
         new Flag { abbrev = "ET", name = "Ethiopia" },
         new Flag { abbrev = "FK", name = "Falkland Islands (Malvinas)" },
         new Flag { abbrev = "FO", name = "Faroe Islands" },
         new Flag { abbrev = "FJ", name = "Fiji" },
         new Flag { abbrev = "FI", name = "Finland" },
         new Flag { abbrev = "FR", name = "France" },
         new Flag { abbrev = "GF", name = "French Guiana" },
         new Flag { abbrev = "PF", name = "French Polynesia" },
         new Flag { abbrev = "TF", name = "French Southern Territories" },
         new Flag { abbrev = "GA", name = "Gabon" },
         new Flag { abbrev = "GM", name = "Gambia" },
         new Flag { abbrev = "GE", name = "Georgia" },
         new Flag { abbrev = "DE", name = "Germany" },
         new Flag { abbrev = "GH", name = "Ghana" },
         new Flag { abbrev = "GI", name = "Gibraltar" },
         new Flag { abbrev = "GR", name = "Greece" },
         new Flag { abbrev = "GL", name = "Greenland" },
         new Flag { abbrev = "GD", name = "Grenada" },
         new Flag { abbrev = "GP", name = "Guadeloupe" },
         new Flag { abbrev = "GU", name = "Guam" },
         new Flag { abbrev = "GT", name = "Guatemala" },
         new Flag { abbrev = "GG", name = "Guernsey" },
         new Flag { abbrev = "GN", name = "Guinea" },
         new Flag { abbrev = "GW", name = "Guinea-Bissau" },
         new Flag { abbrev = "GY", name = "Guyana" },
         new Flag { abbrev = "HT", name = "Haiti" },
         new Flag { abbrev = "HM", name = "Heard and Mcdonald Islands" },
         new Flag { abbrev = "VA", name = "Holy See (Vatican City State)" },
         new Flag { abbrev = "HN", name = "Honduras" },
         new Flag { abbrev = "HU", name = "Hungary" },
         new Flag { abbrev = "IS", name = "Iceland" },
         new Flag { abbrev = "IN", name = "India" },
         new Flag { abbrev = "ID", name = "Indonesia" },
         new Flag { abbrev = "IR", name = "Iran, Islamic Republic of" },
         new Flag { abbrev = "IQ", name = "Iraq" },
         new Flag { abbrev = "IE", name = "Ireland" },
         new Flag { abbrev = "IM", name = "Isle of Man" },
         new Flag { abbrev = "IL", name = "Israel" },
         new Flag { abbrev = "IT", name = "Italy" },
         new Flag { abbrev = "JM", name = "Jamaica" },
         new Flag { abbrev = "JP", name = "Japan" },
         new Flag { abbrev = "JE", name = "Jersey" },
         new Flag { abbrev = "JO", name = "Jordan" },
         new Flag { abbrev = "KZ", name = "Kazakhstan" },
         new Flag { abbrev = "KE", name = "Kenya" },
         new Flag { abbrev = "KI", name = "Kiribati" },
         new Flag { abbrev = "KP", name = "Korea (North)" },
         new Flag { abbrev = "KR", name = "Korea (South)" },
         new Flag { abbrev = "KW", name = "Kuwait" },
         new Flag { abbrev = "KG", name = "Kyrgyzstan" },
         new Flag { abbrev = "LA", name = "Lao PDR" },
         new Flag { abbrev = "LV", name = "Latvia" },
         new Flag { abbrev = "LB", name = "Lebanon" },
         new Flag { abbrev = "LS", name = "Lesotho" },
         new Flag { abbrev = "LR", name = "Liberia" },
         new Flag { abbrev = "LY", name = "Libya" },
         new Flag { abbrev = "LI", name = "Liechtenstein" },
         new Flag { abbrev = "LT", name = "Lithuania" },
         new Flag { abbrev = "LU", name = "Luxembourg" },
         new Flag { abbrev = "MK", name = "Macedonia, Republic of" },
         new Flag { abbrev = "MG", name = "Madagascar" },
         new Flag { abbrev = "MW", name = "Malawi" },
         new Flag { abbrev = "MY", name = "Malaysia" },
         new Flag { abbrev = "MV", name = "Maldives" },
         new Flag { abbrev = "ML", name = "Mali" },
         new Flag { abbrev = "MT", name = "Malta" },
         new Flag { abbrev = "MH", name = "Marshall Islands" },
         new Flag { abbrev = "MQ", name = "Martinique" },
         new Flag { abbrev = "MR", name = "Mauritania" },
         new Flag { abbrev = "MU", name = "Mauritius" },
         new Flag { abbrev = "YT", name = "Mayotte" },
         new Flag { abbrev = "MX", name = "Mexico" },
         new Flag { abbrev = "FM", name = "Micronesia, Federated States of" },
         new Flag { abbrev = "MD", name = "Moldova" },
         new Flag { abbrev = "MC", name = "Monaco" },
         new Flag { abbrev = "MN", name = "Mongolia" },
         new Flag { abbrev = "ME", name = "Montenegro" },
         new Flag { abbrev = "MS", name = "Montserrat" },
         new Flag { abbrev = "MA", name = "Morocco" },
         new Flag { abbrev = "MZ", name = "Mozambique" },
         new Flag { abbrev = "MM", name = "Myanmar" },
         new Flag { abbrev = "NA", name = "Namibia" },
         new Flag { abbrev = "NR", name = "Nauru" },
         new Flag { abbrev = "NP", name = "Nepal" },
         new Flag { abbrev = "NL", name = "Netherlands" },
         new Flag { abbrev = "AN", name = "Netherlands Antilles" },
         new Flag { abbrev = "NC", name = "New Caledonia" },
         new Flag { abbrev = "NZ", name = "New Zealand" },
         new Flag { abbrev = "NI", name = "Nicaragua" },
         new Flag { abbrev = "NE", name = "Niger" },
         new Flag { abbrev = "NG", name = "Nigeria" },
         new Flag { abbrev = "NU", name = "Niue" },
         new Flag { abbrev = "NF", name = "Norfolk Island" },
         new Flag { abbrev = "MP", name = "Northern Mariana Islands" },
         new Flag { abbrev = "NO", name = "Norway" },
         new Flag { abbrev = "OM", name = "Oman" },
         new Flag { abbrev = "PK", name = "Pakistan" },
         new Flag { abbrev = "PW", name = "Palau" },
         new Flag { abbrev = "PS", name = "Palestinian Territory" },
         new Flag { abbrev = "PA", name = "Panama" },
         new Flag { abbrev = "PG", name = "Papua New Guinea" },
         new Flag { abbrev = "PY", name = "Paraguay" },
         new Flag { abbrev = "PE", name = "Peru" },
         new Flag { abbrev = "PH", name = "Philippines" },
         new Flag { abbrev = "PN", name = "Pitcairn" },
         new Flag { abbrev = "PL", name = "Poland" },
         new Flag { abbrev = "PT", name = "Portugal" },
         new Flag { abbrev = "PR", name = "Puerto Rico" },
         new Flag { abbrev = "QA", name = "Qatar" },
         new Flag { abbrev = "RE", name = "Réunion" },
         new Flag { abbrev = "RO", name = "Romania"},
         new Flag { abbrev = "RU", name = "Russian Federation" },
         new Flag { abbrev = "RW", name = "Rwanda" },
         new Flag { abbrev = "BL", name = "Saint-Barthélemy" },
         new Flag { abbrev = "SH", name = "Saint Helena" },
         new Flag { abbrev = "KN", name = "Saint Kitts and Nevis" },
         new Flag { abbrev = "LC", name = "Saint Lucia" },
         new Flag { abbrev = "MF", name = "Saint-Martin (French part)" },
         new Flag { abbrev = "PM", name = "Saint Pierre and Miquelon" },
         new Flag { abbrev = "VC", name = "Saint Vincent and Grenadines" },
         new Flag { abbrev = "WS", name = "Samoa" },
         new Flag { abbrev = "SM", name = "San Marino" },
         new Flag { abbrev = "ST", name = "Sao Tome and Principe" },
         new Flag { abbrev = "SA", name = "Saudi Arabia" },
         new Flag { abbrev = "SN", name = "Senegal" },
         new Flag { abbrev = "RS", name = "Serbia" },
         new Flag { abbrev = "SC", name = "Seychelles" },
         new Flag { abbrev = "SL", name = "Sierra Leone" },
         new Flag { abbrev = "SG", name = "Singapore" },
         new Flag { abbrev = "SK", name = "Slovakia" },
         new Flag { abbrev = "SI", name = "Slovenia" },
         new Flag { abbrev = "SB", name = "Solomon Islands" },
         new Flag { abbrev = "SO", name = "Somalia" },
         new Flag { abbrev = "ZA", name = "South Africa" },
         new Flag { abbrev = "GS", name = "South Georgia and the South Sandwich Islands" },
         new Flag { abbrev = "SS", name = "South Sudan" },
         new Flag { abbrev = "ES", name = "Spain" },
         new Flag { abbrev = "LK", name = "Sri Lanka" },
         new Flag { abbrev = "SD", name = "Sudan" },
         new Flag { abbrev = "SR", name = "Suriname" },
         new Flag { abbrev = "SJ", name = "Svalbard and Jan Mayen Islands" },
         new Flag { abbrev = "SZ", name = "Swaziland" },
         new Flag { abbrev = "SE", name = "Sweden" },
         new Flag { abbrev = "CH", name = "Switzerland" },
         new Flag { abbrev = "SY", name = "Syrian Arab Republic (Syria)" },
         new Flag { abbrev = "TW", name = "Taiwan, Republic of China" },
         new Flag { abbrev = "TJ", name = "Tajikistan" },
         new Flag { abbrev = "TZ", name = "Tanzania, United Republic of" },
         new Flag { abbrev = "TH", name = "Thailand" },
         new Flag { abbrev = "TL", name = "Timor-Leste" },
         new Flag { abbrev = "TG", name = "Togo" },
         new Flag { abbrev = "TK", name = "Tokelau" },
         new Flag { abbrev = "TO", name = "Tonga" },
         new Flag { abbrev = "TT", name = "Trinidad and Tobago" },
         new Flag { abbrev = "TN", name = "Tunisia" },
         new Flag { abbrev = "TR", name = "Turkey" },
         new Flag { abbrev = "TM", name = "Turkmenistan" },
         new Flag { abbrev = "TC", name = "Turks and Caicos Islands" },
         new Flag { abbrev = "TV", name = "Tuvalu" },
         new Flag { abbrev = "UG", name = "Uganda" },
         new Flag { abbrev = "UA", name = "Ukraine" },
         new Flag { abbrev = "AE", name = "United Arab Emirates" },
         new Flag { abbrev = "GB", name = "United Kingdom" },
         new Flag { abbrev = "US", name = "United States of America" },
         new Flag { abbrev = "UM", name = "US Minor Outlying Islands" },
         new Flag { abbrev = "UY", name = "Uruguay" },
         new Flag { abbrev = "UZ", name = "Uzbekistan" },
         new Flag { abbrev = "VU", name = "Vanuatu" },
         new Flag { abbrev = "VE", name = "Venezuela (Bolivarian Republic)" },
         new Flag { abbrev = "VN", name = "Viet Nam" },
         new Flag { abbrev = "VI", name = "Virgin Islands, US" },
         new Flag { abbrev = "WF", name = "Wallis and Futuna Islands" },
         new Flag { abbrev = "EH", name = "Western Sahara" },
         new Flag { abbrev = "YE", name = "Yemen" },
         new Flag { abbrev = "ZM", name = "Zambia" },
         new Flag { abbrev = "ZW", name = "Zimbabwe" },
         new Flag { abbrev = "YE", name = "Yemen" },
         new Flag { abbrev = "ZM", name = "Zambia" },
         new Flag { abbrev = "ZW", name = "Zimbabwe" }
    };

    public static List<Flag> world_RO = new List<Flag>()
    {
         new Flag { abbrev = "AF", name = "Afganistan" },
         new Flag { abbrev = "AX", name = "Insulele Aland" },
         new Flag { abbrev = "AL", name = "Albania" },
         new Flag { abbrev = "DZ", name = "Algeria" },
         new Flag { abbrev = "AS", name = "Samoa Americană" },
         new Flag { abbrev = "AD", name = "Andorra" },
         new Flag { abbrev = "AO", name = "Angola" },
         new Flag { abbrev = "AI", name = "Anguilla" },
         new Flag { abbrev = "AQ", name = "Antarctica" },
         new Flag { abbrev = "AG", name = "Antigua și Barbuda" },
         new Flag { abbrev = "AR", name = "Argentina" },
         new Flag { abbrev = "AM", name = "Armenia" },
         new Flag { abbrev = "AW", name = "Aruba" },
         new Flag { abbrev = "AU", name = "Australia" },
         new Flag { abbrev = "AT", name = "Austria" },
         new Flag { abbrev = "AZ", name = "Azerbaidjan" },
         new Flag { abbrev = "BS", name = "Bahamas" },
         new Flag { abbrev = "BH", name = "Bahrain" },
         new Flag { abbrev = "BD", name = "Bangladesh" },
         new Flag { abbrev = "BB", name = "Barbados" },
         new Flag { abbrev = "BY", name = "Belarus" },
         new Flag { abbrev = "BE", name = "Belgia" },
         new Flag { abbrev = "BZ", name = "Belize" },
         new Flag { abbrev = "BJ", name = "Benin" },
         new Flag { abbrev = "BM", name = "Bermuda" },
         new Flag { abbrev = "BT", name = "Bhutan" },
         new Flag { abbrev = "BO", name = "Bolivia" },
         new Flag { abbrev = "BA", name = "Bosnia și Herțegovina" },
         new Flag { abbrev = "BW", name = "Botswana" },
         new Flag { abbrev = "BV", name = "Insula Bouvet" },
         new Flag { abbrev = "BR", name = "Brazilia" },
         new Flag { abbrev = "VG", name = "Insulele Virgine Britanice" },
         new Flag { abbrev = "IO", name = "Teritoriul britanic din Oceanul Indian" },
         new Flag { abbrev = "BN", name = "Brunei Darussalam" },
         new Flag { abbrev = "BG", name = "Bulgaria" },
         new Flag { abbrev = "BF", name = "Burkina Faso" },
         new Flag { abbrev = "BI", name = "Burundi" },
         new Flag { abbrev = "KH", name = "Cambodgia" },
         new Flag { abbrev = "CM", name = "Camerun" },
         new Flag { abbrev = "CA", name = "Canada" },
         new Flag { abbrev = "Verde", name = "CV-ul Capului" },
         new Flag { abbrev = "KY", name = "Insulele Cayman" },
         new Flag { abbrev = "CF", name = "Republica Centrafricană" },
         new Flag { abbrev = "TD", name = "Ciad" },
         new Flag { abbrev = "CL", name = "Chile" },
         new Flag { abbrev = "CN", name = "China" },
         new Flag { abbrev = "HK", name = "Hong Kong, SAR China" },
         new Flag { abbrev = "MO", name = "Macao, SAR China" },
         new Flag { abbrev = "CX", name = "Insula Crăciunului" },
         new Flag { abbrev = "CC", name = "Insulele Cocos (Keeling)" },
         new Flag { abbrev = "CO", name = "Columbia" },
         new Flag { abbrev = "KM", name = "Comore" },
         new Flag { abbrev = "CG", name = "Congo (Brazzaville)" },
         new Flag { abbrev = "CD", name = "Congo, (Kinshasa)" },
         new Flag { abbrev = "CK", name = "Insulele Cook" },
         new Flag { abbrev = "CR", name = "Costa Rica" },
         new Flag { abbrev = "CI", name = "Côte d'Ivoire" },
         new Flag { abbrev = "HR", name = "Croația" },
         new Flag { abbrev = "CU", name = "Cuba" },
         new Flag { abbrev = "CY", name = "Cipru" },
         new Flag { abbrev = "CZ", name = "Republica Cehă" },
         new Flag { abbrev = "DK", name = "Danemarca" },
         new Flag { abbrev = "DJ", name = "Djibouti" },
         new Flag { abbrev = "DM", name = "Dominica" },
         new Flag { abbrev = "DO", name = "Republica Dominicană" },
         new Flag { abbrev = "CE", name = "Ecuador" },
         new Flag { abbrev = "EG", name = "Egipt" },
         new Flag { abbrev = "SV", name = "El Salvador" },
         new Flag { abbrev = "Ecuatorială", name = "GQ Guineea" },
         new Flag { abbrev = "ER", name = "Eritrea" },
         new Flag { abbrev = "EE", name = "Estonia" },
         new Flag { abbrev = "ET", name = "Etiopia" },
         new Flag { abbrev = "FK", name = "Insulele Falkland (Malvinas)" },
         new Flag { abbrev = "FO", name = "Insulele Feroe" },
         new Flag { abbrev = "FJ", name = "Fiji" },
         new Flag { abbrev = "FI", name = "Finlanda" },
         new Flag { abbrev = "FR", name = "Franța" },
         new Flag { abbrev = "GF", name = "Guyana Franceză" },
         new Flag { abbrev = "PF", name = "Polinezia Franceză" },
         new Flag { abbrev = "TF", name = "Teritoriile sudice franceze" },
         new Flag { abbrev = "GA", name = "Gabon" },
         new Flag { abbrev = "GM", name = "Gambia" },
         new Flag { abbrev = "GE", name = "Georgia" },
         new Flag { abbrev = "DE", name = "Germania" },
         new Flag { abbrev = "GH", name = "Ghana" },
         new Flag { abbrev = "GI", name = "Gibraltar" },
         new Flag { abbrev = "GR", name = "Grecia" },
         new Flag { abbrev = "GL", name = "Groenlanda" },
         new Flag { abbrev = "GD", name = "Grenada" },
         new Flag { abbrev = "GP", name = "Guadalupe" },
         new Flag { abbrev = "GU", name = "Guam" },
         new Flag { abbrev = "GT", name = "Guatemala" },
         new Flag { abbrev = "GG", name = "Guernsey" },
         new Flag { abbrev = "GN", name = "Guineea" },
         new Flag { abbrev = "GW", name = "Guinea-Bissau" },
         new Flag { abbrev = "GY", name = "Guyana" },
         new Flag { abbrev = "HT", name = "Haiti" },
         new Flag { abbrev = "HM", name = "Heard și Insulele Mcdonald" },
         new Flag { abbrev = "VA", name = "Sfântul Scaun (Statul Vatican)" },
         new Flag { abbrev = "HN", name = "Honduras" },
         new Flag { abbrev = "HU", name = "Ungaria" },
         new Flag { abbrev = "ESTE", name = "Islanda" },
         new Flag { abbrev = "IN", name = "India" },
         new Flag { abbrev = "Indoneziei", name = "ID-ul" },
         new Flag { abbrev = "IR", name = "Iran, Republica Islamică" },
         new Flag { abbrev = "IQ", name = "Irak" },
         new Flag { abbrev = "IE", name = "Irlanda" },
         new Flag { abbrev = "IM", name = "Isle of Man" },
         new Flag { abbrev = "IL", name = "Israel" },
         new Flag { abbrev = "IT", name = "Italia" },
         new Flag { abbrev = "JM", name = "Jamaica" },
         new Flag { abbrev = "JP", name = "Japonia" },
         new Flag { abbrev = "JE", name = "Jersey" },
         new Flag { abbrev = "JO", name = "Jordan" },
         new Flag { abbrev = "KZ", name = "Kazahstan" },
         new Flag { abbrev = "KE", name = "Kenya" },
         new Flag { abbrev = "KI", name = "Kiribati" },
         new Flag { abbrev = "(KP)", name = "Coreea de Nord" },
         new Flag { abbrev = "KR", name = "Coreea (Sud)" },
         new Flag { abbrev = "KW", name = "Kuweit" },
         new Flag { abbrev = "KG", name = "Kârgâzstan" },
         new Flag { abbrev = "LA", name = "Lao PDR" },
         new Flag { abbrev = "LV", name = "Letonia" },
         new Flag { abbrev = "LB", name = "Liban" },
         new Flag { abbrev = "LS", name = "Lesotho" },
         new Flag { abbrev = "LR", name = "Liberia" },
         new Flag { abbrev = "LY", name = "Libia" },
         new Flag { abbrev = "LI", name = "Liechtenstein" },
         new Flag { abbrev = "LT", name = "Lituania" },
         new Flag { abbrev = "LU", name = "Luxemburg" },
         new Flag { abbrev = "MK", name = "Macedonia, Republica" },
         new Flag { abbrev = "MG", name = "Madagascar" },
         new Flag { abbrev = "MW", name = "Malawi" },
         new Flag { abbrev = "MY", name = "Malaysia" },
         new Flag { abbrev = "MV", name = "Maldive" },
         new Flag { abbrev = "ML", name = "Mali" },
         new Flag { abbrev = "MT", name = "Malta" },
         new Flag { abbrev = "MH", name = "Insulele Marshall" },
         new Flag { abbrev = "MQ", name = "Martinica" },
         new Flag { abbrev = "MR", name = "Mauritania" },
         new Flag { abbrev = "MU", name = "Mauritius" },
         new Flag { abbrev = "YT", name = "Mayotte" },
         new Flag { abbrev = "MX", name = "Mexic" },
         new Flag { abbrev = "FM", name = "Micronezia, Statele Federate ale" },
         new Flag { abbrev = "MD", name = "Moldova" },
         new Flag { abbrev = "MC", name = "Monaco" },
         new Flag { abbrev = "MN", name = "Mongolia" },
         new Flag { abbrev = "ME", name = "Muntenegru" },
         new Flag { abbrev = "MS", name = "Montserrat" },
         new Flag { abbrev = "MA", name = "Maroc" },
         new Flag { abbrev = "MZ", name = "Mozambic" },
         new Flag { abbrev = "MM", name = "Myanmar" },
         new Flag { abbrev = "NA", name = "Namibia" },
         new Flag { abbrev = "NR", name = "Nauru" },
         new Flag { abbrev = "NP", name = "Nepal" },
         new Flag { abbrev = "NL", name = "Olanda" },
         new Flag { abbrev = "AN", name = "Antilele Olandeze" },
         new Flag { abbrev = "NC", name = "Noua Caledonie" },
         new Flag { abbrev = "NZ", name = "Noua Zeelandă" },
         new Flag { abbrev = "NI", name = "Nicaragua" },
         new Flag { abbrev = "NE", name = "Niger" },
         new Flag { abbrev = "NG", name = "Nigeria" },
         new Flag { abbrev = "NU", name = "Niue" },
         new Flag { abbrev = "NF", name = "Insula Norfolk" },
         new Flag { abbrev = "MP", name = "Insulele Marianelor de Nord" },
         new Flag { abbrev = "NU", name = "Norvegia" },
         new Flag { abbrev = "OM", name = "Oman" },
         new Flag { abbrev = "PK", name = "Pakistan" },
         new Flag { abbrev = "PW", name = "Palau" },
         new Flag { abbrev = "PS", name = "Teritoriul Palestinian" },
         new Flag { abbrev = "PA", name = "Panama" },
         new Flag { abbrev = "PG", name = "Papua Noua Guinee" },
         new Flag { abbrev = "PY", name = "Paraguay" },
         new Flag { abbrev = "PE", name = "Peru" },
         new Flag { abbrev = "PH", name = "Filipine" },
         new Flag { abbrev = "PN", name = "Pitcairn" },
         new Flag { abbrev = "PL", name = "Polonia" },
         new Flag { abbrev = "PT", name = "Portugalia" },
         new Flag { abbrev = "PR", name = "Puerto Rico" },
         new Flag { abbrev = "QA", name = "Qatar" },
         new Flag { abbrev = "RE", name = "Reuniunea" },
         new Flag { abbrev = "RO", name = "Romania" },
         new Flag { abbrev = "RU", name = "Federația Rusă" },
         new Flag { abbrev = "RW", name = "Rwanda" },
         new Flag { abbrev = "BL", name = "Saint-Barthélemy" },
         new Flag { abbrev = "SH", name = "Sfânta Elena" },
         new Flag { abbrev = "KN", name = "Saint Kitts și Nevis" },
         new Flag { abbrev = "LC", name = "Sfânta Lucia" },
         new Flag { abbrev = "MF", name = "Saint-Martin (partea franceză)" },
         new Flag { abbrev = "PM", name = "Saint Pierre și Miquelon" },
         new Flag { abbrev = "VC", name = "Saint Vincent și Grenadine" },
         new Flag { abbrev = "WS", name = "Samoa" },
         new Flag { abbrev = "SM", name = "San Marino" },
         new Flag { abbrev = "ST", name = "Sao Tome și Principe" },
         new Flag { abbrev = "SA", name = "Arabia Saudită" },
         new Flag { abbrev = "SN", name = "Senegal" },
         new Flag { abbrev = "RS", name = "Serbia" },
         new Flag { abbrev = "SC", name = "Seychelles" },
         new Flag { abbrev = "SL", name = "Sierra Leone" },
         new Flag { abbrev = "SG", name = "Singapore" },
         new Flag { abbrev = "SK", name = "Slovacia" },
         new Flag { abbrev = "SI", name = "Slovenia" },
         new Flag { abbrev = "SB", name = "Insulele Solomon" },
         new Flag { abbrev = "SO", name = "Somalia" },
         new Flag { abbrev = "ZA", name = "Africa de Sud" },
         new Flag { abbrev = "GS", name = "Georgia de Sud și Insulele Sandwich de Sud" },
         new Flag { abbrev = "SS", name = "Sudanul de Sud" },
         new Flag { abbrev = "ES", name = "Spania" },
         new Flag { abbrev = "LK", name = "Sri Lanka" },
         new Flag { abbrev = "SD", name = "Sudan" },
         new Flag { abbrev = "SR", name = "Surinam" },
         new Flag { abbrev = "SJ", name = "Insulele Svalbard și Jan Mayen" },
         new Flag { abbrev = "SZ", name = "Swaziland" },
         new Flag { abbrev = "SE", name = "Suedia" },
         new Flag { abbrev = "CH", name = "Elveția" },
         new Flag { abbrev = "SY", name = "Republica Arabă Siriană (Siria)" },
         new Flag { abbrev = "TW", name = "Taiwan, Republica Chineză" },
         new Flag { abbrev = "TJ", name = "Tadjikistan" },
         new Flag { abbrev = "TZ", name = "Tanzania, Republica Unită" },
         new Flag { abbrev = "TH", name = "Thailanda" },
         new Flag { abbrev = "TL", name = "Timor-Leste" },
         new Flag { abbrev = "TG", name = "Togo" },
         new Flag { abbrev = "TK", name = "Tokelau" },
         new Flag { abbrev = "TO", name = "Tonga" },
         new Flag { abbrev = "TT", name = "Trinidad și Tobago" },
         new Flag { abbrev = "TN", name = "Tunisia" },
         new Flag { abbrev = "TR", name = "Turcia" },
         new Flag { abbrev = "TM", name = "Turkmenistan" },
         new Flag { abbrev = "TC", name = "Insulele Turks și Caicos" },
         new Flag { abbrev = "TV", name = "Tuvalu" },
         new Flag { abbrev = "UG", name = "Uganda" },
         new Flag { abbrev = "UA", name = "Ucraina" },
         new Flag { abbrev = "AE", name = "Emiratele Arabe Unite" },
         new Flag { abbrev = "GB", name = "Marea Britanie" },
         new Flag { abbrev = "SUA", name = "Statele Unite ale Americii" },
         new Flag { abbrev = "SUA", name = "UM Insulele Periferice Minore" },
         new Flag { abbrev = "UY", name = "Uruguay" },
         new Flag { abbrev = "UZ", name = "Uzbekistan" },
         new Flag { abbrev = "VU", name = "Vanuatu" },
         new Flag { abbrev = "VE", name = "Venezuela (Republica Bolivariană)" },
         new Flag { abbrev = "VN", name = "Vietnam" },
         new Flag { abbrev = "VI", name = "Insulele Virgine, SUA" },
         new Flag { abbrev = "WF", name = "Insulele Wallis și Futuna" },
         new Flag { abbrev = "EH", name = "Sahara Occidentală" },
         new Flag { abbrev = "DA", name = "Yemen" },
         new Flag { abbrev = "ZM", name = "Zambia" },
         new Flag { abbrev = "ZW", name = "Zimbabwe" },
         new Flag { abbrev = "DA", name = "Yemen" },
         new Flag { abbrev = "ZM", name = "Zambia" },
         new Flag { abbrev = "ZW", name = "Zimbabwe" }
    };

    public static List<Flag> world_FR = new List<Flag>()
    {
         new Flag { abbrev = "afghane", name = "AF" },
         new Flag { abbrev = "AX", name = "Îles Aland" },
         new Flag { abbrev = "AL", name = "Albanie" },
         new Flag { abbrev = "DZ", name = "Algérie" },
         new Flag { abbrev = "AS", name = "Samoa américaines" },
         new Flag { abbrev = "AD", name = "Andorre" },
         new Flag { abbrev = "AO", name = "Angola" },
         new Flag { abbrev = "d'Anguilla", name = "L'IA" },
         new Flag { abbrev = "Antarctique", name = "QA" },
         new Flag { abbrev = "SA", name = "Antigua-et-Barbuda" },
         new Flag { abbrev = "AR", name = "Argentine" },
         new Flag { abbrev = "AM", name = "Arménie" },
         new Flag { abbrev = "AW", name = "Aruba" },
         new Flag { abbrev = "AU", name = "Australie" },
         new Flag { abbrev = "AT", name = "Autriche" },
         new Flag { abbrev = "AZ", name = "Azerbaïdjan" },
         new Flag { abbrev = "BS", name = "Bahamas" },
         new Flag { abbrev = "BH", name = "Bahreïn" },
         new Flag { abbrev = "BD", name = "Bangladesh" },
         new Flag { abbrev = "BB", name = "Barbade" },
         new Flag { abbrev = "PAR", name = "Biélorussie" },
         new Flag { abbrev = "BE", name = "Belgique" },
         new Flag { abbrev = "BZ", name = "Belize" },
         new Flag { abbrev = "BJ", name = "Bénin" },
         new Flag { abbrev = "BM", name = "Bermudes" },
         new Flag { abbrev = "BT", name = "Bhoutan" },
         new Flag { abbrev = "BO", name = "Bolivie" },
         new Flag { abbrev = "Bosnie-Herzégovine", name = "BA" },
         new Flag { abbrev = "BW", name = "Botswana" },
         new Flag { abbrev = "BV", name = "Île Bouvet" },
         new Flag { abbrev = "BR", name = "Brésil" },
         new Flag { abbrev = "VG", name = "Îles Vierges britanniques" },
         new Flag { abbrev = "OI", name = "Territoire britannique de l'océan Indien" },
         new Flag { abbrev = "BN", name = "Brunéi Darussalam" },
         new Flag { abbrev = "BG", name = "Bulgarie" },
         new Flag { abbrev = "BF", name = "Burkina Faso" },
         new Flag { abbrev = "BI", name = "Burundi" },
         new Flag { abbrev = "KH", name = "Cambodge" },
         new Flag { abbrev = "CM", name = "Cameroun" },
         new Flag { abbrev = "CA", name = "Canada" },
         new Flag { abbrev = "Vert", name = "CV Cap" },
         new Flag { abbrev = "KY", name = "Îles Caïmans" },
         new Flag { abbrev = "CF", name = "République centrafricaine" },
         new Flag { abbrev = "TD", name = "Tchad" },
         new Flag { abbrev = "CL", name = "Chili" },
         new Flag { abbrev = "CN", name = "Chine" },
         new Flag { abbrev = "HK", name = "Hong Kong, RAS Chine" },
         new Flag { abbrev = "MO", name = "Macao, RAS Chine" },
         new Flag { abbrev = "CX", name = "Île de Noël" },
         new Flag { abbrev = "CC", name = "Îles Cocos (Keeling)" },
         new Flag { abbrev = "CO", name = "Colombie" },
         new Flag { abbrev = "KM", name = "Comores" },
         new Flag { abbrev = "CG", name = "Congo (Brazzaville)" },
         new Flag { abbrev = "CD", name = "Congo, (Kinshasa)" },
         new Flag { abbrev = "CK", name = "Îles Cook" },
         new Flag { abbrev = "RC", name = "Costa Rica" },
         new Flag { abbrev = "CI", name = "Côte d'Ivoire" },
         new Flag { abbrev = "RH", name = "Croatie" },
         new Flag { abbrev = "CU", name = "Cuba" },
         new Flag { abbrev = "CY", name = "Chypre" },
         new Flag { abbrev = "CZ", name = "République tchèque" },
         new Flag { abbrev = "DK", name = "Danemark" },
         new Flag { abbrev = "djiboutien", name = "DJ" },
         new Flag { abbrev = "DM", name = "Dominique" },
         new Flag { abbrev = "DO", name = "République dominicaine" },
         new Flag { abbrev = "CE", name = "Equateur" },
         new Flag { abbrev = "EG", name = "Égypte" },
         new Flag { abbrev = "SV", name = "Salvador" },
         new Flag { abbrev = "GQ", name = "Guinée équatoriale" },
         new Flag { abbrev = "Érythrée", name = "urgence" },
         new Flag { abbrev = "EE", name = "Estonie" },
         new Flag { abbrev = "ET", name = "Éthiopie" },
         new Flag { abbrev = "FK", name = "Îles Falkland (Malvinas)" },
         new Flag { abbrev = "FO", name = "Iles Féroé" },
         new Flag { abbrev = "FJ", name = "Fidji" },
         new Flag { abbrev = "FI", name = "Finlande" },
         new Flag { abbrev = "FR", name = "France" },
         new Flag { abbrev = "GF", name = "Guyane française" },
         new Flag { abbrev = "PF", name = "Polynésie française" },
         new Flag { abbrev = "Françaises", name = "TF Terres Australes" },
         new Flag { abbrev = "Gabon", name = "GA" },
         new Flag { abbrev = "DG", name = "Gambie" },
         new Flag { abbrev = "GE", name = "Géorgie" },
         new Flag { abbrev = "DE", name = "Allemagne" },
         new Flag { abbrev = "GH", name = "Ghana" },
         new Flag { abbrev = "IG", name = "Gibraltar" },
         new Flag { abbrev = "GR", name = "Grèce" },
         new Flag { abbrev = "GL", name = "Groenland" },
         new Flag { abbrev = "GD", name = "Grenade" },
         new Flag { abbrev = "Guadeloupe", name = "GP de" },
         new Flag { abbrev = "GU", name = "Guam" },
         new Flag { abbrev = "GT", name = "Guatemala" },
         new Flag { abbrev = "GG", name = "Guernesey" },
         new Flag { abbrev = "GN", name = "Guinée" },
         new Flag { abbrev = "GW", name = "Guinée-Bissau" },
         new Flag { abbrev = "GY", name = "Guyane" },
         new Flag { abbrev = "HT", name = "Haïti" },
         new Flag { abbrev = "HM", name = "Îles Heard et McDonald" },
         new Flag { abbrev = "VA", name = "Saint-Siège (État de la Cité du Vatican)" },
         new Flag { abbrev = "HN", name = "Honduras" },
         new Flag { abbrev = "HU", name = "Hongrie" },
         new Flag { abbrev = "est", name = "L'Islande" },
         new Flag { abbrev = "EN", name = "Inde" },
         new Flag { abbrev = "Indonésie", name = "ID" },
         new Flag { abbrev = "RI", name = "Iran, République islamique de" },
         new Flag { abbrev = "QI", name = "Irak" },
         new Flag { abbrev = "IE", name = "Irlande" },
         new Flag { abbrev = "IM", name = "Île de Man" },
         new Flag { abbrev = "IL", name = "Israël" },
         new Flag { abbrev = "IT", name = "Italie" },
         new Flag { abbrev = "JM", name = "Jamaïque" },
         new Flag { abbrev = "JP", name = "Japon" },
         new Flag { abbrev = "JE", name = "Maillot" },
         new Flag { abbrev = "JO", name = "Jordanie" },
         new Flag { abbrev = "KZ", name = "Kazakhstan" },
         new Flag { abbrev = "KE", name = "Kenya" },
         new Flag { abbrev = "KI", name = "Kiribati" },
         new Flag { abbrev = "KP", name = "Corée (Nord)" },
         new Flag { abbrev = "KR", name = "Corée (du Sud)" },
         new Flag { abbrev = "KW", name = "Koweït" },
         new Flag { abbrev = "KG", name = "Kirghizistan" },
         new Flag { abbrev = "LA", name = "RDP lao" },
         new Flag { abbrev = "LV", name = "Lettonie" },
         new Flag { abbrev = "LB", name = "Liban" },
         new Flag { abbrev = "LS", name = "Lesotho" },
         new Flag { abbrev = "LR", name = "Libéria" },
         new Flag { abbrev = "LY", name = "Libye" },
         new Flag { abbrev = "LI", name = "Liechtenstein" },
         new Flag { abbrev = "LT", name = "Lituanie" },
         new Flag { abbrev = "LU", name = "Luxembourg" },
         new Flag { abbrev = "MK", name = "Macédoine, République de" },
         new Flag { abbrev = "MG", name = "Madagascar" },
         new Flag { abbrev = "MW", name = "Malawi" },
         new Flag { abbrev = "MA", name = "Malaisie" },
         new Flag { abbrev = "MV", name = "Maldives" },
         new Flag { abbrev = "ML", name = "Mali" },
         new Flag { abbrev = "MT", name = "Malte" },
         new Flag { abbrev = "MH", name = "Îles Marshall" },
         new Flag { abbrev = "MQ", name = "Martinique" },
         new Flag { abbrev = "MR", name = "Mauritanie" },
         new Flag { abbrev = "Maurice", name = "UM" },
         new Flag { abbrev = "YT", name = "Mayotte" },
         new Flag { abbrev = "MX", name = "Mexique" },
         new Flag { abbrev = "FM", name = "Micronésie, États fédérés de" },
         new Flag { abbrev = "Moldavie", name = "MD" },
         new Flag { abbrev = "MC", name = "Monaco" },
         new Flag { abbrev = "MN", name = "Mongolie" },
         new Flag { abbrev = "ME", name = "Monténégro" },
         new Flag { abbrev = "MS", name = "Montserrat" },
         new Flag { abbrev = "MA", name = "Maroc" },
         new Flag { abbrev = "MZ", name = "Mozambique" },
         new Flag { abbrev = "MM", name = "Birmanie" },
         new Flag { abbrev = "NA", name = "Namibie" },
         new Flag { abbrev = "Nord", name = "Nauru" },
         new Flag { abbrev = "NP", name = "Népal" },
         new Flag { abbrev = "NL", name = "Pays-Bas" },
         new Flag { abbrev = "AN", name = "Antilles néerlandaises" },
         new Flag { abbrev = "NC", name = "Nouvelle Calédonie" },
         new Flag { abbrev = "NZ", name = "Nouvelle-Zélande" },
         new Flag { abbrev = "NI", name = "Nicaragua" },
         new Flag { abbrev = "NE", name = "Niger" },
         new Flag { abbrev = "NG", name = "Nigéria" },
         new Flag { abbrev = "NU", name = "Nioué" },
         new Flag { abbrev = "NF", name = "Île Norfolk" },
         new Flag { abbrev = "Nord", name = "Député des îles Mariannes du" },
         new Flag { abbrev = "NON", name = "Norvège" },
         new Flag { abbrev = "OM", name = "Oman" },
         new Flag { abbrev = "PK", name = "Pakistan" },
         new Flag { abbrev = "PW", name = "Palaos" },
         new Flag { abbrev = "PS", name = "Territoire palestinien" },
         new Flag { abbrev = "panaméenne", name = "PA" },
         new Flag { abbrev = "PG", name = "Papouasie-Nouvelle-Guinée" },
         new Flag { abbrev = "PY", name = "Paraguay" },
         new Flag { abbrev = "PE", name = "Pérou" },
         new Flag { abbrev = "PH", name = "Philippines" },
         new Flag { abbrev = "PN", name = "Pitcairn" },
         new Flag { abbrev = "PL", name = "Pologne" },
         new Flag { abbrev = "TP", name = "Portugal" },
         new Flag { abbrev = "Rico", name = "Relations publiques de Porto" },
         new Flag { abbrev = "Qatar", name = "AQ du" },
         new Flag { abbrev = "RE", name = "Réunion" },
         new Flag { abbrev = "RO", name = "Roumanie" },
         new Flag { abbrev = "RU", name = "Fédération de Russie" },
         new Flag { abbrev = "AD", name = "Rwanda" },
         new Flag { abbrev = "BL", name = "Saint-Barthélemy" },
         new Flag { abbrev = "SH", name = "Sainte-Hélène" },
         new Flag { abbrev = "KN", name = "Saint-Kitts-et-Nevis" },
         new Flag { abbrev = "LC", name = "Sainte-Lucie" },
         new Flag { abbrev = "MF", name = "Saint-Martin (partie française)" },
         new Flag { abbrev = "PM", name = "Saint Pierre et Miquelon" },
         new Flag { abbrev = "VC", name = "Saint-Vincent-et-les Grenadines" },
         new Flag { abbrev = "WS", name = "Samoa" },
         new Flag { abbrev = "SM", name = "Saint-Marin" },
         new Flag { abbrev = "Principe", name = "Rue Sao Tomé et" },
         new Flag { abbrev = "SA", name = "Arabie Saoudite" },
         new Flag { abbrev = "SN", name = "Sénégal" },
         new Flag { abbrev = "RS", name = "Serbie" },
         new Flag { abbrev = "Seychelles", name = "" },
         new Flag { abbrev = "SL", name = "Sierra Leone" },
         new Flag { abbrev = "SG", name = "Singapour" },
         new Flag { abbrev = "SK", name = "Slovaquie" },
         new Flag { abbrev = "SI", name = "Slovénie" },
         new Flag { abbrev = "SB", name = "Îles Salomon" },
         new Flag { abbrev = "SO", name = "Somalie" },
         new Flag { abbrev = "ZA", name = "Afrique du Sud" },
         new Flag { abbrev = "Sud", name = "GS de Géorgie du Sud et des îles Sandwich du" },
         new Flag { abbrev = "Sud", name = "SS du Soudan du" },
         new Flag { abbrev = "ES", name = "Espagne" },
         new Flag { abbrev = "LK", name = "Sri Lanka" },
         new Flag { abbrev = "SD", name = "Soudan" },
         new Flag { abbrev = "RS", name = "Suriname" },
         new Flag { abbrev = "SJ", name = "Îles Svalbard et Jan Mayen" },
         new Flag { abbrev = "SZ", name = "Swaziland" },
         new Flag { abbrev = "SE", name = "Suède" },
         new Flag { abbrev = "CH", name = "Suisse" },
         new Flag { abbrev = "SY", name = "République arabe syrienne (Syrie)" },
         new Flag { abbrev = "TW", name = "Taïwan, République de Chine" },
         new Flag { abbrev = "TJ", name = "Tadjikistan" },
         new Flag { abbrev = "TZ", name = "Tanzanie, République-Unie de" },
         new Flag { abbrev = "TH", name = "Thaïlande" },
         new Flag { abbrev = "TL", name = "Timor oriental" },
         new Flag { abbrev = "TG", name = "Togo" },
         new Flag { abbrev = "Tokélaou", name = "TK des" },
         new Flag { abbrev = "VERS", name = "Tonga" },
         new Flag { abbrev = "TT", name = "Trinité-et-Tobago" },
         new Flag { abbrev = "TN", name = "Tunisie" },
         new Flag { abbrev = "TR", name = "Turquie" },
         new Flag { abbrev = "TM", name = "Turkménistan" },
         new Flag { abbrev = "Caïques", name = "TC des îles Turques et" },
         new Flag { abbrev = "Tuvalu", name = "Télévision de" },
         new Flag { abbrev = "UG", name = "Ouganda" },
         new Flag { abbrev = "UA", name = "Ukraine" },
         new Flag { abbrev = "AE", name = "Émirats arabes unis" },
         new Flag { abbrev = "GB", name = "Royaume-Uni" },
         new Flag { abbrev = "d'Amérique", name = "États-Unis" },
         new Flag { abbrev = "UM", name = "Îles mineures éloignées des États-Unis" },
         new Flag { abbrev = "UY", name = "Uruguay" },
         new Flag { abbrev = "UZ", name = "Ouzbékistan" },
         new Flag { abbrev = "VU", name = "Vanuatu" },
         new Flag { abbrev = "VE", name = "Venezuela (République bolivarienne)" },
         new Flag { abbrev = "VN", name = "Vietnam" },
         new Flag { abbrev = "VI", name = "Îles Vierges, États-Unis" },
         new Flag { abbrev = "WF", name = "Îles Wallis et Futuna" },
         new Flag { abbrev = "EH", name = "Sahara occidental" },
         new Flag { abbrev = "OUI", name = "Yémen" },
         new Flag { abbrev = "ZM", name = "Zambie" },
         new Flag { abbrev = "ZW", name = "Zimbabwe" },
         new Flag { abbrev = "OUI", name = "Yémen" },
         new Flag { abbrev = "ZM", name = "Zambie" },
         new Flag { abbrev = "ZW", name = "Zimbabwe" }
    };

    public static List<Flag> world_ES = new List<Flag>()
    {
         new Flag { abbrev = "AF", name = "Afganistán" },
         new Flag { abbrev = "Aland", name = "Hacha de las islas" },
         new Flag { abbrev = "AL", name = "Albania" },
         new Flag { abbrev = "DZ", name = "Argelia" },
         new Flag { abbrev = "AS", name = "Samoa Americana" },
         new Flag { abbrev = "AD", name = "Andorra" },
         new Flag { abbrev = "AO", name = "Angola" },
         new Flag { abbrev = "Anguila", name = "IA de" },
         new Flag { abbrev = "AQ", name = "Antártida" },
         new Flag { abbrev = "AG", name = "Antigua y Barbuda" },
         new Flag { abbrev = "AR", name = "Argentina" },
         new Flag { abbrev = "AM", name = "Armenia" },
         new Flag { abbrev = "AW", name = "Aruba" },
         new Flag { abbrev = "AU", name = "Australia" },
         new Flag { abbrev = "AT", name = "Austria" },
         new Flag { abbrev = "AZ", name = "Azerbaiyán" },
         new Flag { abbrev = "BS", name = "Bahamas" },
         new Flag { abbrev = "BH", name = "Baréin" },
         new Flag { abbrev = "BD", name = "Bangladesh" },
         new Flag { abbrev = "BB", name = "Barbados" },
         new Flag { abbrev = "BY", name = "Bielorrusia" },
         new Flag { abbrev = "BE", name = "Bélgica" },
         new Flag { abbrev = "BZ", name = "Belice" },
         new Flag { abbrev = "BJ", name = "Benin" },
         new Flag { abbrev = "BM", name = "Bermudas" },
         new Flag { abbrev = "BT", name = "Bután" },
         new Flag { abbrev = "BO", name = "Bolivia" },
         new Flag { abbrev = "BA", name = "Bosnia y Herzegovina" },
         new Flag { abbrev = "BW", name = "Botswana" },
         new Flag { abbrev = "BV", name = "Bouvet Island" },
         new Flag { abbrev = "BR", name = "Brasil" },
         new Flag { abbrev = "VG", name = "Islas Vírgenes Británicas" },
         new Flag { abbrev = "IO", name = "Territorio Británico del Océano Índico" },
         new Flag { abbrev = "BN", name = "Brunei Darussalam" },
         new Flag { abbrev = "BG", name = "Bulgaria" },
         new Flag { abbrev = "BF", name = "Burkina Faso" },
         new Flag { abbrev = "BI", name = "Burundi" },
         new Flag { abbrev = "KH", name = "Camboya" },
         new Flag { abbrev = "CM", name = "Camerún" },
         new Flag { abbrev = "CA", name = "Canadá" },
         new Flag { abbrev = "CV", name = "Cabo Verde" },
         new Flag { abbrev = "KY", name = "Islas Caimán" },
         new Flag { abbrev = "CF", name = "República Centroafricana" },
         new Flag { abbrev = "TD", name = "Chad" },
         new Flag { abbrev = "CL", name = "Chile" },
         new Flag { abbrev = "CN", name = "China" },
         new Flag { abbrev = "HK", name = "Hong Kong, RAE de China" },
         new Flag { abbrev = "MO", name = "Macao, RAE de China" },
         new Flag { abbrev = "CX", name = "Isla de Navidad" },
         new Flag { abbrev = "CC", name = "Islas Cocos (Keeling)" },
         new Flag { abbrev = "CO", name = "Colombia" },
         new Flag { abbrev = "KM", name = "Comoras" },
         new Flag { abbrev = "CG", name = "Congo (Brazzaville)" },
         new Flag { abbrev = "CD", name = "Congo, (Kinshasa)" },
         new Flag { abbrev = "CK", name = "Islas Cook" },
         new Flag { abbrev = "CR", name = "Costa Rica" },
         new Flag { abbrev = "CI", name = "Costa de Marfil" },
         new Flag { abbrev = "HR", name = "Croacia" },
         new Flag { abbrev = "CU", name = "Cuba" },
         new Flag { abbrev = "CY", name = "Chipre" },
         new Flag { abbrev = "CZ", name = "República Checa" },
         new Flag { abbrev = "DK", name = "Dinamarca" },
         new Flag { abbrev = "DJ", name = "Djibouti" },
         new Flag { abbrev = "DM", name = "Dominica" },
         new Flag { abbrev = "DO", name = "República Dominicana" },
         new Flag { abbrev = "EC", name = "Ecuador" },
         new Flag { abbrev = "EG", name = "Egipto" },
         new Flag { abbrev = "SV", name = "El Salvador" },
         new Flag { abbrev = "GQ", name = "Guinea Ecuatorial" },
         new Flag { abbrev = "Eritrea", name = "ER" },
         new Flag { abbrev = "EE", name = "Estonia" },
         new Flag { abbrev = "ET", name = "Etiopía" },
         new Flag { abbrev = "FK", name = "Islas Malvinas (Falkland)" },
         new Flag { abbrev = "FO", name = "Islas Feroe" },
         new Flag { abbrev = "FJ", name = "Fiyi" },
         new Flag { abbrev = "FI", name = "Finlandia" },
         new Flag { abbrev = "FR", name = "Francia" },
         new Flag { abbrev = "GF", name = "Guayana Francesa" },
         new Flag { abbrev = "PF", name = "Polinesia Francesa" },
         new Flag { abbrev = "TF", name = "Territorios Australes Franceses" },
         new Flag { abbrev = "GA", name = "Gabón" },
         new Flag { abbrev = "GM", name = "Gambia" },
         new Flag { abbrev = "GE", name = "Georgia" },
         new Flag { abbrev = "DE", name = "Alemania" },
         new Flag { abbrev = "GH", name = "Ghana" },
         new Flag { abbrev = "GI", name = "Gibraltar" },
         new Flag { abbrev = "GR", name = "Grecia" },
         new Flag { abbrev = "GL", name = "Groenlandia" },
         new Flag { abbrev = "GD", name = "Granada" },
         new Flag { abbrev = "Guadalupe", name = "GP de" },
         new Flag { abbrev = "GU", name = "Guam" },
         new Flag { abbrev = "GT", name = "Guatemala" },
         new Flag { abbrev = "GG", name = "Guernsey" },
         new Flag { abbrev = "GN", name = "Guinea" },
         new Flag { abbrev = "GW", name = "Guinea-Bissau" },
         new Flag { abbrev = "GY", name = "Guyana" },
         new Flag { abbrev = "HT", name = "Haití" },
         new Flag { abbrev = "HM", name = "Islas Heard y Mcdonald" },
         new Flag { abbrev = "VA", name = "Santa Sede (Estado de la Ciudad del Vaticano)" },
         new Flag { abbrev = "HN", name = "Honduras" },
         new Flag { abbrev = "HU", name = "Hungría" },
         new Flag { abbrev = "es", name = "Islandia" },
         new Flag { abbrev = "EN", name = "India" },
         new Flag { abbrev = "Indonesia", name = "Identificación de" },
         new Flag { abbrev = "IR", name = "Irán, República Islámica del" },
         new Flag { abbrev = "Irak", name = "IQ de" },
         new Flag { abbrev = "IE", name = "Irlanda" },
         new Flag { abbrev = "IM", name = "Isla de Man" },
         new Flag { abbrev = "IL", name = "Israel" },
         new Flag { abbrev = "IT", name = "Italia" },
         new Flag { abbrev = "JM", name = "Jamaica" },
         new Flag { abbrev = "JP", name = "Japón" },
         new Flag { abbrev = "JE", name = "Jersey" },
         new Flag { abbrev = "JO", name = "Jordan" },
         new Flag { abbrev = "KZ", name = "Kazajstán" },
         new Flag { abbrev = "KE", name = "Kenia" },
         new Flag { abbrev = "KI", name = "Kiribati" },
         new Flag { abbrev = "KP", name = "Corea (Norte)" },
         new Flag { abbrev = "KR", name = "Corea (Sur)" },
         new Flag { abbrev = "KW", name = "Kuwait" },
         new Flag { abbrev = "KG", name = "Kirguistán" },
         new Flag { abbrev = "LA", name = "Laos PDR" },
         new Flag { abbrev = "LV", name = "Letonia" },
         new Flag { abbrev = "LB", name = "Líbano" },
         new Flag { abbrev = "LS", name = "Lesoto" },
         new Flag { abbrev = "LR", name = "Liberia" },
         new Flag { abbrev = "LY", name = "Libia" },
         new Flag { abbrev = "LI", name = "Liechtenstein" },
         new Flag { abbrev = "LT", name = "Lituania" },
         new Flag { abbrev = "Luxemburgo", name = "LU de" },
         new Flag { abbrev = "MK", name = "Macedonia, República de" },
         new Flag { abbrev = "MG", name = "Madagascar" },
         new Flag { abbrev = "MW", name = "Malawi" },
         new Flag { abbrev = "MI", name = "Malasia" },
         new Flag { abbrev = "MV", name = "Maldivas" },
         new Flag { abbrev = "ML", name = "Malí" },
         new Flag { abbrev = "MT", name = "Malta" },
         new Flag { abbrev = "MH", name = "Islas Marshall" },
         new Flag { abbrev = "MQ", name = "Martinica" },
         new Flag { abbrev = "MR", name = "Mauritania" },
         new Flag { abbrev = "MU", name = "Mauricio" },
         new Flag { abbrev = "YT", name = "Mayotte" },
         new Flag { abbrev = "MX", name = "México" },
         new Flag { abbrev = "FM", name = "Micronesia, Estados Federados de" },
         new Flag { abbrev = "MD", name = "Moldavia" },
         new Flag { abbrev = "MC", name = "Mónaco" },
         new Flag { abbrev = "MN", name = "Mongolia" },
         new Flag { abbrev = "ME", name = "Montenegro" },
         new Flag { abbrev = "MS", name = "Montserrat" },
         new Flag { abbrev = "MA", name = "Marruecos" },
         new Flag { abbrev = "MZ", name = "Mozambique" },
         new Flag { abbrev = "MM", name = "Myanmar" },
         new Flag { abbrev = "NA", name = "Namibia" },
         new Flag { abbrev = "NR", name = "Nauru" },
         new Flag { abbrev = "NP", name = "Nepal" },
         new Flag { abbrev = "NL", name = "Holanda" },
         new Flag { abbrev = "AN", name = "Antillas Holandesas" },
         new Flag { abbrev = "NC", name = "Nueva Caledonia" },
         new Flag { abbrev = "NZ", name = "Nueva Zelanda" },
         new Flag { abbrev = "NI", name = "Nicaragua" },
         new Flag { abbrev = "NE", name = "Níger" },
         new Flag { abbrev = "NG", name = "Nigeria" },
         new Flag { abbrev = "NU", name = "Niue" },
         new Flag { abbrev = "NF", name = "Isla Norfolk" },
         new Flag { abbrev = "Norte", name = "Diputado de las Islas Marianas del" },
         new Flag { abbrev = "NO", name = "Noruega" },
         new Flag { abbrev = "OM", name = "Omán" },
         new Flag { abbrev = "PK", name = "Pakistán" },
         new Flag { abbrev = "PW", name = "Palau" },
         new Flag { abbrev = "PS", name = "Territorio Palestino" },
         new Flag { abbrev = "PA", name = "Panamá" },
         new Flag { abbrev = "PG", name = "Papua Nueva Guinea" },
         new Flag { abbrev = "PY", name = "Paraguay" },
         new Flag { abbrev = "PE", name = "Perú" },
         new Flag { abbrev = "PH", name = "Filipinas" },
         new Flag { abbrev = "Pitcairn", name = "PN" },
         new Flag { abbrev = "PL", name = "Polonia" },
         new Flag { abbrev = "PT", name = "Portugal" },
         new Flag { abbrev = "PR", name = "Puerto Rico" },
         new Flag { abbrev = "QA", name = "Qatar" },
         new Flag { abbrev = "RE", name = "Reunión" },
         new Flag { abbrev = "RO", name = "Rumanía" },
         new Flag { abbrev = "RU", name = "Federación de Rusia" },
         new Flag { abbrev = "RW", name = "Ruanda" },
         new Flag { abbrev = "BL", name = "San Bartolomé" },
         new Flag { abbrev = "SH", name = "Santa Elena" },
         new Flag { abbrev = "KN", name = "Saint Kitts y Nevis" },
         new Flag { abbrev = "LC", name = "Santa Lucía" },
         new Flag { abbrev = "MF", name = "Saint-Martin (parte francesa)" },
         new Flag { abbrev = "PM", name = "San Pedro y Miquelón" },
         new Flag { abbrev = "VC", name = "San Vicente y las Granadinas" },
         new Flag { abbrev = "WS", name = "Samoa" },
         new Flag { abbrev = "SM", name = "San Marino" },
         new Flag { abbrev = "ST", name = "Santo Tomé y Príncipe" },
         new Flag { abbrev = "SA", name = "Arabia Saudita" },
         new Flag { abbrev = "SN", name = "Senegal" },
         new Flag { abbrev = "RS", name = "Serbia" },
         new Flag { abbrev = "SC", name = "Seychelles" },
         new Flag { abbrev = "SL", name = "Sierra Leona" },
         new Flag { abbrev = "SG", name = "Singapur" },
         new Flag { abbrev = "SK", name = "Eslovaquia" },
         new Flag { abbrev = "SI", name = "Eslovenia" },
         new Flag { abbrev = "SB", name = "Islas Salomón" },
         new Flag { abbrev = "SO", name = "Somalia" },
         new Flag { abbrev = "ZA", name = "Sudáfrica" },
         new Flag { abbrev = "GS", name = "Georgia del Sur y las Islas Sandwich del Sur" },
         new Flag { abbrev = "SS", name = "Sudán del Sur" },
         new Flag { abbrev = "ES", name = "España" },
         new Flag { abbrev = "LK", name = "Sri Lanka" },
         new Flag { abbrev = "SD", name = "Sudán" },
         new Flag { abbrev = "SR", name = "Surinam" },
         new Flag { abbrev = "SJ", name = "Islas Svalbard y Jan Mayen" },
         new Flag { abbrev = "SZ", name = "Swazilandia" },
         new Flag { abbrev = "SE", name = "Suecia" },
         new Flag { abbrev = "CH", name = "Suiza" },
         new Flag { abbrev = "SY", name = "República Árabe Siria (Siria)" },
         new Flag { abbrev = "TW", name = "Taiwán, República de China" },
         new Flag { abbrev = "TJ", name = "Tayikistán" },
         new Flag { abbrev = "TZ", name = "Tanzania, República Unida de" },
         new Flag { abbrev = "TH", name = "Tailandia" },
         new Flag { abbrev = "TL", name = "Timor-Leste" },
         new Flag { abbrev = "TG", name = "Togo" },
         new Flag { abbrev = "TK", name = "Tokelau" },
         new Flag { abbrev = "TO", name = "Tonga" },
         new Flag { abbrev = "TT", name = "Trinidad y Tobago" },
         new Flag { abbrev = "TN", name = "Túnez" },
         new Flag { abbrev = "TR", name = "Turquía" },
         new Flag { abbrev = "TM", name = "Turkmenistán" },
         new Flag { abbrev = "TC", name = "Islas Turcas y Caicos" },
         new Flag { abbrev = "TV", name = "Tuvalu" },
         new Flag { abbrev = "UG", name = "Uganda" },
         new Flag { abbrev = "UA", name = "Ucrania" },
         new Flag { abbrev = "AE", name = "Emiratos Árabes Unidos" },
         new Flag { abbrev = "GB", name = "Reino Unido" },
         new Flag { abbrev = "UU.", name = "Estados Unidos de América EE." },
         new Flag { abbrev = "UM", name = "Islas menores alejadas de EE. UU." },
         new Flag { abbrev = "UY", name = "Uruguay" },
         new Flag { abbrev = "UZ", name = "Uzbekistán" },
         new Flag { abbrev = "VU", name = "Vanuatu" },
         new Flag { abbrev = "VE", name = "Venezuela (República Bolivariana)" },
         new Flag { abbrev = "VN", name = "Vietnam" },
         new Flag { abbrev = "VI", name = "Islas Vírgenes, EE. UU." },
         new Flag { abbrev = "WF", name = "Islas Wallis y Futuna" },
         new Flag { abbrev = "EH", name = "Sáhara Occidental" },
         new Flag { abbrev = "YE", name = "Yemen" },
         new Flag { abbrev = "ZM", name = "Zambia" },
         new Flag { abbrev = "ZW", name = "Zimbabwe" },
         new Flag { abbrev = "YE", name = "Yemen" },
         new Flag { abbrev = "ZM", name = "Zambia" },
         new Flag { abbrev = "ZW", name = "Zimbabwe" }
};
}

